{
  "hash": "aa11c37864b6ae47f17eec03eb7d76e7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tutorial 10\"\nsubtitle: \"Regression with instrumental variables (part 2)\"\nauthor: \"Andrea Recine\"\ndate: today\nlang: en\ndescription: \"IV part 2: the Angrist & Evans (1998) samesex instrument for fertility and labor supply (labsup).\"\ncode-links:\n  - text: R Script\n    icon: file-code\n    href: tutorial10_script.R\n---\n\n\n\n# Angrist and Evans (1998)\n\nIn [*Children and Their Parents' Labor Supply: Evidence from Exogenous Variation in Family Size*](https://www.jstor.org/stable/116844?seq=1), published in the *American Economic Review*, Angrist and Evans analyze the effect of children on maternal labor supply (measured in this Tutorial as weekly hours worked).\n\nTo address the endogeneity of fertility decisions—arising from their possible correlation with other determinants of labor supply—Angrist and Evans focus on mothers with at least two children. They use two instruments: whether the first two children are of the same sex ($samesex$) and whether the second birth produced twins ($multi2nd$).\n\nThus:\n\n- $Y_i = hours_i$: the mother's weekly hours worked;\n- $X_i = kids_i$: number of children, **endogenous** with respect to $u_i$ (fertility decisions are correlated with unobserved determinants of labor supply);\n- $W_i$: included exogenous controls—$educ$, $age$, $black$, and $hispan$;\n- $Z_i$: the instrument(s)—$samesex$ (the first two children are of the same sex) and/or $multi2nd$ (the second birth produced twins).\n\nThe equation of interest is:\n\n$$\nhours_i = \\beta_0 + \\beta_1 kids_i + \\delta_1 educ_i + \\delta_2 age_i + \\delta_3 black_i + \\delta_4 hispan_i + u_i\n$$\n\n\n\n**Relevance** ($cor(Z_i, kids_i) \\neq 0$). The data show that families whose first two children are of the same sex are more likely to have a third child: among women with two children, the fraction who have a third rises from approximately 37%\n(*one boy/one girl*) to approximately 43% (same sex) in 1980 [Angrist & Evans 1998, Table 3, p. 457]. A twin second birth instead increases family size *mechanically*. This distinction matters: $samesex$ shifts $kids$ through preferences for a mixed-sex composition, whereas $multi2nd$ shifts $kids$ mechanically.\n\n**Conditional exogeneity** ($E(u_i \\mid W_i, Z_i) = E(u_i \\mid W_i) = 0$). For $samesex$, the sex composition of the first two children is effectively randomly assigned. Angrist and Evans show that, even in very large samples, mothers whose children are of the same sex do not differ in age, age at first birth, race, or education from mothers whose children are of different sexes (no difference is significant at the 5% level) [Angrist & Evans 1998, Table 4 and p. 458].\n\n\n\nThe argument for $multi2nd$ is more delicate. Twinning is correlated with observable maternal characteristics: it is more common among older, Black, and more highly educated women [p. 458]. For *Twins-2*, the differences in covariate means are consequently large and statistically significant (e.g., age $+0.25$, s.e. $0.06$; education $+0.094$, s.e. $0.042$) [Table 4, p. 459]. Exogeneity therefore holds **only conditional on observables**: all characteristics correlated with twinning must be observed and included among the controls $W_i$ [p. 469].\n\nIn both cases, the **exclusion restriction** requires that neither the children's sex composition nor a twin birth directly affect hours worked except through the number of children. In practice, $Z$ must affect $Y$ *only* through $X$ (no direct effect $Z \\to Y$), and $Z$ must be uncorrelated with the other unobserved determinants of $Y$. These are the two aspects of the condition $E(u_i \\mid W_i, Z_i) = E(u_i \\mid W_i) = 0$.\n\n\n::: {.callout-important title=\"samesex vs multi2nd\"}\n\nTable 4 of the paper reports differences in means between observations for which the instrument equals 1 and those for which it equals 0, with standard errors:\n\n- **samesex**: no significant differences → the instrument is balanced even *unconditionally*;\n\n- **multi2nd (Twins-2)**: large and significant differences in age, age at first birth, ethnicity, and education.\n\n:::\n\n\n::: {.callout-note title=\"Exclusion restriction for samesex\"}\nAngrist and Evans take seriously a potential concern about the exclusion of $samesex$: children's sex could affect labor supply through channels other than family size (paternal involvement, differential treatment of boys and girls, or a higher probability of disability among boys). The key point is that $samesex$ is an **interaction term**:\n$$\nsamesex = \\underbrace{s_1 s_2}_{\\text{Two boys}} + \\underbrace{(1-s_1)(1-s_2)}_{\\text{Two girls}},\n$$\nThe indicators for the sex of the first and second child ($s_1$, $s_2$) can therefore be included as **additive controls**—without absorbing the instrumental variation—to account for these direct effects and reduce omitted-variable bias [Angrist & Evans 1998, eq. (4)–(5), pp. 460–461].\n\nThe same decomposition into *Two boys* and *Two girls* provides two instruments. The **$J$ test** discussed below assesses precisely these direct effects, which would differ between two-boy and two-girl families even though the effect of a third child would not.\n\n\nThe specification used here with `labsup` does not include $s_1$ and $s_2$. This is a pedagogical simplification that should be kept in mind.\n:::\n\n\n\nThe `labsup` dataset contains a subset of the data used by Angrist and Evans (1998).\n\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(knitr)\nlibrary(kableExtra)\nlibrary(modelsummary)\nlibrary(fixest)\nlibrary(wooldridge)\nlibrary(car)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"labsup\", package = \"wooldridge\")\nhead(labsup)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  kids morekids boys2 girls2 boy1st boy2nd samesex multi2nd age agefstm black\n1    2        0     0      0      1      0       0        0  35      27     1\n2    3        1     0      0      0      1       0        0  32      20     1\n3    2        0     1      0      1      1       1        0  30      19     1\n4    2        0     0      0      1      0       0        0  33      23     1\n5    2        0     0      1      0      0       1        0  31      26     1\n6    2        0     0      0      1      0       0        0  35      24     1\n  hispan worked weeks hours   labinc   faminc  nonmomi educ agesq\n1      0      0     0     0  0.00000 44.45000 44.45000   14  1225\n2      0      1    40    40 14.70470 38.04750 23.34280   12  1024\n3      0      1    52    35 20.16255 20.59289  0.43033   12   900\n4      0      1    50    40 21.00222 83.98788 62.98569   14  1089\n5      0      1    26    48 21.86289 88.82650 66.96363   12   961\n6      0      1    52    40 40.39859 58.96578 18.56719   16  1225\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# IV model (samesex as an instrument for kids)\niv_labsup <- feols(hours ~ educ + age + black + hispan | kids ~ samesex, data = labsup, vcov = \"hetero\")\n```\n:::\n\n\n\nFirst stage:\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(iv_labsup, stage = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTSLS estimation\n|- D.V.   : hours\n|- Endo.  : kids\n|- Instr. : samesex\n|\n|=> First Stage\n|   Current Dep. Var.: kids\nObservations: 31,857\nStandard-errors: Heteroskedasticity-robust \n             Estimate Std. Error    t value   Pr(>|t|)    \n(Intercept)  2.024325   0.077092  26.258620  < 2.2e-16 ***\nsamesex      0.069651   0.010297   6.764490 1.3609e-11 ***\neduc        -0.089685   0.001994 -44.970520  < 2.2e-16 ***\nage          0.056773   0.001425  39.845729  < 2.2e-16 ***\nblack        0.032522   0.064401   0.504989 6.1357e-01    \nhispan      -0.037187   0.064513  -0.576431 5.6433e-01    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 0.918735   Adj. R2: 0.115896\nF-test (1st stage): stat = 45.762, p = 1.359e-11, on 1 and 31,851 DoF.\n```\n\n\n:::\n:::\n\n\n\n**Instrument relevance test:**\n\n::: {.cell}\n\n```{.r .cell-code}\nfitstat(iv_labsup, type = \"ivwald\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWald (1st stage), kids: stat = 45.758, p = 1.361e-11, on 1 and 31,851 DoF, VCOV: Heteroskedasticity-robust.\n```\n\n\n:::\n:::\n\n\n$F \\approx 45.8$: well above the rule-of-thumb threshold of 10, so $samesex$ is a **strong** instrument for $kids$.\n\n\nUsing `linearHypothesis`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfirst_stage <- feols(kids ~ samesex + educ + age + black + hispan, data = labsup, vcov = \"hetero\")\n\nlinearHypothesis(first_stage, \"samesex = 0\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLinear hypothesis test:\nsamesex = 0\n\nModel 1: restricted model\nModel 2: kids ~ samesex + educ + age + black + hispan\n\n  Res.Df Df  Chisq Pr(>Chisq)    \n1  31852                         \n2  31851  1 45.758  1.338e-11 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nThe Wald statistic exceeds $m \\times 10 = 10$, confirming the `fitstat` result.\n\n\nThe second-stage estimate is:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(iv_labsup)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTSLS estimation\n|- D.V.   : hours\n|- Endo.  : kids\n|- Instr. : samesex\n|\n|=> Second Stage\n|   Dep. Var.: hours\nObservations: 31,857\nStandard-errors: Heteroskedasticity-robust \n             Estimate Std. Error   t value  Pr(>|t|)    \n(Intercept) 18.442906   6.498657  2.837957 0.0045432 ** \nfit_kids    -5.071274   3.055844 -1.659533 0.0970183 .  \neduc         0.256421   0.276036  0.928940 0.3529273    \nage          0.548170   0.175927  3.115888 0.0018355 ** \nblack        1.551443   1.377751  1.126070 0.2601445    \nhispan      -5.110861   1.378488 -3.707584 0.0002096 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 19.0   Adj. R2: 0.057635\nF-test (1st stage), kids: stat = 45.76161, p = 1.359e-11, on 1 and 31,851 DoF.\n              Wu-Hausman: stat =  0.86766, p = 0.35161  , on 1 and 31,850 DoF.\n```\n\n\n:::\n:::\n\n\nComparison with OLS estimates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# OLS: hours worked and number of children\nols_labsup <- feols(hours ~ kids + educ + age + black + hispan, data = labsup, vcov = \"hetero\")\n\nmodelsummary(\n  list(\"OLS\" = ols_labsup,\n       \"IV\" = iv_labsup),\n  gof_omit = \"IC|Adj|RMSE\"\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_6vi8c5adiml2fjk0zxn7 = TinyTable.createTableFunctions(\"tinytable_6vi8c5adiml2fjk0zxn7\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '16', j: 2 }, { i: '16', j: 3 } ], css_id: 'tinytable_css_2rl2r8b10appf4tc0s39',}, \n          { positions: [ { i: '14', j: 2 }, { i: '14', j: 3 } ], css_id: 'tinytable_css_05o42jut9si7llxe9wyv',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '15', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 }, { i: '13', j: 3 }, { i: '15', j: 3 } ], css_id: 'tinytable_css_yerev97pffvy0nohirge',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_vo70436hzonpaq9anj5z',}, \n          { positions: [ { i: '16', j: 1 } ], css_id: 'tinytable_css_qvw1220fnyd3gs1ls8wf',}, \n          { positions: [ { i: '14', j: 1 } ], css_id: 'tinytable_css_undzjznb59uao7tdmma8',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 }, { i: '15', j: 1 } ], css_id: 'tinytable_css_25quaxsswqvrskchn7aw',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_y1y6zusry571k1x8fba6',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_6vi8c5adiml2fjk0zxn7.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_6vi8c5adiml2fjk0zxn7 td.tinytable_css_2rl2r8b10appf4tc0s39, #tinytable_6vi8c5adiml2fjk0zxn7 th.tinytable_css_2rl2r8b10appf4tc0s39 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_6vi8c5adiml2fjk0zxn7 td.tinytable_css_05o42jut9si7llxe9wyv, #tinytable_6vi8c5adiml2fjk0zxn7 th.tinytable_css_05o42jut9si7llxe9wyv {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_6vi8c5adiml2fjk0zxn7 td.tinytable_css_yerev97pffvy0nohirge, #tinytable_6vi8c5adiml2fjk0zxn7 th.tinytable_css_yerev97pffvy0nohirge { text-align: center }\n    #tinytable_6vi8c5adiml2fjk0zxn7 td.tinytable_css_vo70436hzonpaq9anj5z, #tinytable_6vi8c5adiml2fjk0zxn7 th.tinytable_css_vo70436hzonpaq9anj5z {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_6vi8c5adiml2fjk0zxn7 td.tinytable_css_qvw1220fnyd3gs1ls8wf, #tinytable_6vi8c5adiml2fjk0zxn7 th.tinytable_css_qvw1220fnyd3gs1ls8wf {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_6vi8c5adiml2fjk0zxn7 td.tinytable_css_undzjznb59uao7tdmma8, #tinytable_6vi8c5adiml2fjk0zxn7 th.tinytable_css_undzjznb59uao7tdmma8 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_6vi8c5adiml2fjk0zxn7 td.tinytable_css_25quaxsswqvrskchn7aw, #tinytable_6vi8c5adiml2fjk0zxn7 th.tinytable_css_25quaxsswqvrskchn7aw { text-align: left }\n    #tinytable_6vi8c5adiml2fjk0zxn7 td.tinytable_css_y1y6zusry571k1x8fba6, #tinytable_6vi8c5adiml2fjk0zxn7 th.tinytable_css_y1y6zusry571k1x8fba6 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_6vi8c5adiml2fjk0zxn7\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">OLS</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">IV</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">12.646</td>\n                  <td data-row=\"1\" data-col=\"3\">18.443</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(1.653)</td>\n                  <td data-row=\"2\" data-col=\"3\">(6.499)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">kids</td>\n                  <td data-row=\"3\" data-col=\"2\">-2.254</td>\n                  <td data-row=\"3\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.116)</td>\n                  <td data-row=\"4\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">educ</td>\n                  <td data-row=\"5\" data-col=\"2\">0.509</td>\n                  <td data-row=\"5\" data-col=\"3\">0.256</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.037)</td>\n                  <td data-row=\"6\" data-col=\"3\">(0.276)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">age</td>\n                  <td data-row=\"7\" data-col=\"2\">0.388</td>\n                  <td data-row=\"7\" data-col=\"3\">0.548</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\">(0.030)</td>\n                  <td data-row=\"8\" data-col=\"3\">(0.176)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">black</td>\n                  <td data-row=\"9\" data-col=\"2\">1.456</td>\n                  <td data-row=\"9\" data-col=\"3\">1.551</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\">(1.346)</td>\n                  <td data-row=\"10\" data-col=\"3\">(1.378)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">hispan</td>\n                  <td data-row=\"11\" data-col=\"2\">-5.011</td>\n                  <td data-row=\"11\" data-col=\"3\">-5.111</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\"></td>\n                  <td data-row=\"12\" data-col=\"2\">(1.347)</td>\n                  <td data-row=\"12\" data-col=\"3\">(1.378)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">fit_kids</td>\n                  <td data-row=\"13\" data-col=\"2\"></td>\n                  <td data-row=\"13\" data-col=\"3\">-5.071</td>\n                </tr>\n                <tr>\n                  <td data-row=\"14\" data-col=\"1\"></td>\n                  <td data-row=\"14\" data-col=\"2\"></td>\n                  <td data-row=\"14\" data-col=\"3\">(3.056)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"15\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"15\" data-col=\"2\">31857</td>\n                  <td data-row=\"15\" data-col=\"3\">31857</td>\n                </tr>\n                <tr>\n                  <td data-row=\"16\" data-col=\"1\">R2</td>\n                  <td data-row=\"16\" data-col=\"2\">0.069</td>\n                  <td data-row=\"16\" data-col=\"3\">0.058</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n::: {.callout-note title=\"Question\"}\n1. How should the coefficients on $educ$ and $kids$ in the OLS regression be interpreted?\n:::\n\n\n**Twin birth as an instrument.** We now estimate the model using $multi2nd$ as an instrument for $kids$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\niv_labsup_twins <- feols(hours ~ educ + age + black + hispan | kids ~ multi2nd, data = labsup, vcov = \"hetero\")\n```\n:::\n\n\nFirst stage:\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(iv_labsup_twins, stage = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTSLS estimation\n|- D.V.   : hours\n|- Endo.  : kids\n|- Instr. : multi2nd\n|\n|=> First Stage\n|   Current Dep. Var.: kids\nObservations: 31,857\nStandard-errors: Heteroskedasticity-robust \n             Estimate Std. Error    t value  Pr(>|t|)    \n(Intercept)  2.056117   0.077378  26.572338 < 2.2e-16 ***\nmulti2nd     0.762863   0.054704  13.945402 < 2.2e-16 ***\neduc        -0.089625   0.001993 -44.980147 < 2.2e-16 ***\nage          0.056604   0.001422  39.796354 < 2.2e-16 ***\nblack        0.031647   0.064960   0.487179   0.62614    \nhispan      -0.034899   0.065068  -0.536350   0.59172    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 0.916674   Adj. R2: 0.119859\nF-test (1st stage): stat = 189.38, p < 2.2e-16, on 1 and 31,851 DoF.\n```\n\n\n:::\n:::\n\n\nRelevance test:\n\n::: {.cell}\n\n```{.r .cell-code}\nfitstat(iv_labsup_twins, type = \"ivwald\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWald (1st stage), kids: stat = 194.47, p < 2.2e-16, on 1 and 31,851 DoF, VCOV: Heteroskedasticity-robust.\n```\n\n\n:::\n:::\n\n\nHere $Wald \\approx 194$: $multi2nd$ is a **strong** instrument and is even more relevant than $samesex$—a twin birth mechanically adds exactly one child and therefore produces a pronounced shift in $kids$.\n\nUsing `linearHypothesis`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfirst_stage_twins <- feols(kids ~ multi2nd + educ + age + black + hispan, data = labsup, vcov = \"hetero\")\n\nlinearHypothesis(first_stage_twins, \"multi2nd = 0\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLinear hypothesis test:\nmulti2nd = 0\n\nModel 1: restricted model\nModel 2: kids ~ multi2nd + educ + age + black + hispan\n\n  Res.Df Df  Chisq Pr(>Chisq)    \n1  31852                         \n2  31851  1 194.47  < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\nSecond stage:\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(iv_labsup_twins, stage = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTSLS estimation\n|- D.V.   : hours\n|- Endo.  : kids\n|- Instr. : multi2nd\n|\n|=> Second Stage\n|   Dep. Var.: hours\nObservations: 31,857\nStandard-errors: Heteroskedasticity-robust \n             Estimate Std. Error  t value   Pr(>|t|)    \n(Intercept) 13.109306   3.353528  3.90911 9.2829e-05 ***\nfit_kids    -2.478705   1.420373 -1.74511 8.0976e-02 .  \neduc         0.488897   0.132255  3.69663 2.1884e-04 ***\nage          0.400960   0.085949  4.66510 3.0971e-06 ***\nblack        1.463484   1.347660  1.08594 2.7751e-01    \nhispan      -5.019231   1.349187 -3.72019 1.9942e-04 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 18.8   Adj. R2: 0.057634\nF-test (1st stage), kids: stat = 189.37612, p < 2.2e-16 , on 1 and 31,851 DoF.\n              Wu-Hausman: stat =   0.02293, p = 0.879633, on 1 and 31,850 DoF.\n```\n\n\n:::\n:::\n\n\n\n**Comparison:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(\n  list(\"Hours (IV samesex)\" = iv_labsup ,\n       \"Hours (IV multi2nd)\" = iv_labsup_twins),\n  gof_omit = \"IC|Adj|RMSE\"\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_9xit3pq8o384lcb7qz36 = TinyTable.createTableFunctions(\"tinytable_9xit3pq8o384lcb7qz36\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '14', j: 2 }, { i: '14', j: 3 } ], css_id: 'tinytable_css_ve6ognv2ksbpnad30zyr',}, \n          { positions: [ { i: '12', j: 2 }, { i: '12', j: 3 } ], css_id: 'tinytable_css_82ngzbkfskghc54py45p',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '13', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '11', j: 3 }, { i: '13', j: 3 } ], css_id: 'tinytable_css_c4gmlo7rvrz77ic3m1pg',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_pdxqcf1354c4jx8agxgn',}, \n          { positions: [ { i: '14', j: 1 } ], css_id: 'tinytable_css_bolvrib1f3m4ktq7yo09',}, \n          { positions: [ { i: '12', j: 1 } ], css_id: 'tinytable_css_q7sphlby8f2ba90isqqe',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '13', j: 1 } ], css_id: 'tinytable_css_vzbe7y229xqtlcmk268b',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_nfsszaynl66500xbikm8',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_9xit3pq8o384lcb7qz36.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_9xit3pq8o384lcb7qz36 td.tinytable_css_ve6ognv2ksbpnad30zyr, #tinytable_9xit3pq8o384lcb7qz36 th.tinytable_css_ve6ognv2ksbpnad30zyr {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_9xit3pq8o384lcb7qz36 td.tinytable_css_82ngzbkfskghc54py45p, #tinytable_9xit3pq8o384lcb7qz36 th.tinytable_css_82ngzbkfskghc54py45p {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_9xit3pq8o384lcb7qz36 td.tinytable_css_c4gmlo7rvrz77ic3m1pg, #tinytable_9xit3pq8o384lcb7qz36 th.tinytable_css_c4gmlo7rvrz77ic3m1pg { text-align: center }\n    #tinytable_9xit3pq8o384lcb7qz36 td.tinytable_css_pdxqcf1354c4jx8agxgn, #tinytable_9xit3pq8o384lcb7qz36 th.tinytable_css_pdxqcf1354c4jx8agxgn {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_9xit3pq8o384lcb7qz36 td.tinytable_css_bolvrib1f3m4ktq7yo09, #tinytable_9xit3pq8o384lcb7qz36 th.tinytable_css_bolvrib1f3m4ktq7yo09 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_9xit3pq8o384lcb7qz36 td.tinytable_css_q7sphlby8f2ba90isqqe, #tinytable_9xit3pq8o384lcb7qz36 th.tinytable_css_q7sphlby8f2ba90isqqe {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_9xit3pq8o384lcb7qz36 td.tinytable_css_vzbe7y229xqtlcmk268b, #tinytable_9xit3pq8o384lcb7qz36 th.tinytable_css_vzbe7y229xqtlcmk268b { text-align: left }\n    #tinytable_9xit3pq8o384lcb7qz36 td.tinytable_css_nfsszaynl66500xbikm8, #tinytable_9xit3pq8o384lcb7qz36 th.tinytable_css_nfsszaynl66500xbikm8 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_9xit3pq8o384lcb7qz36\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Hours (IV samesex)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Hours (IV multi2nd)</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">18.443</td>\n                  <td data-row=\"1\" data-col=\"3\">13.109</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(6.499)</td>\n                  <td data-row=\"2\" data-col=\"3\">(3.354)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">fit_kids</td>\n                  <td data-row=\"3\" data-col=\"2\">-5.071</td>\n                  <td data-row=\"3\" data-col=\"3\">-2.479</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(3.056)</td>\n                  <td data-row=\"4\" data-col=\"3\">(1.420)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">educ</td>\n                  <td data-row=\"5\" data-col=\"2\">0.256</td>\n                  <td data-row=\"5\" data-col=\"3\">0.489</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.276)</td>\n                  <td data-row=\"6\" data-col=\"3\">(0.132)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">age</td>\n                  <td data-row=\"7\" data-col=\"2\">0.548</td>\n                  <td data-row=\"7\" data-col=\"3\">0.401</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\">(0.176)</td>\n                  <td data-row=\"8\" data-col=\"3\">(0.086)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">black</td>\n                  <td data-row=\"9\" data-col=\"2\">1.551</td>\n                  <td data-row=\"9\" data-col=\"3\">1.463</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\">(1.378)</td>\n                  <td data-row=\"10\" data-col=\"3\">(1.348)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">hispan</td>\n                  <td data-row=\"11\" data-col=\"2\">-5.111</td>\n                  <td data-row=\"11\" data-col=\"3\">-5.019</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\"></td>\n                  <td data-row=\"12\" data-col=\"2\">(1.378)</td>\n                  <td data-row=\"12\" data-col=\"3\">(1.349)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"13\" data-col=\"2\">31857</td>\n                  <td data-row=\"13\" data-col=\"3\">31857</td>\n                </tr>\n                <tr>\n                  <td data-row=\"14\" data-col=\"1\">R2</td>\n                  <td data-row=\"14\" data-col=\"2\">0.058</td>\n                  <td data-row=\"14\" data-col=\"3\">0.058</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n## Overidentification\n\nWe estimate the overidentified model using both instruments:\n\n\n::: {.cell}\n\n```{.r .cell-code}\niv_labsup_twins_over <- feols(hours ~ educ + age + black + hispan | kids ~ multi2nd + samesex, data = labsup, vcov = \"hetero\")\niv_labsup_twins_over\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTSLS estimation\n|- D.V.   : hours\n|- Endo.  : kids\n|- Instr. : multi2nd, samesex\n|\n|=> Second Stage\n|   Dep. Var.: hours\nObservations: 31,857\nStandard-errors: Heteroskedasticity-robust \n             Estimate Std. Error  t value   Pr(>|t|)    \n(Intercept) 14.151620   3.109413  4.55122 5.3533e-06 ***\nfit_kids    -2.985355   1.283110 -2.32666 1.9990e-02 *  \neduc         0.443466   0.120309  3.68605 2.2814e-04 ***\nage          0.429728   0.078625  5.46556 4.6489e-08 ***\nblack        1.480674   1.351190  1.09583 2.7316e-01    \nhispan      -5.037138   1.352479 -3.72437 1.9614e-04 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 18.8   Adj. R2: 0.057699\nF-test (1st stage), kids: stat = 117.87835, p < 2.2e-16 , on 2 and 31,850 DoF.\n              Wu-Hausman: stat =   0.30154, p = 0.582922, on 1 and 31,850 DoF.\n                  Sargan: stat =   0.58937, p = 0.442665, on 1 DoF.\n```\n\n\n:::\n:::\n\n\nThe first-stage estimates are:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(iv_labsup_twins_over, stage = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTSLS estimation\n|- D.V.   : hours\n|- Endo.  : kids\n|- Instr. : multi2nd, samesex\n|\n|=> First Stage\n|   Current Dep. Var.: kids\nObservations: 31,857\nStandard-errors: Heteroskedasticity-robust \n             Estimate Std. Error    t value   Pr(>|t|)    \n(Intercept)  2.023148   0.077123  26.232884  < 2.2e-16 ***\nmulti2nd     0.763023   0.054526  13.993755  < 2.2e-16 ***\nsamesex      0.069711   0.010266   6.790169 1.1397e-11 ***\neduc        -0.089639   0.001991 -45.012590  < 2.2e-16 ***\nage          0.056595   0.001421  39.814085  < 2.2e-16 ***\nblack        0.030240   0.064509   0.468776 6.3923e-01    \nhispan      -0.036745   0.064617  -0.568657 5.6959e-01    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 0.916011   Adj. R2: 0.121104\nF-test (1st stage): stat = 117.88, p < 2.2e-16, on 2 and 31,850 DoF.\n```\n\n\n:::\n:::\n\n\n\n**Joint relevance test.** We assess whether the two instruments are jointly strong:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitstat(iv_labsup_twins_over, type = \"ivwald\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWald (1st stage), kids: stat = 117.36, p < 2.2e-16, on 2 and 31,850 DoF, VCOV: Heteroskedasticity-robust.\n```\n\n\n:::\n:::\n\n\n\nUsing `linearHypothesis`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfirst_stage_over <- feols(kids ~ multi2nd + samesex + educ + age + black + hispan, data = labsup, vcov = \"hetero\")\n\nlinearHypothesis(first_stage_over, c(\"multi2nd = 0\", \"samesex = 0\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLinear hypothesis test:\nmulti2nd = 0\nsamesex = 0\n\nModel 1: restricted model\nModel 2: kids ~ multi2nd + samesex + educ + age + black + hispan\n\n  Res.Df Df  Chisq Pr(>Chisq)    \n1  31852                         \n2  31850  2 234.72  < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n$Wald \\approx 234.72$: well above the threshold $m \\times 10 = 20$. After adding $samesex$ to $multi2nd$, the instruments remain jointly **very strong**.\n\n\n**Note:** `fitstat` from `fixest` uses the $F$ distribution. Thus, `stat` = 117.36 equals 234.72/2 and is well above the threshold of 10.\n\n\n**$J$ test of overidentifying restrictions.**\n\n\nWe apply the same procedure used for Card (2SLS residuals obtained with `resid()`, an auxiliary regression, $J = m \\cdot F$, and a $p$-value from $\\chi^2_{m-\\ell}$). Here $m = 2$ and $\\ell = 1$.\n\n\nUnder $H_0$, $J \\sim \\chi^2_1$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlabsup <- labsup |> mutate(uhat = resid(iv_labsup_twins_over))\n\nJreg_labsup <- feols(uhat ~ educ + age + black + hispan + samesex + multi2nd, data = labsup, vcov = \"iid\")\n\n\nlinearHypothesis(Jreg_labsup, c(\"samesex = 0\", \"multi2nd = 0\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLinear hypothesis test:\nsamesex = 0\nmulti2nd = 0\n\nModel 1: restricted model\nModel 2: uhat ~ educ + age + black + hispan + samesex + multi2nd\n\n  Res.Df Df  Chisq Pr(>Chisq)\n1  31852                     \n2  31850  2 0.5892     0.7448\n```\n\n\n:::\n:::\n\n\n0.589 is below 3.84, so we do not reject the null hypothesis that the instruments are jointly exogenous.\n\n**Remember:** We must use critical values from the $\\chi^2$ distribution with $m - \\ell = 1$ degree of freedom. The 5% critical value is 3.84, so $J = 0.589$ is well below 3.84.\n\nThe correct $p$-value is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1 - pchisq(0.5892 , df = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4427286\n```\n\n\n:::\n:::\n\n\n\n**Verification using `fitstat` from `fixest`:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitstat(iv_labsup_twins_over, \"sargan\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSargan: stat = 0.58937, p = 0.442665, on 1 DoF.\n```\n\n\n:::\n:::\n\n\nThus, **we do not reject** the null hypothesis that the instruments are jointly exogenous. The caveat discussed for Card nevertheless still applies (see \"Asymmetry of the test\").\n",
    "supporting": [
      "tutorial10_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}