{
  "hash": "142ba5315a533ef2050f2017a6fa680f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tutorial 1\"\nsubtitle: \"Simple Linear Regression\"\nauthor: \"Andrea Recine\"\ndate: today\nlang: en\n---\n\n## Introduction\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(knitr)\nlibrary(tinytable)\nlibrary(modelsummary)\n```\n:::\n\n\n`library(tidyverse)` contains several packages, including:\n\n-   dplyr (data management)\n\n-   tidyr (data reshaping)\n\n-   ggplot2 (graphs)\n\n-   readr (CSV import and other data-import tools)\n\nAlternatively, load the packages individually: `library(ggplot2)` or `library(dplyr)`.\n\nThe other libraries, such as `library(knitr)`, `library(tinytable)`, and `library(modelsummary)`, are useful for creating tables and displaying regression results in a clearer and more polished format.\n\n\n## Data Description\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(wooldridge)\n```\n:::\n\n\nConsider the **wage1** dataset in `library(wooldridge)`, drawn from the 1976 Current Population Survey, and inspect its structure using `head(wage1)`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"wage1\", package = \"wooldridge\")\nhead(wage1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  wage educ exper tenure nonwhite female married numdep smsa northcen south\n1 3.10   11     2      0        0      1       0      2    1        0     0\n2 3.24   12    22      2        0      1       1      3    1        0     0\n3 3.00   11     2      0        0      0       0      2    0        0     0\n4 6.00    8    44     28        0      0       1      0    1        0     0\n5 5.30   12     7      2        0      0       1      1    0        0     0\n6 8.75   16     9      8        0      0       1      0    1        0     0\n  west construc ndurman trcommpu trade services profserv profocc clerocc\n1    1        0       0        0     0        0        0       0       0\n2    1        0       0        0     0        1        0       0       0\n3    1        0       0        0     1        0        0       0       0\n4    1        0       0        0     0        0        0       0       1\n5    1        0       0        0     0        0        0       0       0\n6    1        0       0        0     0        0        1       1       0\n  servocc    lwage expersq tenursq\n1       0 1.131402       4       0\n2       1 1.175573     484       4\n3       0 1.098612       4       0\n4       0 1.791759    1936     784\n5       0 1.667707      49       4\n6       0 2.169054      81      64\n```\n\n\n:::\n:::\n\n\nWe focus on the following variables:\n\n-   $wage$: average hourly earnings in 1976 dollars\n-   $educ$: years of education\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Descriptive statistics\nstat <- wage1 %>%\n       summarise(\n       wage_mean = mean(wage, na.rm = TRUE),\n       wage_median = median(wage, na.rm = TRUE),\n       wage_sd = sd(wage, na.rm = TRUE),\n       education_years_mean = mean(educ, na.rm = TRUE),\n       education_years_median = median(educ, na.rm = TRUE)\n  )\n# Display results\ntt(stat, width = 1, digits = 2, caption = \"Descriptive statistics\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_0e1qhkyl5qy598a3kiq5 = TinyTable.createTableFunctions(\"tinytable_0e1qhkyl5qy598a3kiq5\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '1', j: 1 }, { i: '1', j: 2 }, { i: '1', j: 3 }, { i: '1', j: 4 }, { i: '1', j: 5 } ], css_id: 'tinytable_css_5m8boj6sj27ggm8igj26',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 } ], css_id: 'tinytable_css_t3a37w8tdta5m10fw52p',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_0e1qhkyl5qy598a3kiq5.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_0e1qhkyl5qy598a3kiq5 td.tinytable_css_5m8boj6sj27ggm8igj26, #tinytable_0e1qhkyl5qy598a3kiq5 th.tinytable_css_5m8boj6sj27ggm8igj26 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_0e1qhkyl5qy598a3kiq5 td.tinytable_css_t3a37w8tdta5m10fw52p, #tinytable_0e1qhkyl5qy598a3kiq5 th.tinytable_css_t3a37w8tdta5m10fw52p {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_0e1qhkyl5qy598a3kiq5\" style=\"table-layout: fixed; width: 100% !important; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <caption>Descriptive statistics</caption>\n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">wage_mean</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">wage_median</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">wage_sd</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">education_years_mean</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">education_years_median</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">5.9</td>\n                  <td data-row=\"1\" data-col=\"2\">4.7</td>\n                  <td data-row=\"1\" data-col=\"3\">3.7</td>\n                  <td data-row=\"1\" data-col=\"4\">13</td>\n                  <td data-row=\"1\" data-col=\"5\">12</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n-   `summarise` summarizes the data.\n\n-   `%>%`, or `|>` starting from R 4.1.0, is the pipe operator used to chain multiple operations.\n\n-   `tt()` is a function from the `tinytable` package used to display tables in a clearer and more polished format.\n\nAnother useful library for data management is `library(data.table)`, while `library(kableExtra)` is useful for formatting tables.\n\n---\n\n`ggplot2` is based on the \"Grammar of Graphics\" (gg = _grammar of graphics_). It generates graphs through a layered approach using the `+` symbol and is much more flexible and customizable for complex graphs than base R graphics.\n\nIf you have not loaded `library(tidyverse)`, then you must use `library(ggplot2)`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Histogram with ggplot\nggplot(wage1, aes(x = wage)) +\ngeom_histogram(fill = \"lightblue\", color = \"black\", bins = 15) +\nlabs(title = \"Distribution of wage\",\nx = \"Wage\",\ny = \"Frequency\") +\ntheme_minimal()\n```\n\n::: {.cell-output-display}\n![](tutorial1_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Histogram with ggplot2\nggplot(wage1, aes(x = educ)) +\ngeom_histogram(fill = \"lightblue\", color = \"black\", bins = 15) +\nlabs(title = \"Distribution of education\",\nx = \"Years of education\",\ny = \"Frequency\") +\ntheme_minimal()\n```\n\n::: {.cell-output-display}\n![](tutorial1_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nThe histogram shows a high concentration around 12 years of education, which corresponds to a high school diploma in the United States.\n\n### Relationship between hourly wage and years of education:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(wage1, aes(y = wage, x = educ)) + \n  geom_point(color = \"black\") + \n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](tutorial1_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nWith the regression line:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Second plot\nggplot(wage1, aes(y = wage, x = educ)) + \n  geom_point(color = \"black\") + \n  geom_smooth(method = \"lm\", color = \"skyblue\", se = FALSE) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](tutorial1_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n`lm` stands for linear model.\n\n## Simple Linear Regression\n\nEstimate the following regression:\n\n$$\nwage_i = \\beta_0 + \\beta_1 educ_i + u_i\n$$\n\n$wage$ is measured in dollars per hour, and $educ$ is measured in years of education.\n\n<br>\n\n`library(fixest)` is a very versatile library, especially for panel data, and it makes it easy to correct standard errors using `vcov = \"hetero\"` or `vcov = \"hc1\"`.\n\n\n\nIn other courses, you may have seen regressions estimated with `lm(y~x)`. In that case, the regression output reports homoskedastic standard errors, which can be corrected using `library(sandwich)` with the function `vcovHC()`.\n\nFor the rest of the course, we will use `library(fixest)` to estimate regressions and correct standard errors for heteroskedasticity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Baseline regression model\nlibrary(fixest)\nreg1 <- feols(wage ~ educ, data = wage1, vcov = \"hetero\")\nreg1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS estimation, Dep. Var.: wage\nObservations: 526\nStandard-errors: Heteroskedasticity-robust \n             Estimate Std. Error  t value  Pr(>|t|)    \n(Intercept) -0.904852   0.725479 -1.24725   0.21286    \neduc         0.541359   0.061260  8.83713 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 3.37196   Adj. R2: 0.163164\n```\n\n\n:::\n:::\n\n\n- `feols()` estimates the linear regression.\n\n- $wage$ is the dependent variable.\n\n- $educ$ is the independent variable, or regressor.\n\n- `vcov = \"hetero\"` selects heteroskedasticity-robust standard errors.\n\nIf `vcov = \"hetero\"` is not selected, the standard errors are homoskedastic:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg1_ho <- feols(wage ~ educ, data = wage1)\nreg1_ho\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS estimation, Dep. Var.: wage\nObservations: 526\nStandard-errors: IID \n             Estimate Std. Error  t value  Pr(>|t|)    \n(Intercept) -0.904852   0.684968 -1.32101   0.18707    \neduc         0.541359   0.053248 10.16675 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 3.37196   Adj. R2: 0.163164\n```\n\n\n:::\n:::\n\n\n`feols(y ~ x)` is equivalent to `lm(y ~ x)`.\n\nThe regression output reports *IID* standard errors, meaning independent and identically distributed standard errors, which are homoskedastic.\n\n### Heteroskedasticity\n\nThe first assumption needed for unbiased estimation is $E(u_i|educ_i)=0$.\n\n::: {.callout-tip}\n\n## Question\nWhat are the other OLS assumptions for causal inference?\n:::\n\n\n\nIn the population, this implies that $E(wage_i|educ_i)= \\beta_0 + \\beta_1 educ_i$.\n\n\nAssuming homoskedasticity, that is, $Var(u_i|educ_i)= \\sigma^2$, is equivalent in the population to assuming $Var(wage_i|educ_i) = \\sigma^2$.\n\n\nWhile the expected value of $wage$ may increase as years of education increase, which is what we are interested in, under homoskedasticity the variance of $wage$ does not change as $educ$ changes. That is, we are assuming that the variance of wage conditional on education is constant.\n\n\nThis is not realistic. Individuals with more education have a wider range of job opportunities and interests, which leads to greater variability in $wage$ at higher levels of education. Individuals with low levels of education have fewer opportunities and often earn wages close to the minimum wage. This tends to reduce the variability of $wage$ at lower levels of education.\n\n\nWhen $Var(u_i|x_i)$ depends on $x_i$, the error term exhibits heteroskedasticity, or nonconstant variance. Since $Var(u_i|x)=Var(y|x)$, heteroskedasticity is present whenever $Var(y_i|x_i)$ is a function of $x_i$.\n\n\n::: {.callout-caution collapse=\"false\"}\n## Implications of heteroskedasticity\n\nThe OLS assumptions do not impose restrictions on the conditional variance. Therefore, OLS estimators remain unbiased, consistent, and asymptotically normal even in the presence of heteroskedasticity.\n\nHypothesis tests and confidence intervals based on heteroskedasticity-robust standard errors are valid regardless of the structure of the error variance, allowing valid statistical inference even in the presence of heteroskedasticity. These formulas were proposed by Eicker (1967), Huber (1967), and White (1980), and are commonly known as Eicker-Huber-White standard errors, sometimes simply White standard errors, or robust standard errors.\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Select specific values of educ\neduc_valori <- c(4, 8, 12, 16)\n\n# Compute the variance of wage for those specific values of educ\nvarianza_valori <- wage1 %>%\n  filter(educ %in% educ_valori) %>%\n  group_by(educ) %>%\n  summarise(varianza = var(wage, na.rm = TRUE)) %>%\n  ungroup()\n\n# Plot\nggplot(varianza_valori, aes(x = educ, y = varianza)) +\n  geom_point(size = 3, color = \"darkblue\") +\n  labs(title = \"Variance of wage for specific education values\",\n       x = \"Years of education\",\n       y = \"Variance of wage\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](tutorial1_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n-   `group_by` groups the data by categories.\n  \nNow group the observations into 10 education-level groups:\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Group educ into intervals\nvarianza_educ <- wage1 %>%\n  mutate(gruppo_educ = cut(educ, breaks = 10)) %>%\n  group_by(gruppo_educ) %>%\n  summarise(\n    varianza = var(wage, na.rm = TRUE),\n    media_educ = mean(educ, na.rm = TRUE)\n  )\n\n# 2. Plot the variance as a function of educ\nggplot(varianza_educ, aes(x = media_educ, y = varianza)) +\n  geom_point(size = 3, color = \"darkblue\") +\n  labs(title = \"Variance of wage by education level\",\n       x = \"Years of education (group mean)\",\n       y = \"Variance of wage\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](tutorial1_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n#### Regression Results\n\n\n::: {.cell tbl-cap='OLS estimation results. Dependent variable $:$ Wage'}\n\n```{.r .cell-code}\nmodelsummary(list(\"Wage\" = reg1, \"Wage\" = reg1_ho), gof_omit = \"AIC|BIC|RMSE|R2 Adj.\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_w6d1t2hm1ay5vy58fvcm = TinyTable.createTableFunctions(\"tinytable_w6d1t2hm1ay5vy58fvcm\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '6', j: 2 }, { i: '6', j: 3 } ], css_id: 'tinytable_css_m7978u97q1d4du67p5dx',}, \n          { positions: [ { i: '4', j: 2 }, { i: '4', j: 3 } ], css_id: 'tinytable_css_ujelhqs12ic09aayqo0s',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '5', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '5', j: 3 } ], css_id: 'tinytable_css_bunh6mfgbufo4ecw84zr',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_gp7ihkob4im4cj9gek97',}, \n          { positions: [ { i: '6', j: 1 } ], css_id: 'tinytable_css_bgdkq31myy2ytydbhgsn',}, \n          { positions: [ { i: '4', j: 1 } ], css_id: 'tinytable_css_c6x6hffj3cr8sa3t31jw',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '5', j: 1 } ], css_id: 'tinytable_css_qfu15kqxk5f50s9dus4c',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_qjz9m5kw4vh8vzj4ecej',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_w6d1t2hm1ay5vy58fvcm.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_w6d1t2hm1ay5vy58fvcm td.tinytable_css_m7978u97q1d4du67p5dx, #tinytable_w6d1t2hm1ay5vy58fvcm th.tinytable_css_m7978u97q1d4du67p5dx {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_w6d1t2hm1ay5vy58fvcm td.tinytable_css_ujelhqs12ic09aayqo0s, #tinytable_w6d1t2hm1ay5vy58fvcm th.tinytable_css_ujelhqs12ic09aayqo0s {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_w6d1t2hm1ay5vy58fvcm td.tinytable_css_bunh6mfgbufo4ecw84zr, #tinytable_w6d1t2hm1ay5vy58fvcm th.tinytable_css_bunh6mfgbufo4ecw84zr { text-align: center }\n    #tinytable_w6d1t2hm1ay5vy58fvcm td.tinytable_css_gp7ihkob4im4cj9gek97, #tinytable_w6d1t2hm1ay5vy58fvcm th.tinytable_css_gp7ihkob4im4cj9gek97 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_w6d1t2hm1ay5vy58fvcm td.tinytable_css_bgdkq31myy2ytydbhgsn, #tinytable_w6d1t2hm1ay5vy58fvcm th.tinytable_css_bgdkq31myy2ytydbhgsn {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_w6d1t2hm1ay5vy58fvcm td.tinytable_css_c6x6hffj3cr8sa3t31jw, #tinytable_w6d1t2hm1ay5vy58fvcm th.tinytable_css_c6x6hffj3cr8sa3t31jw {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_w6d1t2hm1ay5vy58fvcm td.tinytable_css_qfu15kqxk5f50s9dus4c, #tinytable_w6d1t2hm1ay5vy58fvcm th.tinytable_css_qfu15kqxk5f50s9dus4c { text-align: left }\n    #tinytable_w6d1t2hm1ay5vy58fvcm td.tinytable_css_qjz9m5kw4vh8vzj4ecej, #tinytable_w6d1t2hm1ay5vy58fvcm th.tinytable_css_qjz9m5kw4vh8vzj4ecej {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_w6d1t2hm1ay5vy58fvcm\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Wage</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Wage </th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">-0.905</td>\n                  <td data-row=\"1\" data-col=\"3\">-0.905</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.725)</td>\n                  <td data-row=\"2\" data-col=\"3\">(0.685)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">educ</td>\n                  <td data-row=\"3\" data-col=\"2\">0.541</td>\n                  <td data-row=\"3\" data-col=\"3\">0.541</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.061)</td>\n                  <td data-row=\"4\" data-col=\"3\">(0.053)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"5\" data-col=\"2\">526</td>\n                  <td data-row=\"5\" data-col=\"3\">526</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">R2</td>\n                  <td data-row=\"6\" data-col=\"2\">0.165</td>\n                  <td data-row=\"6\" data-col=\"3\">0.165</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nThe intercept is -0.90. It represents the estimated average hourly wage, in dollars, for a person with zero years of education. This interpretation has little substantive meaning. It is the expected value when $educ=0$, that is, for a person with no formal education, which may be a rare or unrepresentative case in the population.\n\n\nThe coefficient on educ, $\\beta_1$, represents the average increase in hourly wage **associated** with an additional year of education.\n\nIf $E(u_i|educ_i)=0$, then $\\beta_1 = 0.54$ has a causal interpretation: an additional year of education increases the hourly wage by 0.54 dollars per hour, on average. Otherwise, 0.54 dollars is simply a correlation.\n\n\nIf we wanted to consider 10 additional years of education: 10 x $\\beta_1$ = 10 x 0.54\\$ = 5.4 dollars per hour.\n\nSome variables affect both wage ($wage$) and years of education ($educ$). When these variables are included in the error term, they create correlation between $u_i$ and $educ_i$, thereby violating the assumption $E(u_i|educ_i)=0$.\n\nWhat variables might affect both $wage$ and $educ$? They may be observable, such as experience, family background, and occupation or industry, or unobservable, such as innate ability and social connections.\n\nThese omitted variables create an endogeneity problem that makes it difficult to interpret $\\beta_1$ as the causal effect of education on wage, because the observed correlation may be partly due to these confounding factors.\n\n\n$R^2$ indicates that approximately 16.5% of the variability in $wage$ is explained by $educ$. This relatively low value suggests **only** that many factors other than education are correlated with wages.\n\n\n::: {.callout-warning collapse=\"false\"}\n## $R^2$\n\nThe regression $R^2$ is the fraction of the sample variance of $Y_i$ explained by the regressors.\n\nRemember that:\n\n- A high $R^2$ does not imply that the regressors are the true cause of the dependent variable.\n- A high $R^2$ does not imply the absence of omitted-variable bias.\n- A high $R^2$ does not mean that we have chosen the most appropriate regressors.\n- A low $R^2$ does not imply that we have chosen inappropriate regressors.\n\n:::\n\n\n\n::: {.callout-caution collapse=\"false\"}\n## Asymptotic Theory and Normality of the Errors\n\nNormality of the errors is **not** required for OLS unbiasedness, nor for the property of being the best linear unbiased estimator (BLUE) under the Gauss-Markov assumptions, which require homoskedasticity.\n\nIn some courses, you may have seen tests of the \"normality\" of the residuals presented as a _necessary_ condition for valid inference, or as a way to \"validate the model.\" In reality, the assumption concerns the population errors, which we do not observe. Therefore, tests for error normality, such as the Jarque-Bera test, are based on the OLS residuals. In practice, this test is rarely used. Thanks to the central limit theorem, when the sample is sufficiently large, the asymptotic distribution of the OLS estimators is normal even if the population errors are not normally distributed.\n\n:::\n\n\n\n\n## Changing Units of Measurement\n\nRegression coefficients are expressed in the units of measurement of the data. The value of the coefficients changes if we change the unit of measurement, while the fit of the model to the data does not change. Let us see how the coefficients change when we change the units of measurement of $wage$ and $educ$.\n\n### Dependent Variable: wage\n\n**Hourly wage in hundreds of dollars:** $wage$ is expressed in dollars. We can express it in hundreds of dollars:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwage1 <- wage1 %>%\n  mutate(wage_100 = wage/100)\n```\n:::\n\n\n-   `mutate` creates or modifies variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg2 <- feols(wage_100 ~ educ, data = wage1, vcov = \"hetero\")\nmodelsummary(list(\"Wage\" = reg1, \"Wage in hundreds of $\" = reg2), gof_omit = \"AIC|BIC|RMSE|R2 Adj.\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_d80v13jtymobzb98oknv = TinyTable.createTableFunctions(\"tinytable_d80v13jtymobzb98oknv\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '6', j: 2 }, { i: '6', j: 3 } ], css_id: 'tinytable_css_4dhpvlb2cnz8p3d2w42f',}, \n          { positions: [ { i: '4', j: 2 }, { i: '4', j: 3 } ], css_id: 'tinytable_css_vy3in1g2dhcb44lbm2cf',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '5', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '5', j: 3 } ], css_id: 'tinytable_css_kr7r04uhkana8j8lg71p',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_dfebuy00izfcy3v9o3hr',}, \n          { positions: [ { i: '6', j: 1 } ], css_id: 'tinytable_css_nz1zw61cec1p0lqameah',}, \n          { positions: [ { i: '4', j: 1 } ], css_id: 'tinytable_css_t54xrsin5dvm8pzjw9by',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '5', j: 1 } ], css_id: 'tinytable_css_e50zny7wjjo1l1yqp0go',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_iwffp3uo92zhp7pbu930',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_d80v13jtymobzb98oknv.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_d80v13jtymobzb98oknv td.tinytable_css_4dhpvlb2cnz8p3d2w42f, #tinytable_d80v13jtymobzb98oknv th.tinytable_css_4dhpvlb2cnz8p3d2w42f {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_d80v13jtymobzb98oknv td.tinytable_css_vy3in1g2dhcb44lbm2cf, #tinytable_d80v13jtymobzb98oknv th.tinytable_css_vy3in1g2dhcb44lbm2cf {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_d80v13jtymobzb98oknv td.tinytable_css_kr7r04uhkana8j8lg71p, #tinytable_d80v13jtymobzb98oknv th.tinytable_css_kr7r04uhkana8j8lg71p { text-align: center }\n    #tinytable_d80v13jtymobzb98oknv td.tinytable_css_dfebuy00izfcy3v9o3hr, #tinytable_d80v13jtymobzb98oknv th.tinytable_css_dfebuy00izfcy3v9o3hr {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_d80v13jtymobzb98oknv td.tinytable_css_nz1zw61cec1p0lqameah, #tinytable_d80v13jtymobzb98oknv th.tinytable_css_nz1zw61cec1p0lqameah {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_d80v13jtymobzb98oknv td.tinytable_css_t54xrsin5dvm8pzjw9by, #tinytable_d80v13jtymobzb98oknv th.tinytable_css_t54xrsin5dvm8pzjw9by {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_d80v13jtymobzb98oknv td.tinytable_css_e50zny7wjjo1l1yqp0go, #tinytable_d80v13jtymobzb98oknv th.tinytable_css_e50zny7wjjo1l1yqp0go { text-align: left }\n    #tinytable_d80v13jtymobzb98oknv td.tinytable_css_iwffp3uo92zhp7pbu930, #tinytable_d80v13jtymobzb98oknv th.tinytable_css_iwffp3uo92zhp7pbu930 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_d80v13jtymobzb98oknv\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Wage</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Wage in hundreds of $</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">-0.905</td>\n                  <td data-row=\"1\" data-col=\"3\">-0.009</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.725)</td>\n                  <td data-row=\"2\" data-col=\"3\">(0.007)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">educ</td>\n                  <td data-row=\"3\" data-col=\"2\">0.541</td>\n                  <td data-row=\"3\" data-col=\"3\">0.005</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.061)</td>\n                  <td data-row=\"4\" data-col=\"3\">(0.001)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"5\" data-col=\"2\">526</td>\n                  <td data-row=\"5\" data-col=\"3\">526</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">R2</td>\n                  <td data-row=\"6\" data-col=\"2\">0.165</td>\n                  <td data-row=\"6\" data-col=\"3\">0.165</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nOn average, an additional year of education is associated with an increase in the hourly wage of 0.005 hundreds of dollars. This is 0.005 $\\times$ 100 $\\approx$ 0.5 dollars, or 0.541 without rounding.\n\n\n---\n\n**Monthly wage:** Suppose workers are full-time employees who work 7 hours per day, 5 days per week, and 4 weeks per month. That is, 7 $\\times$ 5 $\\times$ 4 = 140.\n\nCreate a new variable, wage_monthly = $wage$ $\\times$ 140.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwage1 <- wage1 %>%\n  mutate(wage_monthly = wage*140)\n```\n:::\n\n\nNew regression:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg3 <- feols(wage_monthly ~ educ, data = wage1, vcov = \"hetero\")\nreg3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS estimation, Dep. Var.: wage_monthly\nObservations: 526\nStandard-errors: Heteroskedasticity-robust \n             Estimate Std. Error  t value  Pr(>|t|)    \n(Intercept) -126.6792  101.56713 -1.24725   0.21286    \neduc          75.7903    8.57635  8.83713 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 472.1   Adj. R2: 0.163164\n```\n\n\n:::\n:::\n\n\nCompare the two regressions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(\n  list(\"Hourly Wage\" = reg1, \"Monthly Wage\" = reg3), gof_omit = \"AIC|BIC|RMSE|R2 Adj.\"\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_ic0cz6f49jfcwr18oor8 = TinyTable.createTableFunctions(\"tinytable_ic0cz6f49jfcwr18oor8\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '6', j: 2 }, { i: '6', j: 3 } ], css_id: 'tinytable_css_70ly35iqia28j24cm6ow',}, \n          { positions: [ { i: '4', j: 2 }, { i: '4', j: 3 } ], css_id: 'tinytable_css_mt4iat481z0upqqgnxft',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '5', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '5', j: 3 } ], css_id: 'tinytable_css_bj5sja3k1xanj0rrzbnx',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_ru80v0ekrjjod6dzfubj',}, \n          { positions: [ { i: '6', j: 1 } ], css_id: 'tinytable_css_sfj4v52fsm95xz1x1wqr',}, \n          { positions: [ { i: '4', j: 1 } ], css_id: 'tinytable_css_r622ar7akiw76iznwlqa',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '5', j: 1 } ], css_id: 'tinytable_css_xlqpyapi3mo7mod8pr3p',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_z9awqou87gq98w3inwn7',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_ic0cz6f49jfcwr18oor8.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_ic0cz6f49jfcwr18oor8 td.tinytable_css_70ly35iqia28j24cm6ow, #tinytable_ic0cz6f49jfcwr18oor8 th.tinytable_css_70ly35iqia28j24cm6ow {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_ic0cz6f49jfcwr18oor8 td.tinytable_css_mt4iat481z0upqqgnxft, #tinytable_ic0cz6f49jfcwr18oor8 th.tinytable_css_mt4iat481z0upqqgnxft {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_ic0cz6f49jfcwr18oor8 td.tinytable_css_bj5sja3k1xanj0rrzbnx, #tinytable_ic0cz6f49jfcwr18oor8 th.tinytable_css_bj5sja3k1xanj0rrzbnx { text-align: center }\n    #tinytable_ic0cz6f49jfcwr18oor8 td.tinytable_css_ru80v0ekrjjod6dzfubj, #tinytable_ic0cz6f49jfcwr18oor8 th.tinytable_css_ru80v0ekrjjod6dzfubj {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_ic0cz6f49jfcwr18oor8 td.tinytable_css_sfj4v52fsm95xz1x1wqr, #tinytable_ic0cz6f49jfcwr18oor8 th.tinytable_css_sfj4v52fsm95xz1x1wqr {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_ic0cz6f49jfcwr18oor8 td.tinytable_css_r622ar7akiw76iznwlqa, #tinytable_ic0cz6f49jfcwr18oor8 th.tinytable_css_r622ar7akiw76iznwlqa {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_ic0cz6f49jfcwr18oor8 td.tinytable_css_xlqpyapi3mo7mod8pr3p, #tinytable_ic0cz6f49jfcwr18oor8 th.tinytable_css_xlqpyapi3mo7mod8pr3p { text-align: left }\n    #tinytable_ic0cz6f49jfcwr18oor8 td.tinytable_css_z9awqou87gq98w3inwn7, #tinytable_ic0cz6f49jfcwr18oor8 th.tinytable_css_z9awqou87gq98w3inwn7 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_ic0cz6f49jfcwr18oor8\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Hourly Wage</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Monthly Wage</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">-0.905</td>\n                  <td data-row=\"1\" data-col=\"3\">-126.679</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.725)</td>\n                  <td data-row=\"2\" data-col=\"3\">(101.567)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">educ</td>\n                  <td data-row=\"3\" data-col=\"2\">0.541</td>\n                  <td data-row=\"3\" data-col=\"3\">75.790</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.061)</td>\n                  <td data-row=\"4\" data-col=\"3\">(8.576)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"5\" data-col=\"2\">526</td>\n                  <td data-row=\"5\" data-col=\"3\">526</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">R2</td>\n                  <td data-row=\"6\" data-col=\"2\">0.165</td>\n                  <td data-row=\"6\" data-col=\"3\">0.165</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nThe coefficients of the second model equal those of the first model $\\times$ 140. The same applies to the standard errors.\n\nOn average, an additional year of education is **associated** with an increase in the monthly wage of 75.79 dollars.\n\n75.79 dollars = 0.541 $\\times$ 140.\n\n### Independent Variable: educ\n\nSuppose $educ$ is measured in months of education. That is, $educ$ $\\times$ 12:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwage1 <- wage1 %>%\n  mutate(educ_mesi = educ*12)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg4 <- feols(wage ~ educ_mesi, data = wage1, vcov = \"hetero\")\nmodelsummary(list(\"Wage\" = reg1, \"Wage\" = reg4), gof_omit = \"AIC|BIC|RMSE|R2 Adj.\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_b5fjelay7bop1z5nkgkk = TinyTable.createTableFunctions(\"tinytable_b5fjelay7bop1z5nkgkk\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '8', j: 2 }, { i: '8', j: 3 } ], css_id: 'tinytable_css_z34zloovyhc4o4p8c4xn',}, \n          { positions: [ { i: '6', j: 2 }, { i: '6', j: 3 } ], css_id: 'tinytable_css_p7yg2crx2ulz3bam4d3u',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '7', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '7', j: 3 } ], css_id: 'tinytable_css_ws4d55jo63pu37uy98zq',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_blemg58lbyupg1izgkqb',}, \n          { positions: [ { i: '8', j: 1 } ], css_id: 'tinytable_css_puhcna11z4l7mrnte9gd',}, \n          { positions: [ { i: '6', j: 1 } ], css_id: 'tinytable_css_zziod1tofj0ztc27wpz2',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '7', j: 1 } ], css_id: 'tinytable_css_4jwiqzfrc9f54pbuqv9u',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_hjuugsz5m8h9gmnknaam',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_b5fjelay7bop1z5nkgkk.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_b5fjelay7bop1z5nkgkk td.tinytable_css_z34zloovyhc4o4p8c4xn, #tinytable_b5fjelay7bop1z5nkgkk th.tinytable_css_z34zloovyhc4o4p8c4xn {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_b5fjelay7bop1z5nkgkk td.tinytable_css_p7yg2crx2ulz3bam4d3u, #tinytable_b5fjelay7bop1z5nkgkk th.tinytable_css_p7yg2crx2ulz3bam4d3u {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_b5fjelay7bop1z5nkgkk td.tinytable_css_ws4d55jo63pu37uy98zq, #tinytable_b5fjelay7bop1z5nkgkk th.tinytable_css_ws4d55jo63pu37uy98zq { text-align: center }\n    #tinytable_b5fjelay7bop1z5nkgkk td.tinytable_css_blemg58lbyupg1izgkqb, #tinytable_b5fjelay7bop1z5nkgkk th.tinytable_css_blemg58lbyupg1izgkqb {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_b5fjelay7bop1z5nkgkk td.tinytable_css_puhcna11z4l7mrnte9gd, #tinytable_b5fjelay7bop1z5nkgkk th.tinytable_css_puhcna11z4l7mrnte9gd {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_b5fjelay7bop1z5nkgkk td.tinytable_css_zziod1tofj0ztc27wpz2, #tinytable_b5fjelay7bop1z5nkgkk th.tinytable_css_zziod1tofj0ztc27wpz2 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_b5fjelay7bop1z5nkgkk td.tinytable_css_4jwiqzfrc9f54pbuqv9u, #tinytable_b5fjelay7bop1z5nkgkk th.tinytable_css_4jwiqzfrc9f54pbuqv9u { text-align: left }\n    #tinytable_b5fjelay7bop1z5nkgkk td.tinytable_css_hjuugsz5m8h9gmnknaam, #tinytable_b5fjelay7bop1z5nkgkk th.tinytable_css_hjuugsz5m8h9gmnknaam {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_b5fjelay7bop1z5nkgkk\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Wage</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Wage </th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">-0.905</td>\n                  <td data-row=\"1\" data-col=\"3\">-0.905</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.725)</td>\n                  <td data-row=\"2\" data-col=\"3\">(0.725)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">educ</td>\n                  <td data-row=\"3\" data-col=\"2\">0.541</td>\n                  <td data-row=\"3\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.061)</td>\n                  <td data-row=\"4\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">educ_mesi</td>\n                  <td data-row=\"5\" data-col=\"2\"></td>\n                  <td data-row=\"5\" data-col=\"3\">0.045</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\"></td>\n                  <td data-row=\"6\" data-col=\"3\">(0.005)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"7\" data-col=\"2\">526</td>\n                  <td data-row=\"7\" data-col=\"3\">526</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\">R2</td>\n                  <td data-row=\"8\" data-col=\"2\">0.165</td>\n                  <td data-row=\"8\" data-col=\"3\">0.165</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nIn this case, the intercept **does not** change. The intercept is -0.90 and represents the estimated average hourly wage, in dollars, for a person with zero months of education.\n\nOn average, an additional month of education is **associated** with an increase in the hourly wage of 0.045 dollars, where $0.045 = \\frac{0.541}{12}$.\n\n\n::: {.callout-important title=\"Goodness of Fit and Units of Measurement\"}\n\nChanging the unit of measurement, whether for the dependent variable or the independent variable, does not change the goodness of fit of the model to the data. The $R^2$ remains unchanged, as does the statistical significance of the coefficients, because the ratio between the coefficient and the standard error remains the same.\n\n**Warning (1)** This will change when we consider models with the dependent variable in logarithmic form. In that case, as we will see, if we compare two models, one where the dependent variable is $wage$ and one where it is $log(wage)$, we are comparing two different models (lin-lin versus log-lin).\n\n**Warning (2)** Pay attention to changes in units of measurement when the dependent variable is expressed in logarithmic form, as we will see later.\n\n:::\n\n\n\n\n## Confidence Intervals and Hypothesis Tests\n\nConsider the first regression:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(list(\"Hourly Wage\" = reg1), gof_omit = \"AIC|BIC|RMSE|R2 Adj.\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_td9f93tu3me7lydqnypy = TinyTable.createTableFunctions(\"tinytable_td9f93tu3me7lydqnypy\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '6', j: 2 } ], css_id: 'tinytable_css_mzcdjywfs96ybrui2pmv',}, \n          { positions: [ { i: '4', j: 2 } ], css_id: 'tinytable_css_3cpuawa460573sqhix1i',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '5', j: 2 } ], css_id: 'tinytable_css_tklibx0iquqi2kvhn44p',}, \n          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_sastz88frzmib34sodqs',}, \n          { positions: [ { i: '6', j: 1 } ], css_id: 'tinytable_css_jxrqfu6uhvxb08vycx4k',}, \n          { positions: [ { i: '4', j: 1 } ], css_id: 'tinytable_css_jlg7fpa0jenh5c0ia245',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '5', j: 1 } ], css_id: 'tinytable_css_jfzvkzjs1s56hns7ccb4',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_ofl0dpncilmdfg3ctk50',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_td9f93tu3me7lydqnypy.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_td9f93tu3me7lydqnypy td.tinytable_css_mzcdjywfs96ybrui2pmv, #tinytable_td9f93tu3me7lydqnypy th.tinytable_css_mzcdjywfs96ybrui2pmv {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_td9f93tu3me7lydqnypy td.tinytable_css_3cpuawa460573sqhix1i, #tinytable_td9f93tu3me7lydqnypy th.tinytable_css_3cpuawa460573sqhix1i {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_td9f93tu3me7lydqnypy td.tinytable_css_tklibx0iquqi2kvhn44p, #tinytable_td9f93tu3me7lydqnypy th.tinytable_css_tklibx0iquqi2kvhn44p { text-align: center }\n    #tinytable_td9f93tu3me7lydqnypy td.tinytable_css_sastz88frzmib34sodqs, #tinytable_td9f93tu3me7lydqnypy th.tinytable_css_sastz88frzmib34sodqs {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_td9f93tu3me7lydqnypy td.tinytable_css_jxrqfu6uhvxb08vycx4k, #tinytable_td9f93tu3me7lydqnypy th.tinytable_css_jxrqfu6uhvxb08vycx4k {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_td9f93tu3me7lydqnypy td.tinytable_css_jlg7fpa0jenh5c0ia245, #tinytable_td9f93tu3me7lydqnypy th.tinytable_css_jlg7fpa0jenh5c0ia245 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_td9f93tu3me7lydqnypy td.tinytable_css_jfzvkzjs1s56hns7ccb4, #tinytable_td9f93tu3me7lydqnypy th.tinytable_css_jfzvkzjs1s56hns7ccb4 { text-align: left }\n    #tinytable_td9f93tu3me7lydqnypy td.tinytable_css_ofl0dpncilmdfg3ctk50, #tinytable_td9f93tu3me7lydqnypy th.tinytable_css_ofl0dpncilmdfg3ctk50 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_td9f93tu3me7lydqnypy\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Hourly Wage</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">-0.905</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.725)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">educ</td>\n                  <td data-row=\"3\" data-col=\"2\">0.541</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.061)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"5\" data-col=\"2\">526</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">R2</td>\n                  <td data-row=\"6\" data-col=\"2\">0.165</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nThe 95% confidence interval for $\\beta_1$ is computed as:\n\n$$\n\\beta_1 \\pm z_{1-\\alpha/2} \\times SE(\\beta_1)\n$$ {#eq-ci}\n\nwhere $z_{1-\\alpha/2}$ is the critical value of the standard normal distribution. For $\\alpha = 0.05$, we have $z_{0.975} = 1.96$.\n\nSubstituting the values of the coefficient and the standard error:\n$$\n\\beta_1 \\pm 1.96 \\times SE(\\beta_1) \\implies 0.541 \\pm 1.96 \\times 0.061 \\implies\n0.541 \\pm 0.119\n$$\n\nWith 95% confidence, we can state that the true value of the coefficient $\\beta_1$ lies between 0.422 and 0.66 dollars.\n\nUsing `feols()` and `confint`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(reg1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %    97.5 %\n(Intercept) -2.3300571 0.5203539\neduc         0.4210146 0.6617039\n```\n\n\n:::\n:::\n\n\n\nNull and alternative hypotheses:\n\n$$\n  H_0: \\beta_1 = 0 \\quad \\text{(no association between wage and educ)}\n$$\n\n$$\n  H_1: \\beta_1 \\neq 0 \\quad \\text{(there is an association between wage and educ)}\n$$\n\nTo construct the test, begin by computing the $z$ statistic:\n\n$$\n   z = \\frac{\\beta_1}{SE(\\beta_1)} = \\frac{0.541}{0.061} = 8.87\n$$ \n\nThen compare the critical value $z_{0.975} = 1.96$ with the absolute value of $z$. We can reject the null hypothesis if $|z|$ is greater than 1.96. Conversely, if $|z|$ is less than 1.96, we cannot reject the null hypothesis.\n\nIn our case:\n$$\n  |z| = 8.87 > 1.96\n$$ \n\ntherefore, we reject the null hypothesis $H_0$ at the 5% significance level. Consequently, we can state that the coefficient $\\beta_1$ is *statistically significant* at the 5% level, meaning that we have statistical evidence to conclude that there is an association between $educ$ and $wage$.\n\n\nThe confidence interval for 2 additional years of education would be:\n\n$$\n2 \\times 0.541 \\pm 1.96 \\times 2 \\times 0.061 \\implies\n1.082 \\pm 0.238\n$$\n\n\nThis is equivalent to multiplying the endpoints of the confidence interval for one year of education by 2.\n\n---\n\n## Confidence Intervals and Changes in Units of Measurement\n\nWe have just seen that:\n\n$$\n\\beta_1 \\pm 1.96 \\times SE(\\beta_1) \\implies 0.541 \\pm 1.96 \\times 0.061 \\implies\n0.541 \\pm 0.119\n$$\n\nIf $wage$ were expressed in hundreds of dollars, the confidence interval for $\\beta_1$ would be:\n\n$$\n\\frac{0.541}{100} \\pm 1.96 \\times \\frac{0.061}{100} \\implies 0,00541 \\pm 1.96 \\times 0.00061 \\implies 0.00541 \\pm 0.00119\n$$\n\nThis is equivalent to dividing by 100 the endpoints of the confidence interval expressed in dollars.\n\n---\n\n## Dummy Variables\n\n*Dummy variables* are a necessary tool for incorporating categorical information into regression models.\n\nConsider a categorical variable, `female`, which indicates the worker's gender. The variable can take only two values, `Female` and `Male`. The dummy variable is equal to:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabledummy <- table(wage1$female)\nnames(tabledummy) <- c(\"Male\", \"Female\")\n\nas.data.frame(tabledummy) |>\n  setNames(c(\"Gender\", \"Frequency\")) |>\n  tt(caption = \"Number of Men and Women\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_1dn32y5yi6jp9hmzudtw = TinyTable.createTableFunctions(\"tinytable_1dn32y5yi6jp9hmzudtw\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '2', j: 1 }, { i: '2', j: 2 } ], css_id: 'tinytable_css_luwzl946ocq8xamyredm',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 } ], css_id: 'tinytable_css_zadsge4ga7hkqeek1x0d',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_1dn32y5yi6jp9hmzudtw.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_1dn32y5yi6jp9hmzudtw td.tinytable_css_luwzl946ocq8xamyredm, #tinytable_1dn32y5yi6jp9hmzudtw th.tinytable_css_luwzl946ocq8xamyredm {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_1dn32y5yi6jp9hmzudtw td.tinytable_css_zadsge4ga7hkqeek1x0d, #tinytable_1dn32y5yi6jp9hmzudtw th.tinytable_css_zadsge4ga7hkqeek1x0d {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_1dn32y5yi6jp9hmzudtw\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <caption>Number of Men and Women</caption>\n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Gender</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Frequency</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Male</td>\n                  <td data-row=\"1\" data-col=\"2\">274</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">Female</td>\n                  <td data-row=\"2\" data-col=\"2\">252</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nDescriptive statistics by category:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstat_gender <- wage1 %>% \n  group_by(female) %>%\n        summarize(\n       wage_mean = mean(wage, na.rm = TRUE),\n       wage_median = median(wage, na.rm = TRUE),\n       wage_sd = sd(wage, na.rm = TRUE),\n       education_years_mean = mean(educ, na.rm = TRUE),\n       education_years_median = median(educ, na.rm = TRUE)\n  )\n\nstat_gender |>\n  tt(caption = \"Descriptive statistics\") |>\n  format_tt(digits = 2) |>\n  theme_tt(\"striped\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: The theme_tt() function is deprecated. Please use format-specific or style-specific theme functions instead:\n\nFormat-specific functions:\n\n* theme_html()\n* theme_latex()\n* theme_typst()\n\nStyle-specific functions:\n\n* theme_grid()\n* theme_revealjs()\n* theme_rotate()\n* theme_striped()\n* theme_empty()\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_xcjplxtqqpl5pnjb3h0n = TinyTable.createTableFunctions(\"tinytable_xcjplxtqqpl5pnjb3h0n\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '2', j: 1 }, { i: '2', j: 2 }, { i: '2', j: 3 }, { i: '2', j: 4 }, { i: '2', j: 5 }, { i: '2', j: 6 } ], css_id: 'tinytable_css_ttpekj5vas0b26ukmbdy',}, \n          { positions: [ { i: '1', j: 1 }, { i: '1', j: 2 }, { i: '1', j: 3 }, { i: '1', j: 4 }, { i: '1', j: 5 }, { i: '1', j: 6 } ], css_id: 'tinytable_css_pjulj6mzb8mc8qgcmib5',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 } ], css_id: 'tinytable_css_iyo7k5swg1znf4s0gt24',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_xcjplxtqqpl5pnjb3h0n.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_xcjplxtqqpl5pnjb3h0n td.tinytable_css_ttpekj5vas0b26ukmbdy, #tinytable_xcjplxtqqpl5pnjb3h0n th.tinytable_css_ttpekj5vas0b26ukmbdy {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_xcjplxtqqpl5pnjb3h0n td.tinytable_css_pjulj6mzb8mc8qgcmib5, #tinytable_xcjplxtqqpl5pnjb3h0n th.tinytable_css_pjulj6mzb8mc8qgcmib5 { background-color: #ededed }\n    #tinytable_xcjplxtqqpl5pnjb3h0n td.tinytable_css_iyo7k5swg1znf4s0gt24, #tinytable_xcjplxtqqpl5pnjb3h0n th.tinytable_css_iyo7k5swg1znf4s0gt24 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_xcjplxtqqpl5pnjb3h0n\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <caption>Descriptive statistics</caption>\n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">female</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">wage_mean</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">wage_median</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">wage_sd</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">education_years_mean</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">education_years_median</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">0</td>\n                  <td data-row=\"1\" data-col=\"2\">7.1</td>\n                  <td data-row=\"1\" data-col=\"3\">6</td>\n                  <td data-row=\"1\" data-col=\"4\">4.2</td>\n                  <td data-row=\"1\" data-col=\"5\">13</td>\n                  <td data-row=\"1\" data-col=\"6\">12</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">1</td>\n                  <td data-row=\"2\" data-col=\"2\">4.6</td>\n                  <td data-row=\"2\" data-col=\"3\">3.8</td>\n                  <td data-row=\"2\" data-col=\"4\">2.5</td>\n                  <td data-row=\"2\" data-col=\"5\">12</td>\n                  <td data-row=\"2\" data-col=\"6\">12</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n-   `group_by` groups the data by categories.\n\n\n::: {.callout-note title=\"Remember\"}\nThe mean of a dummy variable is equal to the proportion\nof observations for which $D_i = 1$ in the sample:\n\n$$\\bar{D} = \\frac{1}{n}\\sum_{i=1}^{n} D_i = \\frac{n_1}{n}$$\n\nwhere $n_1$ is the number of observations with $D_i = 1$.\n\nIndeed:\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(wage1$female)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4790875\n```\n\n\n:::\n:::\n\n\nThat is, 252/526 $\\approx$ 0.48.\n:::\n\nWhen we include this dummy variable in a regression model,\n\n$$\nwage_i = \\beta_0 + \\beta_1 female_i + u_i,\n$$\n\nwe must think carefully about the interpretation of $\\beta_0$ and $\\beta_1$.\n\n\n### With Exogeneity: Causal Interpretation\n\n\nIf we assume that $E(u_i|female_i)=0$, we can give the regression coefficients a causal interpretation. In this case, $\\beta_0$ represents the expected wage when $female_i=0$, that is, for male workers:\n\n$$\n  E(wage_i|female_i=0)=\\beta_0.\n$$ \n\nSimilarly, for female workers ($female_i=1$), the expected wage is:\n\n$$\nE(wage_i|female_i=1)=\\beta_0+\\beta_1.\n$$\n\nConsequently, $\\beta_1$ represents the difference in expected wage between women and men:\n\n$$ \n\\beta_1 = E(wage_i|female_i=1) - E(wage_i|female_i=0).\n$$\n\nThe assumption $E(u_i|female_i)=0$ implies that all variables that determine wages and are included in the error term do not differ systematically between men and women. In other words, we are assuming that the only difference between the groups is gender itself, and therefore the estimate of $\\beta_1$ captures the causal effect of being a woman on earnings.\n\n\nThe assumption $E(u_i|female_i)=0$ is unrealistic.\n\n### Without Exogeneity: Descriptive Interpretation\n\nIf we are not willing to assume that $E(u_i|female_i)=0$, the causal interpretation is no longer valid. In this case, we can interpret $\\beta_1$ simply as the observed difference in average wages, without assigning a causal meaning to this difference.\n\nThe coefficient captures not only possible direct effects of gender, but also the effects of all omitted variables that are correlated with gender and affect wage. These may include, for example, systematic differences in education levels, choice of field of study, with women underrepresented in higher-paying STEM fields, industry or occupation, hours worked, or willingness to relocate geographically.\n\nThe coefficient $\\beta_1$ therefore reflects a \"raw\" difference in earnings, combining multiple factors beyond the effect of gender. In fact, it is simply a **difference in means** of $wage$ between the two groups (7.10 - 4.59 $\\approx$ 2.51 dollars).\n\n\nEstimate the model using `fixest`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg_female <- feols(wage ~ female, data = wage1, vcov = \"hetero\")\nmodelsummary(list(\"Wage\" =reg_female), gof_omit = \"AIC|BIC|RMSE|R2 Adj.\", title = \"The dependent variable is Wage\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_vlkoq93wzpqtjierd0a6 = TinyTable.createTableFunctions(\"tinytable_vlkoq93wzpqtjierd0a6\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '6', j: 2 } ], css_id: 'tinytable_css_9hvtogtop0lp5y6lx983',}, \n          { positions: [ { i: '4', j: 2 } ], css_id: 'tinytable_css_li4llh4auwbedwp7pj89',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '5', j: 2 } ], css_id: 'tinytable_css_fmz62a5086u5uib2fhn1',}, \n          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_1swyrcmxtyxy5u7enhdq',}, \n          { positions: [ { i: '6', j: 1 } ], css_id: 'tinytable_css_bs8yyeirtd9m15njaf2m',}, \n          { positions: [ { i: '4', j: 1 } ], css_id: 'tinytable_css_7y25abaxl7s9zcboqto6',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '5', j: 1 } ], css_id: 'tinytable_css_l0pp0s9j781xq1a1503q',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_xm2x9way62vejr9h8b0t',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_vlkoq93wzpqtjierd0a6.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_vlkoq93wzpqtjierd0a6 td.tinytable_css_9hvtogtop0lp5y6lx983, #tinytable_vlkoq93wzpqtjierd0a6 th.tinytable_css_9hvtogtop0lp5y6lx983 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_vlkoq93wzpqtjierd0a6 td.tinytable_css_li4llh4auwbedwp7pj89, #tinytable_vlkoq93wzpqtjierd0a6 th.tinytable_css_li4llh4auwbedwp7pj89 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_vlkoq93wzpqtjierd0a6 td.tinytable_css_fmz62a5086u5uib2fhn1, #tinytable_vlkoq93wzpqtjierd0a6 th.tinytable_css_fmz62a5086u5uib2fhn1 { text-align: center }\n    #tinytable_vlkoq93wzpqtjierd0a6 td.tinytable_css_1swyrcmxtyxy5u7enhdq, #tinytable_vlkoq93wzpqtjierd0a6 th.tinytable_css_1swyrcmxtyxy5u7enhdq {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_vlkoq93wzpqtjierd0a6 td.tinytable_css_bs8yyeirtd9m15njaf2m, #tinytable_vlkoq93wzpqtjierd0a6 th.tinytable_css_bs8yyeirtd9m15njaf2m {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_vlkoq93wzpqtjierd0a6 td.tinytable_css_7y25abaxl7s9zcboqto6, #tinytable_vlkoq93wzpqtjierd0a6 th.tinytable_css_7y25abaxl7s9zcboqto6 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_vlkoq93wzpqtjierd0a6 td.tinytable_css_l0pp0s9j781xq1a1503q, #tinytable_vlkoq93wzpqtjierd0a6 th.tinytable_css_l0pp0s9j781xq1a1503q { text-align: left }\n    #tinytable_vlkoq93wzpqtjierd0a6 td.tinytable_css_xm2x9way62vejr9h8b0t, #tinytable_vlkoq93wzpqtjierd0a6 th.tinytable_css_xm2x9way62vejr9h8b0t {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_vlkoq93wzpqtjierd0a6\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <caption>The dependent variable is Wage</caption>\n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Wage</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">7.099</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.251)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">female</td>\n                  <td data-row=\"3\" data-col=\"2\">-2.512</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.298)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"5\" data-col=\"2\">526</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">R2</td>\n                  <td data-row=\"6\" data-col=\"2\">0.116</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\nThe regression results show that the average wage of men, represented by the intercept, is approximately 7.1 dollars per hour in 1976 dollars.\n\nThe coefficient on the dummy variable for female gender (`female`) is -2.51 dollars. Women earn approximately 2.51 dollars less than men on average. The average wage of women is approximately 4.58 dollars (7.1 - 2.51).\n\nHowever, remember that this difference cannot be interpreted causally without assuming that $E(u_i|female_i)=0$, an assumption that is difficult to defend because many variables, such as industry or occupation and type of education, may differ systematically between men and women and affect $wage$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstat_gender |>\n  tt(caption = \"Descriptive statistics\") |>\n  format_tt(digits = 2) |>\n  theme_tt(\"striped\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: The theme_tt() function is deprecated. Please use format-specific or style-specific theme functions instead:\n\nFormat-specific functions:\n\n* theme_html()\n* theme_latex()\n* theme_typst()\n\nStyle-specific functions:\n\n* theme_grid()\n* theme_revealjs()\n* theme_rotate()\n* theme_striped()\n* theme_empty()\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_vm871zdykwlg005damlz = TinyTable.createTableFunctions(\"tinytable_vm871zdykwlg005damlz\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '2', j: 1 }, { i: '2', j: 2 }, { i: '2', j: 3 }, { i: '2', j: 4 }, { i: '2', j: 5 }, { i: '2', j: 6 } ], css_id: 'tinytable_css_6nbtpjvkuao36jki5faa',}, \n          { positions: [ { i: '1', j: 1 }, { i: '1', j: 2 }, { i: '1', j: 3 }, { i: '1', j: 4 }, { i: '1', j: 5 }, { i: '1', j: 6 } ], css_id: 'tinytable_css_1djftrxrahapwfdiwo93',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 } ], css_id: 'tinytable_css_3g670bvfqwymh3ic3goh',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_vm871zdykwlg005damlz.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_vm871zdykwlg005damlz td.tinytable_css_6nbtpjvkuao36jki5faa, #tinytable_vm871zdykwlg005damlz th.tinytable_css_6nbtpjvkuao36jki5faa {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_vm871zdykwlg005damlz td.tinytable_css_1djftrxrahapwfdiwo93, #tinytable_vm871zdykwlg005damlz th.tinytable_css_1djftrxrahapwfdiwo93 { background-color: #ededed }\n    #tinytable_vm871zdykwlg005damlz td.tinytable_css_3g670bvfqwymh3ic3goh, #tinytable_vm871zdykwlg005damlz th.tinytable_css_3g670bvfqwymh3ic3goh {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_vm871zdykwlg005damlz\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <caption>Descriptive statistics</caption>\n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">female</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">wage_mean</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">wage_median</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">wage_sd</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">education_years_mean</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">education_years_median</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">0</td>\n                  <td data-row=\"1\" data-col=\"2\">7.1</td>\n                  <td data-row=\"1\" data-col=\"3\">6</td>\n                  <td data-row=\"1\" data-col=\"4\">4.2</td>\n                  <td data-row=\"1\" data-col=\"5\">13</td>\n                  <td data-row=\"1\" data-col=\"6\">12</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">1</td>\n                  <td data-row=\"2\" data-col=\"2\">4.6</td>\n                  <td data-row=\"2\" data-col=\"3\">3.8</td>\n                  <td data-row=\"2\" data-col=\"4\">2.5</td>\n                  <td data-row=\"2\" data-col=\"5\">12</td>\n                  <td data-row=\"2\" data-col=\"6\">12</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n### Dummy $male = 1?$\n\nGenerate a dummy variable equal to 1 if the worker is male and 0 if the worker is female. There are several ways to add it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwage1 <- wage1 %>%\n  mutate(male = ifelse(female == 1, 0, 1))\n```\n:::\n\n\n-  We create a new variable, `male`, equal to 1 if the individual is male and 0 if the individual is female.\n\n-  `ifelse(female == 1, 0, 1)` means that if $female$ = 1, then $male$ = 0; otherwise, $male$ = 1.\n\n-  Equivalently, $male$ can be created as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwage1 <- wage1 %>% \n  mutate(male = 1 - female)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg_male <- feols(wage ~ male, data = wage1, vcov = \"hetero\")\nmodelsummary(list(\"Wage\" = reg_female, \"Wage\" = reg_male), gof_omit = \"AIC|BIC|RMSE|R2 Adj.\", title = \"Female = 1 (first column) vs Male = 1 (second column)\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_j1w2wsod747y3js8zbfh = TinyTable.createTableFunctions(\"tinytable_j1w2wsod747y3js8zbfh\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '8', j: 2 }, { i: '8', j: 3 } ], css_id: 'tinytable_css_hi6ip04hmghap10uo5fh',}, \n          { positions: [ { i: '6', j: 2 }, { i: '6', j: 3 } ], css_id: 'tinytable_css_7dq7mp00bzjyizwu8xko',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '7', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '7', j: 3 } ], css_id: 'tinytable_css_wy1mhubnk4nfhoj7v7j6',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_ggrdgoovgzt7c9txh5qk',}, \n          { positions: [ { i: '8', j: 1 } ], css_id: 'tinytable_css_vzrbyrmvf9pxyb40fhof',}, \n          { positions: [ { i: '6', j: 1 } ], css_id: 'tinytable_css_4zdqabziu43xmc7rbauy',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '7', j: 1 } ], css_id: 'tinytable_css_4xqtqn2jys1rj6g8h9o0',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_nlspuhgjtcw3103pjtet',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_j1w2wsod747y3js8zbfh.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_j1w2wsod747y3js8zbfh td.tinytable_css_hi6ip04hmghap10uo5fh, #tinytable_j1w2wsod747y3js8zbfh th.tinytable_css_hi6ip04hmghap10uo5fh {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_j1w2wsod747y3js8zbfh td.tinytable_css_7dq7mp00bzjyizwu8xko, #tinytable_j1w2wsod747y3js8zbfh th.tinytable_css_7dq7mp00bzjyizwu8xko {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_j1w2wsod747y3js8zbfh td.tinytable_css_wy1mhubnk4nfhoj7v7j6, #tinytable_j1w2wsod747y3js8zbfh th.tinytable_css_wy1mhubnk4nfhoj7v7j6 { text-align: center }\n    #tinytable_j1w2wsod747y3js8zbfh td.tinytable_css_ggrdgoovgzt7c9txh5qk, #tinytable_j1w2wsod747y3js8zbfh th.tinytable_css_ggrdgoovgzt7c9txh5qk {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_j1w2wsod747y3js8zbfh td.tinytable_css_vzrbyrmvf9pxyb40fhof, #tinytable_j1w2wsod747y3js8zbfh th.tinytable_css_vzrbyrmvf9pxyb40fhof {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_j1w2wsod747y3js8zbfh td.tinytable_css_4zdqabziu43xmc7rbauy, #tinytable_j1w2wsod747y3js8zbfh th.tinytable_css_4zdqabziu43xmc7rbauy {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_j1w2wsod747y3js8zbfh td.tinytable_css_4xqtqn2jys1rj6g8h9o0, #tinytable_j1w2wsod747y3js8zbfh th.tinytable_css_4xqtqn2jys1rj6g8h9o0 { text-align: left }\n    #tinytable_j1w2wsod747y3js8zbfh td.tinytable_css_nlspuhgjtcw3103pjtet, #tinytable_j1w2wsod747y3js8zbfh th.tinytable_css_nlspuhgjtcw3103pjtet {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_j1w2wsod747y3js8zbfh\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <caption>Female = 1 (first column) vs Male = 1 (second column)</caption>\n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Wage</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Wage </th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">7.099</td>\n                  <td data-row=\"1\" data-col=\"3\">4.588</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.251)</td>\n                  <td data-row=\"2\" data-col=\"3\">(0.159)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">female</td>\n                  <td data-row=\"3\" data-col=\"2\">-2.512</td>\n                  <td data-row=\"3\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.298)</td>\n                  <td data-row=\"4\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">male</td>\n                  <td data-row=\"5\" data-col=\"2\"></td>\n                  <td data-row=\"5\" data-col=\"3\">2.512</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\"></td>\n                  <td data-row=\"6\" data-col=\"3\">(0.298)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"7\" data-col=\"2\">526</td>\n                  <td data-row=\"7\" data-col=\"3\">526</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\">R2</td>\n                  <td data-row=\"8\" data-col=\"2\">0.116</td>\n                  <td data-row=\"8\" data-col=\"3\">0.116</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nThe statistical properties of OLS remain the same as when $x_i$ is continuous.\n\n**Note**: If we included both $male$ and $female$, there would be perfect multicollinearity, so one variable would be removed automatically.\n\nIndeed, $male$ + $female$ = 1 for every observation. Including both variables together with the intercept generates perfect multicollinearity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg2dummy <- feols(wage ~ male + female, data = wage1, vcov = \"hetero\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe variable 'female' has been removed because of collinearity (see\n$collin.var).\n```\n\n\n:::\n\n```{.r .cell-code}\nreg2dummy\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS estimation, Dep. Var.: wage\nObservations: 526\nStandard-errors: Heteroskedasticity-robust \n            Estimate Std. Error  t value   Pr(>|t|)    \n(Intercept)  4.58766   0.159322 28.79495  < 2.2e-16 ***\nmale         2.51183   0.297621  8.43970 3.1252e-16 ***\n... 1 variable was removed because of collinearity (female)\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 3.46964   Adj. R2: 0.113979\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "tutorial1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}