{
  "hash": "d0b7ea2aa95b4231cc4de8cfa684c42c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tutorial 9\"\nsubtitle: \"Regression with instrumental variables (IV)\"\nauthor: \"Andrea Recine\"\ndate: today\nlang: en\n\nformat:\n  html:\n    # Layout\n    theme: flatly\n    toc: true\n    toc-depth: 3\n    toc-title: \"Contents\"\n    toc-location: right\n    number-sections: true\n\n    # Code\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    code-block-bg: true\n    code-block-border-left: false\n    highlight-style: github\n\n    # Output\n    embed-resources: true\n\n    # Typography\n    fontsize: 1.1em\n    linestretch: 1.6\n\nexecute:\n  warning: false\n  message: false\n  echo: true\n\nknitr:\n  opts_chunk:\n    comment: \"#>\"\n    fig.align: \"center\"\n    fig.width: 7\n    fig.height: 4.5\n\n---\n\n# Regression with instrumental variables\n\nIn this tutorial, we study instrumental variables (IV) regression as a method for addressing the endogeneity of one or more explanatory variables.\n\n\nThree important threats to internal validity are:\n\n1. Omitted variable bias due to an unobserved variable that is correlated with $X$ (and therefore cannot be included in the regression) and for which the available control variables are inadequate;\n\n2. Simultaneous causality bias ($X$ causes $Y$, and $Y$ causes $X$);\n\n3. Errors-in-variables bias ($X$ is measured with error).\n\n\nAll three problems imply $𝐸(u_i | X_i) \\neq 0$. Instrumental variables regression can eliminate the bias by using an instrument, $Z$.\n\n\nWe seek an external variable $Z$ that shifts $X$ through a specific, isolable channel.\n\n\n\n\nConsider the model $Y_i = \\beta_0 + \\beta_1 X_i + u_i$\n\n- The instrumental variables method divides $X$ into two components: one that may be correlated with $u$, and one that is not. By isolating the component that is uncorrelated with $u_i$, we can estimate $\\beta_1$.\n\n\n- To do so, we use an instrument, $Z_i$, that is correlated with $X_i$ but uncorrelated with $u_i$.\n\n\nWe are therefore interested in isolating the component of $X$ generated by $Z$.\n\n\nFor an instrumental variable (an “instrument”) $Z$ to be valid, it must satisfy two conditions:\n\n1. **Relevance:** $cor(Z_i, X_i) \\neq 0$. The instrument must shift $X$.\n2. **Exogeneity (exclusion restriction):** $cor(Z_i, u_i) = 0$. The instrument must not affect $Y$ except through the variation it generates in $X$. That is, $Z$ must affect $Y$ only **indirectly** through $X$ and must be uncorrelated with the unobserved determinants of $Y$.\n\n\n## Setup\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(knitr)\nlibrary(kableExtra)\nlibrary(modelsummary)\nlibrary(fixest)\nlibrary(wooldridge)\n```\n:::\n\n\n\n# Card (1995)\n\nCard (1995) used data on wages and education for a sample of men in 1976 to estimate the return to education. The instrument for education is a dummy variable indicating whether an individual grew up near a four-year college ($nearc4$).\n\n\nCard addressed this problem by using each student's distance from the nearest college as an instrumental variable. The underlying hypothesis is that a shorter geographic distance lowers the “cost” of attending college and therefore increases the probability of enrollment. At the same time, distance from college should not be directly related to the outcome of interest, namely future wages.\n\n\n\nTherefore, if $nearc4$ is indeed uncorrelated with the unobserved factors contained in the error term, it can be used as an instrument for $educ$.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata(\"card\", package = \"wooldridge\")\nhead(card)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   id nearc2 nearc4 educ age fatheduc motheduc weight momdad14 sinmom14 step14\n#> 1  2      0      0    7  29       NA       NA 158413        1        0      0\n#> 2  3      0      0   12  27        8        8 380166        1        0      0\n#> 3  4      0      0   12  34       14       12 367470        1        0      0\n#> 4  5      1      1   11  27       11       12 380166        1        0      0\n#> 5  6      1      1   12  34        8        7 367470        1        0      0\n#> 6  7      1      1   12  26        9       12 380166        1        0      0\n#>   reg661 reg662 reg663 reg664 reg665 reg666 reg667 reg668 reg669 south66 black\n#> 1      1      0      0      0      0      0      0      0      0       0     1\n#> 2      1      0      0      0      0      0      0      0      0       0     0\n#> 3      1      0      0      0      0      0      0      0      0       0     0\n#> 4      0      1      0      0      0      0      0      0      0       0     0\n#> 5      0      1      0      0      0      0      0      0      0       0     0\n#> 6      0      1      0      0      0      0      0      0      0       0     0\n#>   smsa south smsa66 wage enroll KWW  IQ married libcrd14 exper    lwage expersq\n#> 1    1     0      1  548      0  15  NA       1        0    16 6.306275     256\n#> 2    1     0      1  481      0  35  93       1        1     9 6.175867      81\n#> 3    1     0      1  721      0  42 103       1        1    16 6.580639     256\n#> 4    1     0      1  250      0  25  88       1        1    10 5.521461     100\n#> 5    1     0      1  729      0  34 108       1        0    16 6.591674     256\n#> 6    1     0      1  500      0  38  85       1        1     8 6.214608      64\n```\n\n\n:::\n:::\n\n\n\n- $wage$: hourly earnings **in cents** of a dollar\n- $educ$: years of education\n- $exper$: years of labor-market experience\n- $smsa$: residence in a metropolitan area (dummy variable)\n- $black$: whether the individual is Black (dummy variable)\n- $south$: whether the individual resides in the South\n- $nearc4$: dummy variable equal to 1 if the individual lives near a four-year college\n- $nearc2$: dummy variable equal to 1 if the individual lives near a two-year college\n\n\n**Exercise:**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nwage_educ <- feols(wage ~ educ + exper, data = card, vcov = \"hetero\")\nlogwage_educ <- feols(log(wage) ~ educ + exper, data = card, vcov = \"hetero\")\n\n\nmodelsummary(\n  list(\"Wage\" = wage_educ, \"Log Wage\" = logwage_educ), gof_omit = \"AIC|BIC|RMSE|R2 Adj.\"\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_m6qfglk9tqhtzugqxa72 = TinyTable.createTableFunctions(\"tinytable_m6qfglk9tqhtzugqxa72\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '8', j: 2 }, { i: '8', j: 3 } ], css_id: 'tinytable_css_jxobzm6dq0yfwsrfa83k',}, \n          { positions: [ { i: '6', j: 2 }, { i: '6', j: 3 } ], css_id: 'tinytable_css_mkl2rg9hz7m1nch3fbx5',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '7', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '7', j: 3 } ], css_id: 'tinytable_css_igdm19459vfc1pf6kfdf',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_akvkxnnn6jokqop8zvxd',}, \n          { positions: [ { i: '8', j: 1 } ], css_id: 'tinytable_css_4i0t2jb94ggckvd6588r',}, \n          { positions: [ { i: '6', j: 1 } ], css_id: 'tinytable_css_4guwrd1122pcep6fgimw',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '7', j: 1 } ], css_id: 'tinytable_css_5xetjlw45y75f3c22e2f',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_w22xug196u8eqrs9aokz',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_m6qfglk9tqhtzugqxa72.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_m6qfglk9tqhtzugqxa72 td.tinytable_css_jxobzm6dq0yfwsrfa83k, #tinytable_m6qfglk9tqhtzugqxa72 th.tinytable_css_jxobzm6dq0yfwsrfa83k {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_m6qfglk9tqhtzugqxa72 td.tinytable_css_mkl2rg9hz7m1nch3fbx5, #tinytable_m6qfglk9tqhtzugqxa72 th.tinytable_css_mkl2rg9hz7m1nch3fbx5 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_m6qfglk9tqhtzugqxa72 td.tinytable_css_igdm19459vfc1pf6kfdf, #tinytable_m6qfglk9tqhtzugqxa72 th.tinytable_css_igdm19459vfc1pf6kfdf { text-align: center }\n    #tinytable_m6qfglk9tqhtzugqxa72 td.tinytable_css_akvkxnnn6jokqop8zvxd, #tinytable_m6qfglk9tqhtzugqxa72 th.tinytable_css_akvkxnnn6jokqop8zvxd {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_m6qfglk9tqhtzugqxa72 td.tinytable_css_4i0t2jb94ggckvd6588r, #tinytable_m6qfglk9tqhtzugqxa72 th.tinytable_css_4i0t2jb94ggckvd6588r {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_m6qfglk9tqhtzugqxa72 td.tinytable_css_4guwrd1122pcep6fgimw, #tinytable_m6qfglk9tqhtzugqxa72 th.tinytable_css_4guwrd1122pcep6fgimw {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_m6qfglk9tqhtzugqxa72 td.tinytable_css_5xetjlw45y75f3c22e2f, #tinytable_m6qfglk9tqhtzugqxa72 th.tinytable_css_5xetjlw45y75f3c22e2f { text-align: left }\n    #tinytable_m6qfglk9tqhtzugqxa72 td.tinytable_css_w22xug196u8eqrs9aokz, #tinytable_m6qfglk9tqhtzugqxa72 th.tinytable_css_w22xug196u8eqrs9aokz {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_m6qfglk9tqhtzugqxa72\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Wage</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Log Wage</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">-375.588</td>\n                  <td data-row=\"1\" data-col=\"3\">4.666</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(42.504)</td>\n                  <td data-row=\"2\" data-col=\"3\">(0.065)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">educ</td>\n                  <td data-row=\"3\" data-col=\"2\">55.055</td>\n                  <td data-row=\"3\" data-col=\"3\">0.093</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(2.480)</td>\n                  <td data-row=\"4\" data-col=\"3\">(0.004)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">exper</td>\n                  <td data-row=\"5\" data-col=\"2\">25.142</td>\n                  <td data-row=\"5\" data-col=\"3\">0.041</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(1.513)</td>\n                  <td data-row=\"6\" data-col=\"3\">(0.002)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"7\" data-col=\"2\">3010</td>\n                  <td data-row=\"7\" data-col=\"3\">3010</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\">R2</td>\n                  <td data-row=\"8\" data-col=\"2\">0.181</td>\n                  <td data-row=\"8\" data-col=\"3\">0.181</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n::: {.callout-note title=\"Questions\"}\n1. How should the coefficients on $educ$ be interpreted in the two regressions?\n2. If $wage$ were expressed in dollars rather than cents, what would change in the two regressions?\n:::\n\n\n\n## Two-stage least squares (TSLS)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\niv_card <- feols(log(wage) ~ 1 | educ ~ nearc4, data = card, vcov = \"hetero\")\niv_card\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> TSLS estimation\n#> |- D.V.   : log(wage)\n#> |- Endo.  : educ\n#> |- Instr. : nearc4\n#> |\n#> |=> Second Stage\n#> |   Dep. Var.: log(wage)\n#> Observations: 3,010\n#> Standard-errors: Heteroskedasticity-robust \n#>             Estimate Std. Error  t value   Pr(>|t|)    \n#> (Intercept) 3.767472   0.346742 10.86535  < 2.2e-16 ***\n#> fit_educ    0.188063   0.026143  7.19373 7.9229e-13 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> RMSE: 0.556673   Adj. R2: 0.026448\n#> F-test (1st stage), educ: stat = 63.912, p = 1.838e-15, on 1 and 3,008 DoF.\n#>               Wu-Hausman: stat = 48.451, p = 4.141e-12, on 1 and 3,007 DoF.\n```\n\n\n:::\n:::\n\n\n\nThe IV regression is estimated with `feols` using the syntax `log(wage) ~ 1 | educ ~ nearc4`.\n\nThe idea behind **two-stage least squares (TSLS)** is to isolate the “clean” component of $X_i$—the component uncorrelated with $u_i$—in two steps.\n\n**First stage.** Regress the endogenous regressor on the instrument by OLS,\n\n$$\nX_i = \\pi_0 + \\pi_1 Z_i + v_i\n$$\n\nand compute the fitted values $\\hat{X}_i = \\hat{\\pi}_0 + \\hat{\\pi}_1 Z_i$. By construction, these are a linear function of $Z_i$ alone and therefore **inherit the instrument's exogeneity**. The component of $X_i$ correlated with $u_i$—the residual $\\hat{v}_i$—is excluded.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfs_card <- feols(educ ~ nearc4, data = card, vcov = \"hetero\")\nfs_card\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> OLS estimation, Dep. Var.: educ\n#> Observations: 3,010\n#> Standard-errors: Heteroskedasticity-robust \n#>              Estimate Std. Error   t value   Pr(>|t|)    \n#> (Intercept) 12.698015   0.090220 140.74510  < 2.2e-16 ***\n#> nearc4       0.829019   0.106694   7.77005 1.0684e-14 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> RMSE: 2.64848   Adj. R2: 0.02048\n```\n\n\n:::\n\n```{.r .cell-code}\ncard$educ_hat <- predict(fs_card)\n```\n:::\n\n\n\n**Second stage.** Regress $Y_i$ on the fitted value $\\hat{X}_i$ rather than on $X_i$:\n\n$$\nY_i = \\beta_0 + \\beta_1 \\hat{X}_i + \\varepsilon_i\n$$\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsstage_card <- feols(log(wage) ~ educ_hat, data = card, vcov = \"hetero\")\nsstage_card\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> OLS estimation, Dep. Var.: log(wage)\n#> Observations: 3,010\n#> Standard-errors: Heteroskedasticity-robust \n#>             Estimate Std. Error  t value  Pr(>|t|)    \n#> (Intercept) 3.767472   0.272493 13.82595 < 2.2e-16 ***\n#> educ_hat    0.188063   0.020545  9.15350 < 2.2e-16 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> RMSE: 0.437744   Adj. R2: 0.026448\n```\n\n\n:::\n:::\n\n\n::: {.callout-important}\nWith **one instrument and one endogenous regressor**, the TSLS estimator is exactly equal to the direct IV estimator (the covariance ratio in the next section): $\\hat{\\beta}_1^{TSLS} = \\hat{\\beta}_1^{IV}$. The advantage of the two-stage formulation is that it extends readily to multiple instruments, multiple endogenous regressors, and additional controls, whereas the simple covariance ratio does not.\n:::\n\nWhen the two stages are performed “by hand,” however, the **standard errors are incorrect**: the second regression treats $\\hat{X}_i$ as observed, ignoring that it was itself estimated in the first stage. In practice, we therefore use the IV syntax in `feols`, which computes the appropriate standard errors. As usual, we use heteroskedasticity-robust standard errors.\n\n\n## Direct algebraic derivation\n\nBecause we are estimating a regression with one endogenous variable and one instrument, we can derive the IV estimator algebraically. Begin with the structural equation:\n\n$$\nY_i = \\beta_0 + \\beta_1 X_i + u_i\n$$\n\nWe know that $X_i$ is endogenous, meaning that $\\text{Cov}(X_i, u_i) \\neq 0$, which is why OLS is biased. The key step is to take the **covariance of both sides with the instrument** $Z_i$. Covariance is a linear operator, and the covariance of a constant with any variable is zero, so:\n\n$$\n\\text{Cov}(Y_i, Z_i) = \\beta_1 \\, \\text{Cov}(X_i, Z_i) + \\text{Cov}(u_i, Z_i)\n$$\n\nThe final term is zero by the instrument exogeneity condition ($\\text{Cov}(Z_i, u_i) = 0$). This leaves one equation in one unknown, which we can solve for $\\beta_1$:\n\n$$\n\\beta_1 = \\frac{\\text{Cov}(Y_i, Z_i)}{\\text{Cov}(X_i, Z_i)}\n$$\n\nOnce a valid instrument is available, $\\beta_1$ becomes a simple function of two observable covariances. The **relevance** condition ($\\text{Cov}(X_i, Z_i) \\neq 0$) ensures that the denominator is nonzero. If the instrument were irrelevant, the expression would take the indeterminate form $0/0$ and would not identify the parameter.\n\nThe **IV estimator** replaces the population covariances with their sample counterparts ($s_{YZ}$ and $s_{XZ}$):\n\n$$\n\\hat{\\beta}_1^{IV} = \\frac{s_{YZ}}{s_{XZ}}\n$$\n\nIn our application, $Y = \\log(wage)$ (the `lwage` column), $X = educ$, and $Z = nearc4$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncov(card$nearc4, card$lwage)/cov(card$nearc4, card$educ)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.1880626\n```\n\n\n:::\n:::\n\n\nThe result equals the TSLS estimate of $\\beta_1$ from the model without controls (`iv_card`).\n\n\n\n## Derivation from the reduced form\n\n$$\nY_i = \\beta_0 + \\beta_1 X_i + u_i\n$$\n\n$$\nX_i = \\pi_0 + \\pi_1 Z_i + v_i\n$$\n\nSubstituting the first-stage equation into the structural equation gives:\n\n$$\nY_i = \\beta_0 + \\beta_1(\\pi_0 + \\pi_1 Z_i + v_i) + u_i\n= \\underbrace{(\\beta_0 + \\beta_1\\pi_0)}_{\\gamma_0} + \\underbrace{\\beta_1\\pi_1}_{\\gamma_1}\\, Z_i + \\underbrace{(\\beta_1 v_i + u_i)}_{\\omega_i}\n$$\n\nthat is, a regression of the outcome on the instrument alone:\n\n$$\nY_i = \\gamma_0 + \\gamma_1 Z_i + \\omega_i\n$$\n\nThe reduced-form coefficient is therefore $\\gamma_1 = \\beta_1 \\pi_1$: the product of the coefficient of interest, $\\beta_1$, and the first-stage coefficient, $\\pi_1$. Dividing by $\\pi_1$ recovers $\\beta_1$:\n\n$$\n\\beta_1 = \\frac{\\gamma_1}{\\pi_1}\n$$\n\nwhich is exactly what the estimator $\\hat{\\beta}_1^{IV} = \\hat{\\gamma}_1 / \\hat{\\pi}_1$ does.\n\nWe previously estimated the regression of the endogenous variable on the instrument as `fs_card`. We now estimate the regression of the dependent variable on the instrument.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrf_card <- feols(log(wage) ~ nearc4, data = card, vcov = \"hetero\")\nrf_card\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> OLS estimation, Dep. Var.: log(wage)\n#> Observations: 3,010\n#> Standard-errors: Heteroskedasticity-robust \n#>             Estimate Std. Error  t value  Pr(>|t|)    \n#> (Intercept) 6.155494   0.013989 440.0200 < 2.2e-16 ***\n#> nearc4      0.155907   0.017033   9.1535 < 2.2e-16 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> RMSE: 0.437744   Adj. R2: 0.026448\n```\n\n\n:::\n:::\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Extract the coefficients\nbeta_fs_1 <- coef(fs_card)[\"nearc4\"]  # first-stage coefficient\nbeta_rf_1 <- coef(rf_card)[\"nearc4\"]  # reduced-form coefficient\n\nbeta_rf_1 / beta_fs_1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>    nearc4 \n#> 0.1880626\n```\n\n\n:::\n:::\n\n\n\n## General model\n\nSo far, we have considered one endogenous regressor ($X_i$) and one instrument ($Z_i$). In practice, we also want to include a set of **included exogenous variables** $W_{1i}, \\dots, W_{ki}$—*exogenous* because they are assumed to be uncorrelated with the error term.\n\n$$\nY_i = \\beta_0 + \\beta_1 X_i + \\delta_1 W_{1i} + \\dots + \\delta_k W_{ki} + u_i\n$$\n\n\nEvery exogenous variable included in the structural equation must also appear in the first stage. Thus, the first stage is:\n\n\n$$\nX_i = \\pi_0 + \\pi_1 Z_i + \\zeta_1 W_{1i} + \\dots + \\zeta_k W_{ki} + v_i\n$$\n\nThe fitted values $\\hat{X}_i$ are then a linear function only of the exogenous variables ($Z_i$ and the $W$ variables). In the second stage, regress $Y_i$ on $\\hat{X}_i$ and the same $W$ variables:\n\n$$\nY_i = \\beta_0 + \\beta_1 \\hat{X}_i + \\delta_1 W_{1i} + \\dots + \\delta_k W_{ki} + \\text{error}\n$$\n\nIf the $W$ variables were omitted from the first stage, $\\hat{X}_i$ would inherit the component of their variation correlated with $u_i$, and the estimator would again be biased.\n\n\n::: {.callout-important title=\"The exclusion restriction becomes conditional\"}\nWith controls, instrument exogeneity is **conditional** on $W$:\n\n$$\nE(u_i \\mid W_i, Z_i) = E(u_i \\mid W_i) = 0\n$$\n\n\nThe first equality, instrument exogeneity, states that conditional on $W$, knowing $Z_i$ provides no additional information about the error (the instrument does not enter the equation for $Y$ directly). The second states that the $W$ variables are themselves exogenous.\n\n\nThe intuition is that $Z_i$ must vary **as if randomly assigned** among units with the same values of $W$. The $W$ variables make this “as if” comparison credible: in many applications, $Z_i$ is not unconditionally exogenous but may be conditionally exogenous when units with similar relevant characteristics are compared. Choosing $W$ is therefore an integral part of the identification argument, as the geographic controls in the Card application illustrate.\n:::\n\n\nIn Card's model, the $W$ variables are $exper$, $expersq$, $black$, $smsa$, and $south$. The `feols` syntax `log(wage) ~ W1 + W2 + ... | educ ~ nearc4` automatically includes the $W$ variables in both stages.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\niv_card_controls <- feols(log(wage) ~ exper + expersq + black + smsa + south | educ ~ nearc4, data = card, vcov = \"hetero\")\n\nsummary(iv_card_controls)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> TSLS estimation\n#> |- D.V.   : log(wage)\n#> |- Endo.  : educ\n#> |- Instr. : nearc4\n#> |\n#> |=> Second Stage\n#> |   Dep. Var.: log(wage)\n#> Observations: 3,010\n#> Standard-errors: Heteroskedasticity-robust \n#>              Estimate Std. Error  t value   Pr(>|t|)    \n#> (Intercept)  3.752781   0.817701  4.58943 4.6269e-06 ***\n#> fit_educ     0.132289   0.048578  2.72323 6.5020e-03 ** \n#> exper        0.107498   0.021137  5.08565 3.8886e-07 ***\n#> expersq     -0.002284   0.000347 -6.58724 5.2707e-11 ***\n#> black       -0.130802   0.051511 -2.53929 1.1158e-02 *  \n#> smsa         0.131324   0.029803  4.40638 1.0879e-05 ***\n#> south       -0.104901   0.022926 -4.57554 4.9425e-06 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> RMSE: 0.390578   Adj. R2: 0.185432\n#> F-test (1st stage), educ: stat = 16.7176, p = 4.452e-5, on 1 and 3,003 DoF.\n#>               Wu-Hausman: stat =  1.5390, p = 0.214858, on 1 and 3,002 DoF.\n```\n\n\n:::\n:::\n\n\n\n**OLS comparison:**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nols_card_controls <- feols(log(wage) ~ exper + expersq + black + smsa + south + educ, data = card, vcov = \"hetero\")\n\nmodelsummary(\n  list(\"Log Wage (OLS)\" = ols_card_controls, \"Log Wage (IV)\" = iv_card_controls), gof_omit = \"AIC|BIC|RMSE|R2 Adj.\"\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_m6e5ip8e0bgwysw5d8ax = TinyTable.createTableFunctions(\"tinytable_m6e5ip8e0bgwysw5d8ax\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '18', j: 2 }, { i: '18', j: 3 } ], css_id: 'tinytable_css_xbhtqgqp0np7mo95t7ne',}, \n          { positions: [ { i: '16', j: 2 }, { i: '16', j: 3 } ], css_id: 'tinytable_css_dy6cxzewavgitsssyzoi',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '14', j: 2 }, { i: '15', j: 2 }, { i: '17', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 }, { i: '13', j: 3 }, { i: '14', j: 3 }, { i: '15', j: 3 }, { i: '17', j: 3 } ], css_id: 'tinytable_css_q1sbsm4ynfpdvaya2d7y',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_0lpz6fywbfonlls8s7ew',}, \n          { positions: [ { i: '18', j: 1 } ], css_id: 'tinytable_css_5oyrnhkx2lp8slflg5ck',}, \n          { positions: [ { i: '16', j: 1 } ], css_id: 'tinytable_css_fm8w33e3gug03ll8fh4v',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 }, { i: '14', j: 1 }, { i: '15', j: 1 }, { i: '17', j: 1 } ], css_id: 'tinytable_css_gdlvba6lj07e2iuuqyfx',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_lwt4dslvlmlxjsw0g3kf',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_m6e5ip8e0bgwysw5d8ax.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_m6e5ip8e0bgwysw5d8ax td.tinytable_css_xbhtqgqp0np7mo95t7ne, #tinytable_m6e5ip8e0bgwysw5d8ax th.tinytable_css_xbhtqgqp0np7mo95t7ne {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_m6e5ip8e0bgwysw5d8ax td.tinytable_css_dy6cxzewavgitsssyzoi, #tinytable_m6e5ip8e0bgwysw5d8ax th.tinytable_css_dy6cxzewavgitsssyzoi {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_m6e5ip8e0bgwysw5d8ax td.tinytable_css_q1sbsm4ynfpdvaya2d7y, #tinytable_m6e5ip8e0bgwysw5d8ax th.tinytable_css_q1sbsm4ynfpdvaya2d7y { text-align: center }\n    #tinytable_m6e5ip8e0bgwysw5d8ax td.tinytable_css_0lpz6fywbfonlls8s7ew, #tinytable_m6e5ip8e0bgwysw5d8ax th.tinytable_css_0lpz6fywbfonlls8s7ew {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_m6e5ip8e0bgwysw5d8ax td.tinytable_css_5oyrnhkx2lp8slflg5ck, #tinytable_m6e5ip8e0bgwysw5d8ax th.tinytable_css_5oyrnhkx2lp8slflg5ck {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_m6e5ip8e0bgwysw5d8ax td.tinytable_css_fm8w33e3gug03ll8fh4v, #tinytable_m6e5ip8e0bgwysw5d8ax th.tinytable_css_fm8w33e3gug03ll8fh4v {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_m6e5ip8e0bgwysw5d8ax td.tinytable_css_gdlvba6lj07e2iuuqyfx, #tinytable_m6e5ip8e0bgwysw5d8ax th.tinytable_css_gdlvba6lj07e2iuuqyfx { text-align: left }\n    #tinytable_m6e5ip8e0bgwysw5d8ax td.tinytable_css_lwt4dslvlmlxjsw0g3kf, #tinytable_m6e5ip8e0bgwysw5d8ax th.tinytable_css_lwt4dslvlmlxjsw0g3kf {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_m6e5ip8e0bgwysw5d8ax\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Log Wage (OLS)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Log Wage (IV)</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">4.734</td>\n                  <td data-row=\"1\" data-col=\"3\">3.753</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.070)</td>\n                  <td data-row=\"2\" data-col=\"3\">(0.818)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">exper</td>\n                  <td data-row=\"3\" data-col=\"2\">0.084</td>\n                  <td data-row=\"3\" data-col=\"3\">0.107</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.007)</td>\n                  <td data-row=\"4\" data-col=\"3\">(0.021)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">expersq</td>\n                  <td data-row=\"5\" data-col=\"2\">-0.002</td>\n                  <td data-row=\"5\" data-col=\"3\">-0.002</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.000)</td>\n                  <td data-row=\"6\" data-col=\"3\">(0.000)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">black</td>\n                  <td data-row=\"7\" data-col=\"2\">-0.190</td>\n                  <td data-row=\"7\" data-col=\"3\">-0.131</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\">(0.017)</td>\n                  <td data-row=\"8\" data-col=\"3\">(0.052)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">smsa</td>\n                  <td data-row=\"9\" data-col=\"2\">0.161</td>\n                  <td data-row=\"9\" data-col=\"3\">0.131</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\">(0.015)</td>\n                  <td data-row=\"10\" data-col=\"3\">(0.030)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">south</td>\n                  <td data-row=\"11\" data-col=\"2\">-0.125</td>\n                  <td data-row=\"11\" data-col=\"3\">-0.105</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\"></td>\n                  <td data-row=\"12\" data-col=\"2\">(0.015)</td>\n                  <td data-row=\"12\" data-col=\"3\">(0.023)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">educ</td>\n                  <td data-row=\"13\" data-col=\"2\">0.074</td>\n                  <td data-row=\"13\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"14\" data-col=\"1\"></td>\n                  <td data-row=\"14\" data-col=\"2\">(0.004)</td>\n                  <td data-row=\"14\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"15\" data-col=\"1\">fit_educ</td>\n                  <td data-row=\"15\" data-col=\"2\"></td>\n                  <td data-row=\"15\" data-col=\"3\">0.132</td>\n                </tr>\n                <tr>\n                  <td data-row=\"16\" data-col=\"1\"></td>\n                  <td data-row=\"16\" data-col=\"2\"></td>\n                  <td data-row=\"16\" data-col=\"3\">(0.049)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"17\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"17\" data-col=\"2\">3010</td>\n                  <td data-row=\"17\" data-col=\"3\">3010</td>\n                </tr>\n                <tr>\n                  <td data-row=\"18\" data-col=\"1\">R2</td>\n                  <td data-row=\"18\" data-col=\"2\">0.291</td>\n                  <td data-row=\"18\" data-col=\"3\">0.187</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\nIn the OLS regression, one additional year of education is associated with an average increase in wages of approximately 7.4%, holding the other variables constant.\n\nThe TSLS regression yields a larger estimate: one additional year of education is associated with an average increase in wages of approximately 13.2%.\n\n\n### Why geographic controls are needed\n\nInstrument exogeneity ($cor(Z_i, u_i) = 0$) is the critical assumption, and it is useful to see how it could fail. Four-year colleges have historically been concentrated in metropolitan areas in the Northeast and on the Pacific coast, where average wages are also higher for reasons unrelated to an individual's education: agglomeration economies, cost of living, and the sectoral composition of the local economy.\n\nSuppose that no geographic controls were included. Distance to college would tend to be shorter for individuals raised in Boston or San Francisco, and those individuals might also earn more as adults than comparable individuals raised in the rural South, regardless of their education. The entire wage difference between living “near a college” and “far from a college” would enter $u_i$ as an urban wage premium. It would then be correlated with $nearc4$ by construction, implying $cor(Z_i, u_i) \\neq 0$. The IV estimate would combine the return to education with the urban wage premium, and the two effects could not be distinguished.\n\nWe therefore add controls for geography and socioeconomic context: residence in a metropolitan area (`smsa`) and census-region dummy variables (`reg662`–`reg669`). Conditional on these controls, identification relies only on variation in distance across areas with similar observed characteristics, reducing the concern that an urban wage premium is confounded with the return to education.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\niv_card_geo <- feols(log(wage) ~ exper + expersq + black + smsa +\n                       reg662 + reg663 + reg664 + reg665 +\n                       reg666 + reg667 + reg668 + reg669\n                     | educ ~ nearc4, data = card, vcov = \"hetero\")\n\nmodelsummary(\n  list(\"IV (baseline)\" = iv_card_controls, \"IV (+ geography)\" = iv_card_geo), gof_omit = \"AIC|BIC|RMSE|R2 Adj.\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_24ato9rb75j47rt1euh6 = TinyTable.createTableFunctions(\"tinytable_24ato9rb75j47rt1euh6\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '32', j: 2 }, { i: '32', j: 3 } ], css_id: 'tinytable_css_k15ve0q5bg2wl3huo0xm',}, \n          { positions: [ { i: '30', j: 2 }, { i: '30', j: 3 } ], css_id: 'tinytable_css_8hhz7th91vtudf1l0d4y',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '14', j: 2 }, { i: '15', j: 2 }, { i: '16', j: 2 }, { i: '17', j: 2 }, { i: '18', j: 2 }, { i: '19', j: 2 }, { i: '20', j: 2 }, { i: '21', j: 2 }, { i: '22', j: 2 }, { i: '23', j: 2 }, { i: '24', j: 2 }, { i: '25', j: 2 }, { i: '26', j: 2 }, { i: '27', j: 2 }, { i: '28', j: 2 }, { i: '29', j: 2 }, { i: '31', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 }, { i: '13', j: 3 }, { i: '14', j: 3 }, { i: '15', j: 3 }, { i: '16', j: 3 }, { i: '17', j: 3 }, { i: '18', j: 3 }, { i: '19', j: 3 }, { i: '20', j: 3 }, { i: '21', j: 3 }, { i: '22', j: 3 }, { i: '23', j: 3 }, { i: '24', j: 3 }, { i: '25', j: 3 }, { i: '26', j: 3 }, { i: '27', j: 3 }, { i: '28', j: 3 }, { i: '29', j: 3 }, { i: '31', j: 3 } ], css_id: 'tinytable_css_tvmsk515s63wh8pyjxs4',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_3clmffxkoozy4r3uzm1q',}, \n          { positions: [ { i: '32', j: 1 } ], css_id: 'tinytable_css_lxsq26th8fkl4zfjqy2o',}, \n          { positions: [ { i: '30', j: 1 } ], css_id: 'tinytable_css_8t6i116i5vvkd10htdgh',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 }, { i: '14', j: 1 }, { i: '15', j: 1 }, { i: '16', j: 1 }, { i: '17', j: 1 }, { i: '18', j: 1 }, { i: '19', j: 1 }, { i: '20', j: 1 }, { i: '21', j: 1 }, { i: '22', j: 1 }, { i: '23', j: 1 }, { i: '24', j: 1 }, { i: '25', j: 1 }, { i: '26', j: 1 }, { i: '27', j: 1 }, { i: '28', j: 1 }, { i: '29', j: 1 }, { i: '31', j: 1 } ], css_id: 'tinytable_css_d1fop08fq79niliw4jjf',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_t0r8xv3infvw454nuh77',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_24ato9rb75j47rt1euh6.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_24ato9rb75j47rt1euh6 td.tinytable_css_k15ve0q5bg2wl3huo0xm, #tinytable_24ato9rb75j47rt1euh6 th.tinytable_css_k15ve0q5bg2wl3huo0xm {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_24ato9rb75j47rt1euh6 td.tinytable_css_8hhz7th91vtudf1l0d4y, #tinytable_24ato9rb75j47rt1euh6 th.tinytable_css_8hhz7th91vtudf1l0d4y {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_24ato9rb75j47rt1euh6 td.tinytable_css_tvmsk515s63wh8pyjxs4, #tinytable_24ato9rb75j47rt1euh6 th.tinytable_css_tvmsk515s63wh8pyjxs4 { text-align: center }\n    #tinytable_24ato9rb75j47rt1euh6 td.tinytable_css_3clmffxkoozy4r3uzm1q, #tinytable_24ato9rb75j47rt1euh6 th.tinytable_css_3clmffxkoozy4r3uzm1q {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_24ato9rb75j47rt1euh6 td.tinytable_css_lxsq26th8fkl4zfjqy2o, #tinytable_24ato9rb75j47rt1euh6 th.tinytable_css_lxsq26th8fkl4zfjqy2o {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_24ato9rb75j47rt1euh6 td.tinytable_css_8t6i116i5vvkd10htdgh, #tinytable_24ato9rb75j47rt1euh6 th.tinytable_css_8t6i116i5vvkd10htdgh {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_24ato9rb75j47rt1euh6 td.tinytable_css_d1fop08fq79niliw4jjf, #tinytable_24ato9rb75j47rt1euh6 th.tinytable_css_d1fop08fq79niliw4jjf { text-align: left }\n    #tinytable_24ato9rb75j47rt1euh6 td.tinytable_css_t0r8xv3infvw454nuh77, #tinytable_24ato9rb75j47rt1euh6 th.tinytable_css_t0r8xv3infvw454nuh77 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_24ato9rb75j47rt1euh6\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">IV (baseline)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">IV (+ geography)</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">3.753</td>\n                  <td data-row=\"1\" data-col=\"3\">3.485</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.818)</td>\n                  <td data-row=\"2\" data-col=\"3\">(0.876)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">fit_educ</td>\n                  <td data-row=\"3\" data-col=\"2\">0.132</td>\n                  <td data-row=\"3\" data-col=\"3\">0.142</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.049)</td>\n                  <td data-row=\"4\" data-col=\"3\">(0.052)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">exper</td>\n                  <td data-row=\"5\" data-col=\"2\">0.107</td>\n                  <td data-row=\"5\" data-col=\"3\">0.113</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.021)</td>\n                  <td data-row=\"6\" data-col=\"3\">(0.023)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">expersq</td>\n                  <td data-row=\"7\" data-col=\"2\">-0.002</td>\n                  <td data-row=\"7\" data-col=\"3\">-0.002</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\">(0.000)</td>\n                  <td data-row=\"8\" data-col=\"3\">(0.000)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">black</td>\n                  <td data-row=\"9\" data-col=\"2\">-0.131</td>\n                  <td data-row=\"9\" data-col=\"3\">-0.135</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\">(0.052)</td>\n                  <td data-row=\"10\" data-col=\"3\">(0.051)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">smsa</td>\n                  <td data-row=\"11\" data-col=\"2\">0.131</td>\n                  <td data-row=\"11\" data-col=\"3\">0.126</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\"></td>\n                  <td data-row=\"12\" data-col=\"2\">(0.030)</td>\n                  <td data-row=\"12\" data-col=\"3\">(0.032)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">south</td>\n                  <td data-row=\"13\" data-col=\"2\">-0.105</td>\n                  <td data-row=\"13\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"14\" data-col=\"1\"></td>\n                  <td data-row=\"14\" data-col=\"2\">(0.023)</td>\n                  <td data-row=\"14\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"15\" data-col=\"1\">reg662</td>\n                  <td data-row=\"15\" data-col=\"2\"></td>\n                  <td data-row=\"15\" data-col=\"3\">0.100</td>\n                </tr>\n                <tr>\n                  <td data-row=\"16\" data-col=\"1\"></td>\n                  <td data-row=\"16\" data-col=\"2\"></td>\n                  <td data-row=\"16\" data-col=\"3\">(0.037)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"17\" data-col=\"1\">reg663</td>\n                  <td data-row=\"17\" data-col=\"2\"></td>\n                  <td data-row=\"17\" data-col=\"3\">0.146</td>\n                </tr>\n                <tr>\n                  <td data-row=\"18\" data-col=\"1\"></td>\n                  <td data-row=\"18\" data-col=\"2\"></td>\n                  <td data-row=\"18\" data-col=\"3\">(0.036)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"19\" data-col=\"1\">reg664</td>\n                  <td data-row=\"19\" data-col=\"2\"></td>\n                  <td data-row=\"19\" data-col=\"3\">0.048</td>\n                </tr>\n                <tr>\n                  <td data-row=\"20\" data-col=\"1\"></td>\n                  <td data-row=\"20\" data-col=\"2\"></td>\n                  <td data-row=\"20\" data-col=\"3\">(0.044)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"21\" data-col=\"1\">reg665</td>\n                  <td data-row=\"21\" data-col=\"2\"></td>\n                  <td data-row=\"21\" data-col=\"3\">0.028</td>\n                </tr>\n                <tr>\n                  <td data-row=\"22\" data-col=\"1\"></td>\n                  <td data-row=\"22\" data-col=\"2\"></td>\n                  <td data-row=\"22\" data-col=\"3\">(0.043)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"23\" data-col=\"1\">reg666</td>\n                  <td data-row=\"23\" data-col=\"2\"></td>\n                  <td data-row=\"23\" data-col=\"3\">0.044</td>\n                </tr>\n                <tr>\n                  <td data-row=\"24\" data-col=\"1\"></td>\n                  <td data-row=\"24\" data-col=\"2\"></td>\n                  <td data-row=\"24\" data-col=\"3\">(0.047)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"25\" data-col=\"1\">reg667</td>\n                  <td data-row=\"25\" data-col=\"2\"></td>\n                  <td data-row=\"25\" data-col=\"3\">0.007</td>\n                </tr>\n                <tr>\n                  <td data-row=\"26\" data-col=\"1\"></td>\n                  <td data-row=\"26\" data-col=\"2\"></td>\n                  <td data-row=\"26\" data-col=\"3\">(0.044)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"27\" data-col=\"1\">reg668</td>\n                  <td data-row=\"27\" data-col=\"2\"></td>\n                  <td data-row=\"27\" data-col=\"3\">-0.085</td>\n                </tr>\n                <tr>\n                  <td data-row=\"28\" data-col=\"1\"></td>\n                  <td data-row=\"28\" data-col=\"2\"></td>\n                  <td data-row=\"28\" data-col=\"3\">(0.058)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"29\" data-col=\"1\">reg669</td>\n                  <td data-row=\"29\" data-col=\"2\"></td>\n                  <td data-row=\"29\" data-col=\"3\">0.109</td>\n                </tr>\n                <tr>\n                  <td data-row=\"30\" data-col=\"1\"></td>\n                  <td data-row=\"30\" data-col=\"2\"></td>\n                  <td data-row=\"30\" data-col=\"3\">(0.042)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"31\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"31\" data-col=\"2\">3010</td>\n                  <td data-row=\"31\" data-col=\"3\">3010</td>\n                </tr>\n                <tr>\n                  <td data-row=\"32\" data-col=\"1\">R2</td>\n                  <td data-row=\"32\" data-col=\"2\">0.187</td>\n                  <td data-row=\"32\" data-col=\"3\">0.187</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nThe coefficient on $educ$ remains broadly stable (around 14%) after geographic controls are included. At least with respect to observed characteristics, the urban wage premium does not appear to cause substantial bias. The fundamental point remains: these controls are essential to a credible defense of instrument exogeneity.\n\n\n## Overidentification\n\nSo far, we have considered one instrument $Z_i$ for the endogenous variable $X_i$. Having **multiple instruments** does not change the basic identification requirement—one valid instrument is sufficient to identify $\\beta_1$—but it may substantially improve the **precision** of the estimate.\n\nWith $m$ instruments $Z_{1i}, \\dots, Z_{mi}$ and $k$ included exogenous variables $W_{1i}, \\dots, W_{ki}$, the TSLS first stage becomes\n\n$$\nX_i = \\pi_0 + \\pi_1 Z_{1i} + \\dots + \\pi_m Z_{mi} + \\zeta_1 W_{1i} + \\dots + \\zeta_k W_{ki} + v_i\n$$\n\nand the second stage uses the fitted values $\\hat{X}_i$ exactly as before.\n\n\nThe idea is unchanged: extract the component of $X_i$ that varies for exogenous reasons. Because the variance of the TSLS estimator is inversely related to $\\text{Var}(\\hat{X}_i)$, additional relevant instruments can reduce the variance of the estimate.\n\nIf a new instrument is essentially **redundant** given the existing instruments, the gain is small. If it shifts $X_i$ for a **different** reason, it may add meaningful exogenous variation and substantially improve precision. Ideally, the instruments capture distinct dimensions of exogenous variation in $X_i$.\n\n\nThe Card dataset provides two distinct indicators of proximity to a postsecondary institution: $nearc4$ (a four-year college) and $nearc2$ (a two-year community college).\n\n\nThey are separate instruments because they operate through different channels: a community college lowers barriers to technical and vocational programs and to completing a few additional years of education, whereas a four-year college lowers barriers to completing a bachelor's degree. Both shift $educ$, but not identically. Using them together makes the model **overidentified** (two instruments for one endogenous regressor).\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\niv_card_overid <- feols(log(wage) ~ exper + expersq + black + smsa + south | educ ~ nearc4 + nearc2, data = card, vcov = \"hetero\")\niv_card_overid\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> TSLS estimation\n#> |- D.V.   : log(wage)\n#> |- Endo.  : educ\n#> |- Instr. : nearc4, nearc2\n#> |\n#> |=> Second Stage\n#> |   Dep. Var.: log(wage)\n#> Observations: 3,010\n#> Standard-errors: Heteroskedasticity-robust \n#>              Estimate Std. Error  t value   Pr(>|t|)    \n#> (Intercept)  3.272102   0.817829  4.00096 6.4609e-05 ***\n#> fit_educ     0.160849   0.048570  3.31166 9.3843e-04 ***\n#> exper        0.119211   0.021328  5.58944 2.4822e-08 ***\n#> expersq     -0.002305   0.000369 -6.24624 4.7980e-10 ***\n#> black       -0.101973   0.052080 -1.95801 5.0321e-02 .  \n#> smsa         0.116574   0.030293  3.84822 1.2146e-04 ***\n#> south       -0.095119   0.023433 -4.05915 5.0510e-05 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> RMSE: 0.410172   Adj. R2: 0.186685\n#> F-test (1st stage), educ: stat = 9.4527, p = 8.084e-5, on 2 and 3,002 DoF.\n#>               Wu-Hausman: stat = 3.8685, p = 0.049293, on 1 and 3,002 DoF.\n#>                   Sargan: stat = 2.6508, p = 0.103497, on 1 DoF.\n```\n\n\n:::\n:::\n\n\n\n\n**Test of overidentifying restrictions (the $J$ test).** Instrument exogeneity cannot be tested directly because the error $u_i$ is unobserved. It can, however, be assessed **partially** when the model is overidentified ($m > \\ell$).\n\n\n\nThe intuition is straightforward. With one instrument for one endogenous regressor, there is only **one** IV estimate of $\\beta_1$, so its consistency with other instruments cannot be assessed. With multiple instruments, each instrument used separately would produce its own IV estimate. If all instruments are valid, these estimates should differ only because of sampling variation, since they estimate the same parameter. If one instrument is endogenous, its estimate may differ systematically from the others.\n\n\n\n**Hypotheses:**\n\n- $H_0$: all instruments are exogenous, $cor(Z_{li}, u_i) = 0$ for $l = 1, \\dots, m$.\n- $H_1$: at least one instrument is endogenous.\n\n\n**Procedure** (the Sargan test, valid under homoskedasticity):\n\n1. Estimate the TSLS model with all instruments and obtain the **second-stage residuals**\n$$\n\\hat{u}_i = Y_i - \\hat{\\beta}_0 - \\hat{\\beta}_1 X_i - \\hat{\\delta}_1 W_{1i} - \\dots - \\hat{\\delta}_k W_{ki}\n$$\n\n\n**Important:** compute the residuals using observed $X_i$, not the first-stage fitted value $\\hat{X}_i$. The `resid()` function in `fixest` does this correctly.\n\n\n2. Use OLS to regress $\\hat{u}_i$ on **all** instruments $Z_{1i}, \\dots, Z_{mi}$ and **all** included exogenous variables $W_{1i}, \\dots, W_{ki}$.\n\n\n\n3. Conduct a joint $F$ test on the coefficients of the instruments alone: $H_0:\\ \\pi_1 = \\dots = \\pi_m = 0$.\n\n4. Calculate $J = m \\cdot F$.\n\n\n5. Under $H_0$, asymptotically $J \\sim \\chi^2_{m-\\ell}$, with degrees of freedom equal to the **degree of overidentification** $m - \\ell$ ($\\ell$ is the number of endogenous regressors).\n\n::: {.callout-warning title=\"Warning about the degrees of freedom\"}\nA common error when using the $J$ test is to treat $J$ as a $\\chi^2$ random variable with $m$ degrees of freedom—the number of restrictions imposed in step 3. This is **incorrect**: the appropriate degrees of freedom are $m - \\ell$, because $\\ell$ moment conditions have already been used to estimate $\\beta_1$ and the $\\delta_j$. In the exactly identified case, $m = \\ell$, and there are no overidentifying restrictions to test.\n\n:::\n\n\n**Manual calculation** (in the Card application, $m = 2$ and $\\ell = 1$, so under $H_0$, $J \\sim \\chi^2_1$):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(car)\ncard <- card |> mutate(uhat = resid(iv_card_overid))\n\nJreg_card <- feols(uhat ~ exper + expersq + black + smsa + south + nearc4 + nearc2,\n                   data = card, vcov = \"iid\")\nlh <- linearHypothesis(Jreg_card, c(\"nearc4 = 0\", \"nearc2 = 0\"))\nlh\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Linear hypothesis test:\n#> nearc4 = 0\n#> nearc2 = 0\n#> \n#> Model 1: restricted model\n#> Model 2: uhat ~ exper + expersq + black + smsa + south + nearc4 + nearc2\n#> \n#>   Res.Df Df  Chisq Pr(>Chisq)\n#> 1   3004                     \n#> 2   3002  2 2.6461     0.2663\n```\n\n\n:::\n:::\n\n\n`linearHypothesis` reports a $\\chi^2$ statistic with $m = 2$ degrees of freedom: the statistic equals $J$, but the $p$-value uses the wrong degrees of freedom. We correct it as follows:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npchisq(2.6461, df = 1, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.1038043\n```\n\n\n:::\n:::\n\n\n\nThe 5% critical value from a $\\chi^2$ distribution with one degree of freedom ($q=1$) is therefore **3.84**. Because $J$ is below this threshold, we **do not reject** the null hypothesis that both instruments are exogenous.\n\n\n**Verification using `fitstat` from `fixest`** (which uses the correct degrees of freedom):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfitstat(iv_card_overid, type = c(\"sargan\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Sargan: stat = 2.6508, p = 0.103497, on 1 DoF.\n```\n\n\n:::\n:::\n\n\nThe two approaches agree: $J \\approx 2.65$, $p \\approx 0.10$.\n\n::: {.callout-important title=\"Asymmetry of the test\"}\n- **Rejection** indicates that at least one instrument is endogenous, **but does not identify which one**: the statistic combines information from all instruments.\n- **Failure to reject** does not establish that the instruments are valid. If all instruments were endogenous in the same way, producing similarly biased estimates, the test might not detect the problem.\n\nThe $J$ test is a useful diagnostic, but it **does not replace the economic argument** for instrument exogeneity.\n:::\n\n\n## Weak instruments\n\nIn its simplest form, the IV estimator is $\\hat{\\beta}_1^{IV} = s_{YZ}/s_{XZ}$. The denominator is the sample covariance between the instrument and the endogenous regressor. If the instrument is relevant but **weakly relevant**—$\\text{Cov}(X_i, Z_i)$ is nonzero but small—the denominator is small and estimated with sampling error.\n\n\nWith weak instruments, the **normal approximation** to the TSLS estimator may fail even in large samples. The estimator can be biased toward OLS—the very bias IV is intended to address. Conventional confidence intervals and hypothesis tests are therefore **unreliable**.\n\n\n**Test of instrument relevance.** Estimate the first stage (regress $X_i$ on all instruments $Z_{1i}, \\dots, Z_{mi}$ and all included exogenous variables) and test the **joint** null hypothesis that the coefficients on the instruments are all zero:\n\n$$\nH_0:\\ \\pi_1 = \\pi_2 = \\dots = \\pi_m = 0\n$$\n\nUse an $F$ statistic. For one endogenous regressor, the most common rule of thumb is straightforward: if $F > 10$, the instruments are considered sufficiently strong; if $F < 10$, weak instruments are a serious concern and the IV estimate must be treated with considerable caution.\n\n\n> **Note—the “$F > 10$” rule.** [Montiel Olea & Pflueger (2013)](https://joseluismontielolea.com/Montiel-OleaJBES.pdf) propose an *effective F-statistic* robust to heteroskedasticity and autocorrelation, together with critical values calibrated to the worst-case bias relative to OLS that a researcher is willing to tolerate (for example, 10%, 20%, or 30%). Their critical values are higher than 10. For the remainder of the course, we use the conventional rule of thumb $F > 10$ as an intuitive benchmark. [Andrews (2019)](https://www.annualreviews.org/content/journals/10.1146/annurev-economics-080218-025643) reviews the weak-instruments problem in the econometrics literature.\n\n\n\n**Important:** In terms of the equivalent Wald statistic (a chi-squared statistic with $m$ degrees of freedom), the threshold is $Wald > m \\times 10$.\n\n\n**One instrument ($nearc4$):**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfs_card_ctrl <- feols(educ ~ nearc4 + exper + expersq + black + smsa + south, data = card, vcov = \"hetero\")\n\nlinearHypothesis(fs_card_ctrl, \"nearc4=0\", test=\"F\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Linear hypothesis test:\n#> nearc4 = 0\n#> \n#> Model 1: restricted model\n#> Model 2: educ ~ nearc4 + exper + expersq + black + smsa + south\n#> \n#>   Res.Df Df      F    Pr(>F)    \n#> 1   3004                        \n#> 2   3003  1 17.513 2.935e-05 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe statistic $F \\approx 17.5$ exceeds the threshold of 10, so $nearc4$ is sufficiently relevant to identify $\\beta_1$.\n\n\n\n\nUsing the $\\chi^2$ statistic rather than $F$, the rule becomes $Wald > m \\times 10 = 1 \\times 10 = 10$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlinearHypothesis(fs_card_ctrl, \"nearc4=0\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Linear hypothesis test:\n#> nearc4 = 0\n#> \n#> Model 1: restricted model\n#> Model 2: educ ~ nearc4 + exper + expersq + black + smsa + south\n#> \n#>   Res.Df Df  Chisq Pr(>Chisq)    \n#> 1   3004                         \n#> 2   3003  1 17.513  2.853e-05 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n**Two-instrument case ($nearc4$ and $nearc2$):**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfs_card_overid <- feols(educ ~ nearc4 + nearc2 + exper + expersq + black + smsa + south, data = card, vcov = \"hetero\")\n\nlinearHypothesis(fs_card_overid, c(\"nearc4=0\", \"nearc2=0\"), test=\"F\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Linear hypothesis test:\n#> nearc4 = 0\n#> nearc2 = 0\n#> \n#> Model 1: restricted model\n#> Model 2: educ ~ nearc4 + nearc2 + exper + expersq + black + smsa + south\n#> \n#>   Res.Df Df      F    Pr(>F)    \n#> 1   3004                        \n#> 2   3002  2 9.7168 6.218e-05 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nHere $F \\approx 9.7$, **just below the threshold of 10**. After adding $nearc2$, the joint first-stage statistic is close to the threshold: the potential precision gain discussed in the overidentification section comes with relatively limited additional explanatory power for $educ$ from each instrument.\n\n\nVerification using `fitstat` from `fixest`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfitstat(iv_card_overid, type = c(\"ivwald\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Wald (1st stage), educ: stat = 9.7168, p = 6.218e-5, on 2 and 3,002 DoF, VCOV: Heteroskedasticity-robust.\n```\n\n\n:::\n:::\n\n\n\n\nUsing the $\\chi^2$ distribution, the rule becomes $Wald > m \\times 10$ (with $m=2$ instruments, the threshold is 20). Here the Wald statistic is 19.4, just below 20.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlinearHypothesis(fs_card_overid, c(\"nearc4=0\", \"nearc2=0\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Linear hypothesis test:\n#> nearc4 = 0\n#> nearc2 = 0\n#> \n#> Model 1: restricted model\n#> Model 2: educ ~ nearc4 + nearc2 + exper + expersq + black + smsa + south\n#> \n#>   Res.Df Df  Chisq Pr(>Chisq)    \n#> 1   3004                         \n#> 2   3002  2 19.433  6.026e-05 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}