{
  "hash": "5ed5141da30c353403820c1c4f2ded10",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tutorial 2\"\nsubtitle: \"Multiple Regression\"\nauthor: \"Andrea Recine\"\ndate: today\nlang: en\ndescription: \"Multiple regression: partialling out, dummy variables, and joint hypothesis tests (wage1).\"\ncode-links:\n  - text: R Script\n    icon: file-code\n    href: tutorial2_script.R\n---\n\n## Multiple Regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(knitr)\nlibrary(tinytable)\nlibrary(modelsummary)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(wooldridge)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"wage1\", package = \"wooldridge\")\n```\n:::\n\n\n\nMultiple regression explicitly allows us to control for other variables that affect the dependent variable and may be correlated with the regressor.\n\n**Idea**: By including the relevant variables in the model, and therefore removing them from the error term, we make it more plausible that the remaining factors in the error term are not correlated with the model variables.\n\nIn the previous [Tutorial](../tutorial1/tutorial1.qmd), we estimated the following simple regression model:\n\n$$\nwage_i = \\beta_0 + \\beta_1 educ_i + u_i\n$$\n\nwhere $wage$ is measured in dollars per hour (in 1976 dollars) and $educ$ is years of education.\n\n\nWe now estimate two additional models:\n\n1. we add $exper$ which represents years of experience in the labor market\n\n2. in addition to $educ$ and $exper$, we add $tenure$, which represents the number of years with the current employer.\n\nTherefore:\n\n$$\nwage_i = \\beta_0 + \\beta_1 educ_i + \\beta_2 exper_i + u_i\n$$\n$$\nwage_i = \\beta_0 + \\beta_1 educ_i + \\beta_2 exper_i + \\beta_3 tenure_i + u_i\n$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Regression\nlibrary(fixest)\nreg_wage1 <- feols(wage ~ educ, data = wage1, vcov = \"hetero\")\nreg_wage2 <- feols(wage ~ educ + exper, data = wage1, vcov = \"hetero\")\nreg_wage3 <- feols(wage ~ educ + exper + tenure, data = wage1, vcov = \"hetero\")\n```\n:::\n\n\n\n::: {.cell tbl-cap='OLS estimation results. Dependent variable $:$ wage'}\n\n```{.r .cell-code}\nmodelsummary(list(\"Wage\" = reg_wage1, \"Wage\" = reg_wage2, \"Wage\" = reg_wage3), gof_omit = \"AIC|BIC|RMSE\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_3bwn2cz8x9nplfrx96lk = TinyTable.createTableFunctions(\"tinytable_3bwn2cz8x9nplfrx96lk\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '11', j: 2 }, { i: '11', j: 3 }, { i: '11', j: 4 } ], css_id: 'tinytable_css_a4tay4c3ey4bqm6ws749',}, \n          { positions: [ { i: '8', j: 2 }, { i: '8', j: 3 }, { i: '8', j: 4 } ], css_id: 'tinytable_css_xkw72zrbdgj1o532f2nw',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '3', j: 4 }, { i: '4', j: 4 }, { i: '5', j: 4 }, { i: '6', j: 4 }, { i: '7', j: 4 }, { i: '9', j: 4 }, { i: '10', j: 4 } ], css_id: 'tinytable_css_ui38oiujjebr2l2cvms5',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 } ], css_id: 'tinytable_css_qrz1jj7u4n7cgfgwf6y5',}, \n          { positions: [ { i: '11', j: 1 } ], css_id: 'tinytable_css_fltt5bwecva9bd0ay9lp',}, \n          { positions: [ { i: '8', j: 1 } ], css_id: 'tinytable_css_akoofixdkfirzlysi7mx',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 } ], css_id: 'tinytable_css_yj4bn66qy4ste3m28et7',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_hhzl7t9udy1oe6hywl9y',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_3bwn2cz8x9nplfrx96lk.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_3bwn2cz8x9nplfrx96lk td.tinytable_css_a4tay4c3ey4bqm6ws749, #tinytable_3bwn2cz8x9nplfrx96lk th.tinytable_css_a4tay4c3ey4bqm6ws749 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_3bwn2cz8x9nplfrx96lk td.tinytable_css_xkw72zrbdgj1o532f2nw, #tinytable_3bwn2cz8x9nplfrx96lk th.tinytable_css_xkw72zrbdgj1o532f2nw {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_3bwn2cz8x9nplfrx96lk td.tinytable_css_ui38oiujjebr2l2cvms5, #tinytable_3bwn2cz8x9nplfrx96lk th.tinytable_css_ui38oiujjebr2l2cvms5 { text-align: center }\n    #tinytable_3bwn2cz8x9nplfrx96lk td.tinytable_css_qrz1jj7u4n7cgfgwf6y5, #tinytable_3bwn2cz8x9nplfrx96lk th.tinytable_css_qrz1jj7u4n7cgfgwf6y5 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_3bwn2cz8x9nplfrx96lk td.tinytable_css_fltt5bwecva9bd0ay9lp, #tinytable_3bwn2cz8x9nplfrx96lk th.tinytable_css_fltt5bwecva9bd0ay9lp {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_3bwn2cz8x9nplfrx96lk td.tinytable_css_akoofixdkfirzlysi7mx, #tinytable_3bwn2cz8x9nplfrx96lk th.tinytable_css_akoofixdkfirzlysi7mx {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_3bwn2cz8x9nplfrx96lk td.tinytable_css_yj4bn66qy4ste3m28et7, #tinytable_3bwn2cz8x9nplfrx96lk th.tinytable_css_yj4bn66qy4ste3m28et7 { text-align: left }\n    #tinytable_3bwn2cz8x9nplfrx96lk td.tinytable_css_hhzl7t9udy1oe6hywl9y, #tinytable_3bwn2cz8x9nplfrx96lk th.tinytable_css_hhzl7t9udy1oe6hywl9y {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_3bwn2cz8x9nplfrx96lk\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Wage</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Wage </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Wage  </th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">-0.905</td>\n                  <td data-row=\"1\" data-col=\"3\">-3.391</td>\n                  <td data-row=\"1\" data-col=\"4\">-2.873</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.725)</td>\n                  <td data-row=\"2\" data-col=\"3\">(0.865)</td>\n                  <td data-row=\"2\" data-col=\"4\">(0.807)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">educ</td>\n                  <td data-row=\"3\" data-col=\"2\">0.541</td>\n                  <td data-row=\"3\" data-col=\"3\">0.644</td>\n                  <td data-row=\"3\" data-col=\"4\">0.599</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.061)</td>\n                  <td data-row=\"4\" data-col=\"3\">(0.065)</td>\n                  <td data-row=\"4\" data-col=\"4\">(0.061)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">exper</td>\n                  <td data-row=\"5\" data-col=\"2\"></td>\n                  <td data-row=\"5\" data-col=\"3\">0.070</td>\n                  <td data-row=\"5\" data-col=\"4\">0.022</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\"></td>\n                  <td data-row=\"6\" data-col=\"3\">(0.011)</td>\n                  <td data-row=\"6\" data-col=\"4\">(0.011)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">tenure</td>\n                  <td data-row=\"7\" data-col=\"2\"></td>\n                  <td data-row=\"7\" data-col=\"3\"></td>\n                  <td data-row=\"7\" data-col=\"4\">0.169</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\"></td>\n                  <td data-row=\"8\" data-col=\"3\"></td>\n                  <td data-row=\"8\" data-col=\"4\">(0.029)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"9\" data-col=\"2\">526</td>\n                  <td data-row=\"9\" data-col=\"3\">526</td>\n                  <td data-row=\"9\" data-col=\"4\">526</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\">R2</td>\n                  <td data-row=\"10\" data-col=\"2\">0.165</td>\n                  <td data-row=\"10\" data-col=\"3\">0.225</td>\n                  <td data-row=\"10\" data-col=\"4\">0.306</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">R2 Adj.</td>\n                  <td data-row=\"11\" data-col=\"2\">0.163</td>\n                  <td data-row=\"11\" data-col=\"3\">0.222</td>\n                  <td data-row=\"11\" data-col=\"4\">0.302</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n**Interpretation of the coefficients**: When interpreting coefficients, we consider the effect of one variable holding all other variables constant.\n\n\nWe are still interested in the effect of $educ$ on $wage$, holding the other factors fixed.\n\n\n**Second column**: An additional year of education is associated, on average, with a 0.64 dollar increase in hourly wage, holding years of labor-market experience constant. Individuals with more years of education tend to enter the labor market later and therefore, holding age constant, have less work experience. This explains why $educ$ and $exper$ are negatively correlated.\n\n\n\n::: {.callout-note collapse=\"false\"}\n## Correlation Between $educ$ and $exper$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(wage1$educ, wage1$exper)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.2995418\n```\n\n\n:::\n:::\n\n\n\nThe omitted-variable bias in the simple model `reg_wage1` depends on two factors: the effect of $exper$ on $wage$ and the correlation between $exper$ and $educ$. If both differ from zero, the bias differs from zero.\n\nThe effect of $exper$ on $wage$ is positive: more experience is associated with higher wages. The covariance, and therefore the correlation, between $educ$ and $exper$ is negative ($Cov(educ, exper) < 0$): individuals with more years of education tend to have less experience.\n\nThe bias in the coefficient on $educ$ is therefore **negative**: the simple model **underestimates** the effect of education on wage.\n\n\n:::\n\n\nAlternatively, we may be interested in the effect of experience on hourly wage, holding years of education constant. An additional year of labor-market experience ($exper$) is associated, on average, with a 0.070 dollar increase in hourly wage, holding years of education constant.\n\n\nIn this case, the key assumption (zero conditional mean) is $E(u_i | educ_i, exper_i) = 0$.\n\n---\n\n**Third model**: An additional year of education is associated, on average, with a 0.59 dollar increase in hourly wage, holding years of labor-market experience and years with the same employer ($tenure$) constant.\n\n\nThe key assumption (zero conditional mean) is $E(u_i | educ_i, exper_i, tenure_i) = 0$.\n\n\n::: {.callout-note collapse=\"true\"}\n## Partialling Out (Frisch-Waugh-Lovell Theorem)\n\nHow do we obtain the coefficient on `educ` in a multiple regression? The Frisch-Waugh-Lovell theorem shows that it is equivalent to the following procedure:\n\n1. Regress `wage` on the other variables (`exper`, `tenure`)\n   and compute the residuals: the part of wage *not* explained\n   by experience and tenure.\n2. Regress `educ` on the same variables and compute the residuals:\n   the part of education *not* explained by experience and tenure.\n3. Regress the residuals from step 1 on the residuals from step 2:\n   the coefficient obtained is exactly $\\hat{\\beta}_{educ}$\n   from the multiple regression.\n\nIn other words, the coefficient on `educ` captures the association\nbetween wage and education after removing the effects of the\nother variables, hence the term \"partialling out.\"\n:::\n\n\n### Including a dummy variable:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Regression\nreg_wage4 <- feols(wage ~ educ + exper + tenure + female, data = wage1, vcov = \"hetero\")\nmodelsummary(list(\"Wage\" = reg_wage3, \"Wage\" = reg_wage4), gof_omit = \"AIC|BIC|RMSE\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_nskw6289didt76xakwv3 = TinyTable.createTableFunctions(\"tinytable_nskw6289didt76xakwv3\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '13', j: 2 }, { i: '13', j: 3 } ], css_id: 'tinytable_css_ssx6fxxowp219ek57wpe',}, \n          { positions: [ { i: '10', j: 2 }, { i: '10', j: 3 } ], css_id: 'tinytable_css_h5g2ujgn3iwmn7xpejxq',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 } ], css_id: 'tinytable_css_90rmz5bsskb9gfrjuspq',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_s2hj1arsd2bgdyuogojk',}, \n          { positions: [ { i: '13', j: 1 } ], css_id: 'tinytable_css_2hbwwdi7t34wjggvvw37',}, \n          { positions: [ { i: '10', j: 1 } ], css_id: 'tinytable_css_yksw7spm9rtrtoznc5sx',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 } ], css_id: 'tinytable_css_n58vfwt36zbi8g6u5eq2',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_mzctw3xezxrqqhnn8cwu',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_nskw6289didt76xakwv3.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_nskw6289didt76xakwv3 td.tinytable_css_ssx6fxxowp219ek57wpe, #tinytable_nskw6289didt76xakwv3 th.tinytable_css_ssx6fxxowp219ek57wpe {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_nskw6289didt76xakwv3 td.tinytable_css_h5g2ujgn3iwmn7xpejxq, #tinytable_nskw6289didt76xakwv3 th.tinytable_css_h5g2ujgn3iwmn7xpejxq {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_nskw6289didt76xakwv3 td.tinytable_css_90rmz5bsskb9gfrjuspq, #tinytable_nskw6289didt76xakwv3 th.tinytable_css_90rmz5bsskb9gfrjuspq { text-align: center }\n    #tinytable_nskw6289didt76xakwv3 td.tinytable_css_s2hj1arsd2bgdyuogojk, #tinytable_nskw6289didt76xakwv3 th.tinytable_css_s2hj1arsd2bgdyuogojk {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_nskw6289didt76xakwv3 td.tinytable_css_2hbwwdi7t34wjggvvw37, #tinytable_nskw6289didt76xakwv3 th.tinytable_css_2hbwwdi7t34wjggvvw37 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_nskw6289didt76xakwv3 td.tinytable_css_yksw7spm9rtrtoznc5sx, #tinytable_nskw6289didt76xakwv3 th.tinytable_css_yksw7spm9rtrtoznc5sx {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_nskw6289didt76xakwv3 td.tinytable_css_n58vfwt36zbi8g6u5eq2, #tinytable_nskw6289didt76xakwv3 th.tinytable_css_n58vfwt36zbi8g6u5eq2 { text-align: left }\n    #tinytable_nskw6289didt76xakwv3 td.tinytable_css_mzctw3xezxrqqhnn8cwu, #tinytable_nskw6289didt76xakwv3 th.tinytable_css_mzctw3xezxrqqhnn8cwu {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_nskw6289didt76xakwv3\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Wage</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Wage </th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">-2.873</td>\n                  <td data-row=\"1\" data-col=\"3\">-1.568</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.807)</td>\n                  <td data-row=\"2\" data-col=\"3\">(0.826)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">educ</td>\n                  <td data-row=\"3\" data-col=\"2\">0.599</td>\n                  <td data-row=\"3\" data-col=\"3\">0.572</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.061)</td>\n                  <td data-row=\"4\" data-col=\"3\">(0.061)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">exper</td>\n                  <td data-row=\"5\" data-col=\"2\">0.022</td>\n                  <td data-row=\"5\" data-col=\"3\">0.025</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.011)</td>\n                  <td data-row=\"6\" data-col=\"3\">(0.010)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">tenure</td>\n                  <td data-row=\"7\" data-col=\"2\">0.169</td>\n                  <td data-row=\"7\" data-col=\"3\">0.141</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\">(0.029)</td>\n                  <td data-row=\"8\" data-col=\"3\">(0.028)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">female</td>\n                  <td data-row=\"9\" data-col=\"2\"></td>\n                  <td data-row=\"9\" data-col=\"3\">-1.811</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\"></td>\n                  <td data-row=\"10\" data-col=\"3\">(0.254)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"11\" data-col=\"2\">526</td>\n                  <td data-row=\"11\" data-col=\"3\">526</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\">R2</td>\n                  <td data-row=\"12\" data-col=\"2\">0.306</td>\n                  <td data-row=\"12\" data-col=\"3\">0.364</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">R2 Adj.</td>\n                  <td data-row=\"13\" data-col=\"2\">0.302</td>\n                  <td data-row=\"13\" data-col=\"3\">0.359</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nIn this regression, we are also controlling for gender (dummy variable $female$).\n\n\nIf $E(u_i | educ_i, exper_i, tenure_i, female_i) = 0$, then $\\beta_1$ represents the causal effect of an additional year of education on hourly wage, **holding experience, years with the same employer, and gender constant**.\n\n\n---\n\n### Changing units of measurement:\n\nSuppose wage is expressed on a monthly basis for full-time workers who work 7 hours per day, 5 days per week, and 4 weeks per month. This gives $7 \\times 5 \\times 4 = 140$ hours per month.\n\nWe create a new variable wage_monthly = $wage$ $\\times$ 140\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwage1 <- wage1 %>%\n  mutate(wage_monthly = wage*140)\n\n\nreg_wage_dummy3 <- feols(wage_monthly ~ educ + exper + tenure + female, data = wage1, vcov = \"hetero\")\nmodelsummary(list(\"Wage\" = reg_wage4, \"Wage Monthly\" = reg_wage_dummy3), gof_omit = \"AIC|BIC|RMSE\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_qxminatojzy6tln1oqtz = TinyTable.createTableFunctions(\"tinytable_qxminatojzy6tln1oqtz\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '13', j: 2 }, { i: '13', j: 3 } ], css_id: 'tinytable_css_j7htn518gzq2fcfz58qz',}, \n          { positions: [ { i: '10', j: 2 }, { i: '10', j: 3 } ], css_id: 'tinytable_css_xmrlpmygqkjob95o57ci',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 } ], css_id: 'tinytable_css_puzcwreg4emziukz2w38',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_ju0z97oc2sajwohmkc87',}, \n          { positions: [ { i: '13', j: 1 } ], css_id: 'tinytable_css_dt6q5ubc7hpj7phkvy7q',}, \n          { positions: [ { i: '10', j: 1 } ], css_id: 'tinytable_css_4nou26rmdmehgwmozxfx',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 } ], css_id: 'tinytable_css_9l7l4jd2urwxlfhgpz0a',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_3ltqyctw8ozdljuiv5vt',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_qxminatojzy6tln1oqtz.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_qxminatojzy6tln1oqtz td.tinytable_css_j7htn518gzq2fcfz58qz, #tinytable_qxminatojzy6tln1oqtz th.tinytable_css_j7htn518gzq2fcfz58qz {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_qxminatojzy6tln1oqtz td.tinytable_css_xmrlpmygqkjob95o57ci, #tinytable_qxminatojzy6tln1oqtz th.tinytable_css_xmrlpmygqkjob95o57ci {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_qxminatojzy6tln1oqtz td.tinytable_css_puzcwreg4emziukz2w38, #tinytable_qxminatojzy6tln1oqtz th.tinytable_css_puzcwreg4emziukz2w38 { text-align: center }\n    #tinytable_qxminatojzy6tln1oqtz td.tinytable_css_ju0z97oc2sajwohmkc87, #tinytable_qxminatojzy6tln1oqtz th.tinytable_css_ju0z97oc2sajwohmkc87 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_qxminatojzy6tln1oqtz td.tinytable_css_dt6q5ubc7hpj7phkvy7q, #tinytable_qxminatojzy6tln1oqtz th.tinytable_css_dt6q5ubc7hpj7phkvy7q {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_qxminatojzy6tln1oqtz td.tinytable_css_4nou26rmdmehgwmozxfx, #tinytable_qxminatojzy6tln1oqtz th.tinytable_css_4nou26rmdmehgwmozxfx {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_qxminatojzy6tln1oqtz td.tinytable_css_9l7l4jd2urwxlfhgpz0a, #tinytable_qxminatojzy6tln1oqtz th.tinytable_css_9l7l4jd2urwxlfhgpz0a { text-align: left }\n    #tinytable_qxminatojzy6tln1oqtz td.tinytable_css_3ltqyctw8ozdljuiv5vt, #tinytable_qxminatojzy6tln1oqtz th.tinytable_css_3ltqyctw8ozdljuiv5vt {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_qxminatojzy6tln1oqtz\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Wage</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Wage Monthly</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">-1.568</td>\n                  <td data-row=\"1\" data-col=\"3\">-219.511</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.826)</td>\n                  <td data-row=\"2\" data-col=\"3\">(115.631)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">educ</td>\n                  <td data-row=\"3\" data-col=\"2\">0.572</td>\n                  <td data-row=\"3\" data-col=\"3\">80.011</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.061)</td>\n                  <td data-row=\"4\" data-col=\"3\">(8.570)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">exper</td>\n                  <td data-row=\"5\" data-col=\"2\">0.025</td>\n                  <td data-row=\"5\" data-col=\"3\">3.555</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.010)</td>\n                  <td data-row=\"6\" data-col=\"3\">(1.373)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">tenure</td>\n                  <td data-row=\"7\" data-col=\"2\">0.141</td>\n                  <td data-row=\"7\" data-col=\"3\">19.741</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\">(0.028)</td>\n                  <td data-row=\"8\" data-col=\"3\">(3.914)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">female</td>\n                  <td data-row=\"9\" data-col=\"2\">-1.811</td>\n                  <td data-row=\"9\" data-col=\"3\">-253.519</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\">(0.254)</td>\n                  <td data-row=\"10\" data-col=\"3\">(35.582)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"11\" data-col=\"2\">526</td>\n                  <td data-row=\"11\" data-col=\"3\">526</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\">R2</td>\n                  <td data-row=\"12\" data-col=\"2\">0.364</td>\n                  <td data-row=\"12\" data-col=\"3\">0.364</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">R2 Adj.</td>\n                  <td data-row=\"13\" data-col=\"2\">0.359</td>\n                  <td data-row=\"13\" data-col=\"3\">0.359</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n**Hourly wage**: An additional year of education is associated, on average, with a 0.572 dollar increase in hourly wage, holding gender, experience, and $tenure$ constant.\n\n\n**Monthly wage**: An additional year of education is associated, on average, with an 80 dollar increase in monthly wage, holding gender, experience, and $tenure$ constant.\n\n\nWhat if $educ$ were measured in months of education?\n\nIn [Tutorial 1](../tutorial1/tutorial1.qmd), we saw that expressing $educ$ in months by multiplying it by 12 leaves the intercept unchanged and divides the coefficient on $educ$ by 12.\n\n\nThe coefficient on education measured in months will equal 0.048 dollars ($\\frac{0.572}{12}$). An additional month of education is associated, on average, with a 0.048 dollar increase in hourly wage, holding gender, experience, and $tenure$ constant. The remaining coefficients, including the intercept and the dummy-variable coefficient, remain unchanged.\n\n\n\n---\n\n## Dummy Variable: Wage and Gender:\n\nIn [Tutorial 1](../tutorial1/tutorial1.qmd), we estimated the following regression:\n\n$$\nwage_i = \\beta_0 + \\beta_1 female_i + u_i,\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg_wage_dummy <- feols(wage ~ female, data = wage1, vcov = \"hetero\")\nreg_wage_dummy2 <- feols(wage ~ female + educ + exper + tenure, data = wage1, vcov = \"hetero\")\nmodelsummary(list(\"Wage (Tutorial 1)\" = reg_wage_dummy, \"Wage\" = reg_wage_dummy2), gof_omit = \"AIC|BIC|RMSE\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_3tajafxpfop4b4inhu4u = TinyTable.createTableFunctions(\"tinytable_3tajafxpfop4b4inhu4u\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '13', j: 2 }, { i: '13', j: 3 } ], css_id: 'tinytable_css_urg1k1lip8y5c24bt033',}, \n          { positions: [ { i: '10', j: 2 }, { i: '10', j: 3 } ], css_id: 'tinytable_css_nbbyz37xio4mvceedzew',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 } ], css_id: 'tinytable_css_buvg5kbwfgnatoj7zbo0',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_7z40liwtdt7ld2zdtila',}, \n          { positions: [ { i: '13', j: 1 } ], css_id: 'tinytable_css_rtla7qefh0uhgzgtivjh',}, \n          { positions: [ { i: '10', j: 1 } ], css_id: 'tinytable_css_1ey5efa2jw2qjr6faf40',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 } ], css_id: 'tinytable_css_5dgiv2p512tl78lccfsw',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_auaz8zn96po1gy6t7jee',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_3tajafxpfop4b4inhu4u.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_3tajafxpfop4b4inhu4u td.tinytable_css_urg1k1lip8y5c24bt033, #tinytable_3tajafxpfop4b4inhu4u th.tinytable_css_urg1k1lip8y5c24bt033 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_3tajafxpfop4b4inhu4u td.tinytable_css_nbbyz37xio4mvceedzew, #tinytable_3tajafxpfop4b4inhu4u th.tinytable_css_nbbyz37xio4mvceedzew {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_3tajafxpfop4b4inhu4u td.tinytable_css_buvg5kbwfgnatoj7zbo0, #tinytable_3tajafxpfop4b4inhu4u th.tinytable_css_buvg5kbwfgnatoj7zbo0 { text-align: center }\n    #tinytable_3tajafxpfop4b4inhu4u td.tinytable_css_7z40liwtdt7ld2zdtila, #tinytable_3tajafxpfop4b4inhu4u th.tinytable_css_7z40liwtdt7ld2zdtila {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_3tajafxpfop4b4inhu4u td.tinytable_css_rtla7qefh0uhgzgtivjh, #tinytable_3tajafxpfop4b4inhu4u th.tinytable_css_rtla7qefh0uhgzgtivjh {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_3tajafxpfop4b4inhu4u td.tinytable_css_1ey5efa2jw2qjr6faf40, #tinytable_3tajafxpfop4b4inhu4u th.tinytable_css_1ey5efa2jw2qjr6faf40 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_3tajafxpfop4b4inhu4u td.tinytable_css_5dgiv2p512tl78lccfsw, #tinytable_3tajafxpfop4b4inhu4u th.tinytable_css_5dgiv2p512tl78lccfsw { text-align: left }\n    #tinytable_3tajafxpfop4b4inhu4u td.tinytable_css_auaz8zn96po1gy6t7jee, #tinytable_3tajafxpfop4b4inhu4u th.tinytable_css_auaz8zn96po1gy6t7jee {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_3tajafxpfop4b4inhu4u\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Wage (Tutorial 1)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Wage</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">7.099</td>\n                  <td data-row=\"1\" data-col=\"3\">-1.568</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.251)</td>\n                  <td data-row=\"2\" data-col=\"3\">(0.826)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">female</td>\n                  <td data-row=\"3\" data-col=\"2\">-2.512</td>\n                  <td data-row=\"3\" data-col=\"3\">-1.811</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.298)</td>\n                  <td data-row=\"4\" data-col=\"3\">(0.254)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">educ</td>\n                  <td data-row=\"5\" data-col=\"2\"></td>\n                  <td data-row=\"5\" data-col=\"3\">0.572</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\"></td>\n                  <td data-row=\"6\" data-col=\"3\">(0.061)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">exper</td>\n                  <td data-row=\"7\" data-col=\"2\"></td>\n                  <td data-row=\"7\" data-col=\"3\">0.025</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\"></td>\n                  <td data-row=\"8\" data-col=\"3\">(0.010)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">tenure</td>\n                  <td data-row=\"9\" data-col=\"2\"></td>\n                  <td data-row=\"9\" data-col=\"3\">0.141</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\"></td>\n                  <td data-row=\"10\" data-col=\"3\">(0.028)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"11\" data-col=\"2\">526</td>\n                  <td data-row=\"11\" data-col=\"3\">526</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\">R2</td>\n                  <td data-row=\"12\" data-col=\"2\">0.116</td>\n                  <td data-row=\"12\" data-col=\"3\">0.364</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">R2 Adj.</td>\n                  <td data-row=\"13\" data-col=\"2\">0.114</td>\n                  <td data-row=\"13\" data-col=\"3\">0.359</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nThe results of the first regression show that the average wage of men (represented by the intercept) is about 7.1 dollars (in 1976 dollars) per hour.\n\nThe coefficient on the female dummy variable is -2.51 dollars. On average, women earn about 2.51 dollars less per hour than men. The average hourly wage for women is about 4.58 dollars ($7.1 - 2.51$).\n\n\nIn the second regression, we control for differences in education, experience, and $tenure$.\n\n\nIn this second regression, the negative intercept for men has little practical meaning because no individual in the sample has zero years of $educ$, $exper$, and $tenure$. The coefficient on $female$, however, represents the average difference in hourly wage between a woman and a man, holding $educ$, $exper$, and $tenure$ constant.\n\n\nBecause we control for $educ$, $exper$, and $tenure$, the 1.81 dollar hourly-wage gap cannot be explained by differences in the average levels of education, experience, and tenure between men and women. The 1.81 dollar difference is attributable to gender or to factors associated with gender that are not controlled for in the regression.\n\n---\n\n## Dummy Variables with Multiple Categories\n\n\nWe estimate a model that allows for wage differences across four groups: married men, married women, single men, and single women.\n\nTo interpret the dummy-variable coefficients, we must choose a reference group.\n\nWe then define dummy variables for the other three groups.\n\n**Dummy variables**: We use single men as the omitted category and create the following variables:\n\n- $marrmale$ equals 1 for married men.\n\n- $marrfemale$ equals 1 for married women.\n\n- $singfem$ equals 1 for single (unmarried) women.\n\n- $singmale$ equals 1 for single (unmarried) men. This is our reference group. We create the dummy variable for single men but do not include it in the regression.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwage1 <- wage1 %>%\n  mutate(\n    marrmale = ifelse(female == 0 & married == 1, 1, 0),\n    marrfemale = ifelse(female == 1 & married == 1, 1, 0),\n    singfem = ifelse(female == 1 & married == 0, 1, 0),\n    singmale = ifelse(female == 0 & married == 0, 1, 0)\n  )\n```\n:::\n\n\n\nWhat would happen if we also included $female$? We would obtain perfect collinearity, known as the dummy-variable trap.\n\nWhen several dummy variables must be created, for example for regions, the `fastDummies` package can be useful.\n\n\n::: {.callout-note title=\"Recall\"}\nThe mean of a dummy variable is the proportion of observations equal to 1 in the sample:\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstatdummy <- wage1 %>%\n  summarise(\n    marrmale_mean = mean(marrmale, na.rm = TRUE),\n    marrfemale_mean = mean(marrfemale, na.rm = TRUE),\n    singfem_mean = mean(singfem, na.rm = TRUE),\n    singmale_mean = mean(singmale, na.rm = TRUE)\n  )\n\ntt(statdummy, width = 1, digits = 3, caption = \"Means of the dummy variables\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_ml7tj5cq8iz8giqymvp7 = TinyTable.createTableFunctions(\"tinytable_ml7tj5cq8iz8giqymvp7\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '1', j: 1 }, { i: '1', j: 2 }, { i: '1', j: 3 }, { i: '1', j: 4 } ], css_id: 'tinytable_css_5m4v95hog4utgknsy1wx',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 } ], css_id: 'tinytable_css_e1vqgjos12eo11w4zp9m',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_ml7tj5cq8iz8giqymvp7.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_ml7tj5cq8iz8giqymvp7 td.tinytable_css_5m4v95hog4utgknsy1wx, #tinytable_ml7tj5cq8iz8giqymvp7 th.tinytable_css_5m4v95hog4utgknsy1wx {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_ml7tj5cq8iz8giqymvp7 td.tinytable_css_e1vqgjos12eo11w4zp9m, #tinytable_ml7tj5cq8iz8giqymvp7 th.tinytable_css_e1vqgjos12eo11w4zp9m {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_ml7tj5cq8iz8giqymvp7\" style=\"table-layout: fixed; width: 100% !important; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <caption>Means of the dummy variables</caption>\n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">marrmale_mean</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">marrfemale_mean</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">singfem_mean</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">singmale_mean</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">0.357</td>\n                  <td data-row=\"1\" data-col=\"2\">0.251</td>\n                  <td data-row=\"1\" data-col=\"3\">0.228</td>\n                  <td data-row=\"1\" data-col=\"4\">0.163</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nThe sum $0.357 + 0.251 + 0.228 + 0.163$ equals 1, as expected, because the four dummy variables represent mutually exclusive and collectively exhaustive groups.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg_wage_sm <- feols(wage ~ marrmale + marrfemale + singfem + educ + exper + tenure, data = wage1, vcov = \"hetero\")\nmodelsummary(list(\"Wage\" = reg_wage_sm), gof_omit = \"AIC|BIC|RMSE\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_snxn83zs4xvxdfljtuio = TinyTable.createTableFunctions(\"tinytable_snxn83zs4xvxdfljtuio\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '17', j: 2 } ], css_id: 'tinytable_css_bybscpdw6rb3o5743yvr',}, \n          { positions: [ { i: '14', j: 2 } ], css_id: 'tinytable_css_cmzcegven8w465o9vgsm',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '15', j: 2 }, { i: '16', j: 2 } ], css_id: 'tinytable_css_ggr7c0fftjgxncghglhw',}, \n          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_vqql4s46jc7tf8s2yg6t',}, \n          { positions: [ { i: '17', j: 1 } ], css_id: 'tinytable_css_u4nj3c38cxabwjlh79vj',}, \n          { positions: [ { i: '14', j: 1 } ], css_id: 'tinytable_css_de6myyri3mzb8t2awazk',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 }, { i: '15', j: 1 }, { i: '16', j: 1 } ], css_id: 'tinytable_css_wj16rrulxwkwt96o6cus',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_1ujfc5ioi44av2xasz7c',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_snxn83zs4xvxdfljtuio.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_snxn83zs4xvxdfljtuio td.tinytable_css_bybscpdw6rb3o5743yvr, #tinytable_snxn83zs4xvxdfljtuio th.tinytable_css_bybscpdw6rb3o5743yvr {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_snxn83zs4xvxdfljtuio td.tinytable_css_cmzcegven8w465o9vgsm, #tinytable_snxn83zs4xvxdfljtuio th.tinytable_css_cmzcegven8w465o9vgsm {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_snxn83zs4xvxdfljtuio td.tinytable_css_ggr7c0fftjgxncghglhw, #tinytable_snxn83zs4xvxdfljtuio th.tinytable_css_ggr7c0fftjgxncghglhw { text-align: center }\n    #tinytable_snxn83zs4xvxdfljtuio td.tinytable_css_vqql4s46jc7tf8s2yg6t, #tinytable_snxn83zs4xvxdfljtuio th.tinytable_css_vqql4s46jc7tf8s2yg6t {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_snxn83zs4xvxdfljtuio td.tinytable_css_u4nj3c38cxabwjlh79vj, #tinytable_snxn83zs4xvxdfljtuio th.tinytable_css_u4nj3c38cxabwjlh79vj {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_snxn83zs4xvxdfljtuio td.tinytable_css_de6myyri3mzb8t2awazk, #tinytable_snxn83zs4xvxdfljtuio th.tinytable_css_de6myyri3mzb8t2awazk {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_snxn83zs4xvxdfljtuio td.tinytable_css_wj16rrulxwkwt96o6cus, #tinytable_snxn83zs4xvxdfljtuio th.tinytable_css_wj16rrulxwkwt96o6cus { text-align: left }\n    #tinytable_snxn83zs4xvxdfljtuio td.tinytable_css_1ujfc5ioi44av2xasz7c, #tinytable_snxn83zs4xvxdfljtuio th.tinytable_css_1ujfc5ioi44av2xasz7c {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_snxn83zs4xvxdfljtuio\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Wage</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">-2.394</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.850)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">marrmale</td>\n                  <td data-row=\"3\" data-col=\"2\">1.822</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.376)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">marrfemale</td>\n                  <td data-row=\"5\" data-col=\"2\">-0.882</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.339)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">singfem</td>\n                  <td data-row=\"7\" data-col=\"2\">-0.309</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\">(0.352)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">educ</td>\n                  <td data-row=\"9\" data-col=\"2\">0.553</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\">(0.061)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">exper</td>\n                  <td data-row=\"11\" data-col=\"2\">0.019</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\"></td>\n                  <td data-row=\"12\" data-col=\"2\">(0.010)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">tenure</td>\n                  <td data-row=\"13\" data-col=\"2\">0.130</td>\n                </tr>\n                <tr>\n                  <td data-row=\"14\" data-col=\"1\"></td>\n                  <td data-row=\"14\" data-col=\"2\">(0.027)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"15\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"15\" data-col=\"2\">526</td>\n                </tr>\n                <tr>\n                  <td data-row=\"16\" data-col=\"1\">R2</td>\n                  <td data-row=\"16\" data-col=\"2\">0.392</td>\n                </tr>\n                <tr>\n                  <td data-row=\"17\" data-col=\"1\">R2 Adj.</td>\n                  <td data-row=\"17\" data-col=\"2\">0.385</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n**Interpretation of the coefficients:**\n\n- On average, a married man earns 1.822 dollars more per hour than a single man, holding years of education, years of experience, and years with the current employer ($tenure$) constant.\n\n- On average, a married woman earns 0.882 dollars less per hour than a single man, holding years of education, years of experience, and $tenure$ constant.\n\n- On average, a single woman earns 0.309 dollars less per hour than a single man, holding years of education, years of experience, and $tenure$ constant.\n\n\n::: {.callout-caution title=\"Warning\"}\nAre these coefficients statistically significant at the 5% level? Also compute their confidence intervals.\n:::\n\n\n---\n\n### The Dummy-Variable Trap\n\nAs in Tutorial 1, we create the variable $male$.\n\n::: {.cell}\n\n```{.r .cell-code}\nwage1 <- wage1 %>%\n  mutate(male = 1 - female)\n```\n:::\n\n\nWe regress $wage$ on $marrmale$, $marrfemale$, $singfem$, $female$, and $male$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg_wage_sm_dummy <- feols(wage ~ marrmale + marrfemale + singfem + female + male, data = wage1, vcov = \"hetero\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe variables 'female' and 'male' have been removed because of collinearity (see\n$collin.var).\n```\n\n\n:::\n\n```{.r .cell-code}\nreg_wage_sm_dummy\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS estimation, Dep. Var.: wage\nObservations: 526\nStandard-errors: Heteroskedasticity-robust \n             Estimate Std. Error  t value   Pr(>|t|)    \n(Intercept)  5.168023   0.293016 17.63733  < 2.2e-16 ***\nmarrmale     2.815009   0.435098  6.46982 2.2614e-10 ***\nmarrfemale  -0.602114   0.341999 -1.76057 7.8896e-02 .  \nsingfem     -0.556440   0.400727 -1.38858 1.6555e-01    \n... 2 variables were removed because of collinearity (female and male)\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 3.33904   Adj. R2: 0.17628\n```\n\n\n:::\n:::\n\n\n::: {.callout-important title=\"Warning\"}\n$female$ and $male$ are perfectly collinear.\n\nThis is because:\n\n- $female$ = $marrfemale$ + $singfem$\n\n- $male$ = $marrmale$ + $singmale$ (where single men are the omitted **reference group**).\n\n\nThe variable $male$ identifies all men and is the sum of married men (captured by $marrmale$) and single men (the reference category, which is not included in the regression).\n\nR automatically removes the perfectly collinear variables.\n:::\n\n\n---\n\n\n### Dummy Variables for Geographic Regions\n\n\nThe `wage1` dataset divides the United States into four major regions defined by the _US Census Bureau_: **Northeast**, **North Central / Midwest**, **South**, and **West**.\n\n\nThe dataset contains three dummy variables, `northcen`, `south`, and `west`, while the Northeast is the **omitted reference group**.\n\n::: {.callout-note collapse=\"true\"}\n## Historical note\n\nThe Census Bureau renamed the \"North Central\" region \"Midwest\" in 1984. Because the `wage1` dataset is from 1976, it retains the older designation, which explains the variable name `northcen`.\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwage1 |>\n  summarise(\n    n_northcen  = sum(northcen),\n    n_south     = sum(south),\n    n_west      = sum(west),\n    n_northeast = sum(1 - northcen - south - west)\n  ) |>\n  tt(caption = \"Observations by region\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_1cm9q1yig1i0km20s1yy = TinyTable.createTableFunctions(\"tinytable_1cm9q1yig1i0km20s1yy\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '1', j: 1 }, { i: '1', j: 2 }, { i: '1', j: 3 }, { i: '1', j: 4 } ], css_id: 'tinytable_css_k5lojg4es80preitddie',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 } ], css_id: 'tinytable_css_kovp7wwv2oyw4qihzi1o',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_1cm9q1yig1i0km20s1yy.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_1cm9q1yig1i0km20s1yy td.tinytable_css_k5lojg4es80preitddie, #tinytable_1cm9q1yig1i0km20s1yy th.tinytable_css_k5lojg4es80preitddie {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_1cm9q1yig1i0km20s1yy td.tinytable_css_kovp7wwv2oyw4qihzi1o, #tinytable_1cm9q1yig1i0km20s1yy th.tinytable_css_kovp7wwv2oyw4qihzi1o {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_1cm9q1yig1i0km20s1yy\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <caption>Observations by region</caption>\n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">n_northcen</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">n_south</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">n_west</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">n_northeast</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">132</td>\n                  <td data-row=\"1\" data-col=\"2\">187</td>\n                  <td data-row=\"1\" data-col=\"3\">89</td>\n                  <td data-row=\"1\" data-col=\"4\">118</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\nThe sum across these four categories equals the total number of observations, as expected, because the categories are mutually exclusive and exhaustive.\n\nBefore estimating the model, we examine the *unadjusted* wage differences across regions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwage1 |>\n  mutate(\n    region = case_when(\n      northcen == 1 ~ \"North Central\",\n      south    == 1 ~ \"South\",\n      west     == 1 ~ \"West\",\n      TRUE          ~ \"Northeast\"\n    )\n  ) |>\n  group_by(region) |>\n  summarise(\n    n = n(),\n    mean_wage   = mean(wage),\n    median_wage = median(wage),\n    mean_educ   = mean(educ)\n  ) |>\n  arrange(desc(mean_wage)) |>\n  tt(caption = \"Descriptive statistics by region\") |>\n  format_tt(digits = 3) |>\n  theme_tt(\"striped\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: The theme_tt() function is deprecated. Please use format-specific or style-specific theme functions instead:\n\nFormat-specific functions:\n\n* theme_html()\n* theme_latex()\n* theme_typst()\n\nStyle-specific functions:\n\n* theme_grid()\n* theme_revealjs()\n* theme_rotate()\n* theme_striped()\n* theme_empty()\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_ultxhezfo76os7mezwld = TinyTable.createTableFunctions(\"tinytable_ultxhezfo76os7mezwld\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '4', j: 1 }, { i: '4', j: 2 }, { i: '4', j: 3 }, { i: '4', j: 4 }, { i: '4', j: 5 } ], css_id: 'tinytable_css_xsvztx5pv8gsffm22wt3',}, \n          { positions: [ { i: '1', j: 1 }, { i: '3', j: 1 }, { i: '1', j: 2 }, { i: '3', j: 2 }, { i: '1', j: 3 }, { i: '3', j: 3 }, { i: '1', j: 4 }, { i: '3', j: 4 }, { i: '1', j: 5 }, { i: '3', j: 5 } ], css_id: 'tinytable_css_0z2qevoutnw10brjscix',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 } ], css_id: 'tinytable_css_14mflj38hcri52z4yyhy',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_ultxhezfo76os7mezwld.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_ultxhezfo76os7mezwld td.tinytable_css_xsvztx5pv8gsffm22wt3, #tinytable_ultxhezfo76os7mezwld th.tinytable_css_xsvztx5pv8gsffm22wt3 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_ultxhezfo76os7mezwld td.tinytable_css_0z2qevoutnw10brjscix, #tinytable_ultxhezfo76os7mezwld th.tinytable_css_0z2qevoutnw10brjscix { background-color: #ededed }\n    #tinytable_ultxhezfo76os7mezwld td.tinytable_css_14mflj38hcri52z4yyhy, #tinytable_ultxhezfo76os7mezwld th.tinytable_css_14mflj38hcri52z4yyhy {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_ultxhezfo76os7mezwld\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <caption>Descriptive statistics by region</caption>\n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">region</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">n</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">mean_wage</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">median_wage</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">mean_educ</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">West</td>\n                  <td data-row=\"1\" data-col=\"2\">89</td>\n                  <td data-row=\"1\" data-col=\"3\">6.61</td>\n                  <td data-row=\"1\" data-col=\"4\">5.3</td>\n                  <td data-row=\"1\" data-col=\"5\">12.7</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">Northeast</td>\n                  <td data-row=\"2\" data-col=\"2\">118</td>\n                  <td data-row=\"2\" data-col=\"3\">6.37</td>\n                  <td data-row=\"2\" data-col=\"4\">4.93</td>\n                  <td data-row=\"2\" data-col=\"5\">12.8</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">North Central</td>\n                  <td data-row=\"3\" data-col=\"2\">132</td>\n                  <td data-row=\"3\" data-col=\"3\">5.71</td>\n                  <td data-row=\"3\" data-col=\"4\">4.68</td>\n                  <td data-row=\"3\" data-col=\"5\">12.9</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\">South</td>\n                  <td data-row=\"4\" data-col=\"2\">187</td>\n                  <td data-row=\"4\" data-col=\"3\">5.39</td>\n                  <td data-row=\"4\" data-col=\"4\">4.5</td>\n                  <td data-row=\"4\" data-col=\"5\">12.1</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nThese are unadjusted differences. In the multiple regression, we control for education, experience, gender, and tenure to determine whether wage differences across regions remain after holding these characteristics constant.\n\nWe estimate the following regression:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg_region <- feols(\n  wage ~ educ + exper + tenure + female + northcen + south + west,\n  data = wage1, vcov = \"hetero\"\n)\n\nmodelsummary(\n  list(\"Wage\" = reg_region),\n  gof_omit = \"AIC|BIC|RMSE|R2 Adj.\",\n  title = \"Regression with Regional Dummies (Northeast = Reference Group)\"\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_o4ooi7juutxlhij4m4kl = TinyTable.createTableFunctions(\"tinytable_o4ooi7juutxlhij4m4kl\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '18', j: 2 } ], css_id: 'tinytable_css_8nzd45kzh4cu1d6h2uuv',}, \n          { positions: [ { i: '16', j: 2 } ], css_id: 'tinytable_css_gj25d3dglbm9k1k322uu',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '14', j: 2 }, { i: '15', j: 2 }, { i: '17', j: 2 } ], css_id: 'tinytable_css_48q1rnopoz107hd0288t',}, \n          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_qntyecnwzo9pvbii8ogc',}, \n          { positions: [ { i: '18', j: 1 } ], css_id: 'tinytable_css_2p1gwc13q95ml44opbg2',}, \n          { positions: [ { i: '16', j: 1 } ], css_id: 'tinytable_css_fi8wscuiwn57fctk1aca',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 }, { i: '14', j: 1 }, { i: '15', j: 1 }, { i: '17', j: 1 } ], css_id: 'tinytable_css_rnudssdor4kyg98ybbi2',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_ihrvl6xqkccqo4578tb8',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_o4ooi7juutxlhij4m4kl.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_o4ooi7juutxlhij4m4kl td.tinytable_css_8nzd45kzh4cu1d6h2uuv, #tinytable_o4ooi7juutxlhij4m4kl th.tinytable_css_8nzd45kzh4cu1d6h2uuv {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_o4ooi7juutxlhij4m4kl td.tinytable_css_gj25d3dglbm9k1k322uu, #tinytable_o4ooi7juutxlhij4m4kl th.tinytable_css_gj25d3dglbm9k1k322uu {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_o4ooi7juutxlhij4m4kl td.tinytable_css_48q1rnopoz107hd0288t, #tinytable_o4ooi7juutxlhij4m4kl th.tinytable_css_48q1rnopoz107hd0288t { text-align: center }\n    #tinytable_o4ooi7juutxlhij4m4kl td.tinytable_css_qntyecnwzo9pvbii8ogc, #tinytable_o4ooi7juutxlhij4m4kl th.tinytable_css_qntyecnwzo9pvbii8ogc {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_o4ooi7juutxlhij4m4kl td.tinytable_css_2p1gwc13q95ml44opbg2, #tinytable_o4ooi7juutxlhij4m4kl th.tinytable_css_2p1gwc13q95ml44opbg2 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_o4ooi7juutxlhij4m4kl td.tinytable_css_fi8wscuiwn57fctk1aca, #tinytable_o4ooi7juutxlhij4m4kl th.tinytable_css_fi8wscuiwn57fctk1aca {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_o4ooi7juutxlhij4m4kl td.tinytable_css_rnudssdor4kyg98ybbi2, #tinytable_o4ooi7juutxlhij4m4kl th.tinytable_css_rnudssdor4kyg98ybbi2 { text-align: left }\n    #tinytable_o4ooi7juutxlhij4m4kl td.tinytable_css_ihrvl6xqkccqo4578tb8, #tinytable_o4ooi7juutxlhij4m4kl th.tinytable_css_ihrvl6xqkccqo4578tb8 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_o4ooi7juutxlhij4m4kl\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <caption>Regression with Regional Dummies (Northeast = Reference Group)</caption>\n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Wage</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">-1.233</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.837)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">educ</td>\n                  <td data-row=\"3\" data-col=\"2\">0.566</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.061)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">exper</td>\n                  <td data-row=\"5\" data-col=\"2\">0.027</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.010)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">tenure</td>\n                  <td data-row=\"7\" data-col=\"2\">0.139</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\">(0.027)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">female</td>\n                  <td data-row=\"9\" data-col=\"2\">-1.857</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\">(0.256)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">northcen</td>\n                  <td data-row=\"11\" data-col=\"2\">-0.621</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\"></td>\n                  <td data-row=\"12\" data-col=\"2\">(0.389)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">south</td>\n                  <td data-row=\"13\" data-col=\"2\">-0.572</td>\n                </tr>\n                <tr>\n                  <td data-row=\"14\" data-col=\"1\"></td>\n                  <td data-row=\"14\" data-col=\"2\">(0.353)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"15\" data-col=\"1\">west</td>\n                  <td data-row=\"15\" data-col=\"2\">0.571</td>\n                </tr>\n                <tr>\n                  <td data-row=\"16\" data-col=\"1\"></td>\n                  <td data-row=\"16\" data-col=\"2\">(0.461)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"17\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"17\" data-col=\"2\">526</td>\n                </tr>\n                <tr>\n                  <td data-row=\"18\" data-col=\"1\">R2</td>\n                  <td data-row=\"18\" data-col=\"2\">0.378</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n\nEach coefficient on a regional dummy variable is interpreted **relative to the reference group (Northeast)**:\n\n\n- $northcen$: a worker in the North Central region (now called the Midwest) earns, on average, 0.621 dollars **less** per hour than a worker in the Northeast, holding years of education, experience, gender, and $tenure$ constant.\n\n\n- $south$: a worker in the South earns, on average, 0.572 dollars **less** per hour than a worker in the Northeast, holding years of education, experience, gender, and $tenure$ constant.\n\n- $west$: a worker in the West earns, on average, 0.571 dollars **more** per hour than a worker in the Northeast, holding years of education, experience, gender, and $tenure$ constant.\n\n\n\n::: {.callout-important title=\"The Regional Dummy-Variable Trap\"}\nIf we also included a `northeast` dummy variable (constructed as\n`1 - northcen - south - west`), we would obtain **perfect collinearity**,\njust as in the earlier case with `marrmale + marrfemale + singfem + female + male`.\nR would automatically remove one of the four dummy variables.\n\nWith $k$ mutually exclusive and exhaustive categories, the sum of the $k$ dummy variables always equals 1 for every observation. This creates perfect collinearity with the intercept, so we include only $k-1$ dummy variables (or all $k$ dummy variables without an intercept).\n:::\n\n\n\n## Testing Joint Hypotheses\n\nConsider the regression `reg_wage_sm`. We test the null hypothesis that there are no wage differences across the categories after controlling for years of education, experience, and years with the same employer:\n\nThat is:\n$$\nH_0: \\beta_1 = \\beta_2 = \\beta_3 = 0\n$$\n\n\nWe can use the `wald()` function from `fixest`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwald(reg_wage_sm,\n     keep = \"marrmale|marrfemale|singfem\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWald test, H0: joint nullity of marrmale, marrfemale and singfem\n stat = 24.0, p-value = 1.445e-14, on 3 and 519 DoF, VCOV: Heteroskedasticity-robust.\n```\n\n\n:::\n:::\n\n\nMore often, we will use `linearHypothesis()` from the `car` package:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"car\")\nlibrary(car)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: carData\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'car'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:dplyr':\n\n    recode\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:purrr':\n\n    some\n```\n\n\n:::\n\n```{.r .cell-code}\n# Hypothesis test (Wald)\nlinearHypothesis(reg_wage_sm,\n                 c(\"marrmale = 0\", \"marrfemale = 0\", \"singfem = 0\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLinear hypothesis test:\nmarrmale = 0\nmarrfemale = 0\nsingfem = 0\n\nModel 1: restricted model\nModel 2: wage ~ marrmale + marrfemale + singfem + educ + exper + tenure\n\n  Res.Df Df  Chisq Pr(>Chisq)    \n1    522                         \n2    519  3 72.043  1.558e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThis is the $\\chi^2$ (Wald) statistic based on an asymptotic distribution.\n\n\nTo obtain the $F$ statistic, specify `test = \"F\"` in `linearHypothesis()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinearHypothesis(reg_wage_sm,\n                 c(\"marrmale = 0\", \"marrfemale = 0\", \"singfem = 0\"), test = \"F\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLinear hypothesis test:\nmarrmale = 0\nmarrfemale = 0\nsingfem = 0\n\nModel 1: restricted model\nModel 2: wage ~ marrmale + marrfemale + singfem + educ + exper + tenure\n\n  Res.Df Df      F    Pr(>F)    \n1    522                        \n2    519  3 24.015 1.445e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n::: {.callout-note title=\"Recall\"}\n\n| $q$ (restrictions) | Critical value $\\chi^2$ ($\\alpha = 0.05$) | Critical value $F$ ($\\alpha = 0.05$) |\n|------------------|-----------------------------|-----------------------------|\n| 1                | 3.84                        | 3.84                        |\n| 2                | 6.00                        | 3.00                        |\n| 3                | 7.80                        | 2.60                        |\n\n*Note:* For large $n$, the $F$ statistic has a $\\chi^2/q$ distribution.\n:::\n\nIn our case:\n\n- 24 > 2.60\n\n- 72.04 > 7.80\n\nWe therefore reject the null hypothesis that there are no wage differences across the categories.\n\nThere is a simple formula for the $F$ statistic that is valid only under **homoskedasticity**, but it helps illustrate what the statistic does.\n\nUnder homoskedasticity, the classical $F$ test proceeds as follows:\n\n- Estimate two regressions: one under the null hypothesis (the restricted regression) and one under the alternative hypothesis (the unrestricted regression).\n\n- Compare the fit of the two regressions using their $R^2$ values. If the unrestricted model fits sufficiently better, reject the null hypothesis.\n\n\nThe classical $F$ statistic is historically important and useful for intuition, but it is not valid in the presence of heteroskedasticity.\n",
    "supporting": [
      "tutorial2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}