{
  "hash": "d9ee0adeed02e1983e97512e758b1062",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Problem Set 1\"\nsubtitle: \"Solutions\"\nauthor: \"Andrea Recine\"\ndate: today\nlang: en\ndescription: \"Full worked solutions to Problem Set 1.\"\n---\n\n# Problem Set 1\n\n## Introduction\n\n\n::: {.callout-note}\nThe solutions are in collapsible boxes: try to answer **before** opening them.\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(knitr)\nlibrary(tinytable)\nlibrary(modelsummary)\nlibrary(fixest)\nlibrary(car)\nlibrary(marginaleffects)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(wooldridge)\n```\n:::\n\n\n\n\n## Exercise 1\n\nConsider the data in `wage2`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"wage2\", package = \"wooldridge\")\n```\n:::\n\n\n\n- $wage$: monthly earnings\n- $educ$: years of education\n- $exper$: years of experience\n- $tenure$: years with the current employer\n- $black$: dummy variable indicating whether the worker is Black\n\n\n\nWe estimate the following models:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelA <- feols(wage ~ educ + exper + tenure + black, data = wage2, vcov = \"hetero\")\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelB <- feols(log(wage) ~ educ + exper + tenure + black, data = wage2, vcov = \"hetero\")\n```\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(list(\"Wage (Model A)\" = modelA, \"Log Wage (Model B)\" = modelB), gof_omit = \"AIC|BIC|RMSE|R2 Adj.\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_xx8bi8l85k9wf9wngh96 = TinyTable.createTableFunctions(\"tinytable_xx8bi8l85k9wf9wngh96\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '12', j: 2 }, { i: '12', j: 3 } ], css_id: 'tinytable_css_1uc346t84mt4r40yqcak',}, \n          { positions: [ { i: '10', j: 2 }, { i: '10', j: 3 } ], css_id: 'tinytable_css_3c8gycelmcrtal01llia',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '11', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '11', j: 3 } ], css_id: 'tinytable_css_kkszqpfxl7ub1qqh94jk',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_uidstenoi4uticpgeqjh',}, \n          { positions: [ { i: '12', j: 1 } ], css_id: 'tinytable_css_jpk1dosz8yxzd3gug55a',}, \n          { positions: [ { i: '10', j: 1 } ], css_id: 'tinytable_css_15ocvv44638hwumiq8kg',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '11', j: 1 } ], css_id: 'tinytable_css_54sho1fsi44gzsn4r89f',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_ikclv25li62744xn0t56',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_xx8bi8l85k9wf9wngh96.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_xx8bi8l85k9wf9wngh96 td.tinytable_css_1uc346t84mt4r40yqcak, #tinytable_xx8bi8l85k9wf9wngh96 th.tinytable_css_1uc346t84mt4r40yqcak {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_xx8bi8l85k9wf9wngh96 td.tinytable_css_3c8gycelmcrtal01llia, #tinytable_xx8bi8l85k9wf9wngh96 th.tinytable_css_3c8gycelmcrtal01llia {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_xx8bi8l85k9wf9wngh96 td.tinytable_css_kkszqpfxl7ub1qqh94jk, #tinytable_xx8bi8l85k9wf9wngh96 th.tinytable_css_kkszqpfxl7ub1qqh94jk { text-align: center }\n    #tinytable_xx8bi8l85k9wf9wngh96 td.tinytable_css_uidstenoi4uticpgeqjh, #tinytable_xx8bi8l85k9wf9wngh96 th.tinytable_css_uidstenoi4uticpgeqjh {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_xx8bi8l85k9wf9wngh96 td.tinytable_css_jpk1dosz8yxzd3gug55a, #tinytable_xx8bi8l85k9wf9wngh96 th.tinytable_css_jpk1dosz8yxzd3gug55a {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_xx8bi8l85k9wf9wngh96 td.tinytable_css_15ocvv44638hwumiq8kg, #tinytable_xx8bi8l85k9wf9wngh96 th.tinytable_css_15ocvv44638hwumiq8kg {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_xx8bi8l85k9wf9wngh96 td.tinytable_css_54sho1fsi44gzsn4r89f, #tinytable_xx8bi8l85k9wf9wngh96 th.tinytable_css_54sho1fsi44gzsn4r89f { text-align: left }\n    #tinytable_xx8bi8l85k9wf9wngh96 td.tinytable_css_ikclv25li62744xn0t56, #tinytable_xx8bi8l85k9wf9wngh96 th.tinytable_css_ikclv25li62744xn0t56 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_xx8bi8l85k9wf9wngh96\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Wage (Model A)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Log Wage (Model B)</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">-178.430</td>\n                  <td data-row=\"1\" data-col=\"3\">5.613</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(110.685)</td>\n                  <td data-row=\"2\" data-col=\"3\">(0.115)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">educ</td>\n                  <td data-row=\"3\" data-col=\"2\">69.438</td>\n                  <td data-row=\"3\" data-col=\"3\">0.069</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(6.787)</td>\n                  <td data-row=\"4\" data-col=\"3\">(0.007)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">exper</td>\n                  <td data-row=\"5\" data-col=\"2\">14.772</td>\n                  <td data-row=\"5\" data-col=\"3\">0.015</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(3.213)</td>\n                  <td data-row=\"6\" data-col=\"3\">(0.003)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">tenure</td>\n                  <td data-row=\"7\" data-col=\"2\">7.301</td>\n                  <td data-row=\"7\" data-col=\"3\">0.012</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\">(2.488)</td>\n                  <td data-row=\"8\" data-col=\"3\">(0.003)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">black</td>\n                  <td data-row=\"9\" data-col=\"2\">-175.133</td>\n                  <td data-row=\"9\" data-col=\"3\">-0.207</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\">(29.843)</td>\n                  <td data-row=\"10\" data-col=\"3\">(0.037)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"11\" data-col=\"2\">935</td>\n                  <td data-row=\"11\" data-col=\"3\">935</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\">R2</td>\n                  <td data-row=\"12\" data-col=\"2\">0.166</td>\n                  <td data-row=\"12\" data-col=\"3\">0.181</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n### Questions\n\n::: {.callout-tip title=\"Question 1 — Interpretation of `educ`\"}\nInterpret the coefficient on $educ$ in **Model A** (level) and in **Model B** (log).\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n- **Model A** (level): holding $exper$, $tenure$, and $black$ constant, an additional year of education is **associated** on average with an increase of about **69.44 dollars** in the monthly wage.\n- **Model B** (log): holding the same variables constant, an additional year of education is **associated** on average with an increase in the wage of about $100 \\cdot$ 0.069 $=$ **6.9%**. Since the dependent variable is in logs and the regressor in levels, this is a **semi-elasticity**.\n:::\n\n\n::: {.callout-tip title=\"Question 2 — Change of units of measurement\"}\nSuppose that the wage $wage$ in **Model A** is expressed in hundreds of dollars (that is, `wage/100`). Which of the following statements is correct?\n\na) The coefficients of Model A would all be divided by 100, while those of Model B would remain unchanged.\n\nb) The coefficients of Model A would all be divided by 100, while those of Model B, except the intercept, would remain unchanged.\n\nc) The coefficients of Model A would all be multiplied by 100, while those of Model B, except the one on `educ`, would remain unchanged.\n\nd) The coefficients of Model A would all be multiplied by 100, while those of Model B would remain unchanged.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n**Correct answer: b)**.\n\nIn **Model A** the dependent variable is in levels: rescaling $wage$ to $wage/100$ **divides by 100** all the coefficients (intercept included) and their standard errors; the $t$ ratios and the $R^2$ do not change.\n\nIn **Model B** the dependent variable is in logs: $\\log(wage/100) = \\log(wage) - \\log(100)$. **Only the intercept** changes (by $-\\log(100)$), while the coefficients of the explanatory variables remain unchanged. This is why b) is correct and a) (which says \"all of B unchanged\") is imprecise about the intercept.\n:::\n\n\n::: {.callout-tip title=\"Question 3 — Coefficient on `black` (multiple choice)\"}\nWhich interpretation of the coefficient on $black$ is correct?\n\na) In Model A: Black workers earn on average about 175.13 dollars less per month, holding the other variables constant.\nb) In Model B: Black workers earn on average about 20.7% less, holding the same variables constant.\nc) Both of the above, one for each model.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n**Correct answer: c)**.\n\nBoth interpretations are correct in their respective models: in levels $\\hat\\beta_{black} =$ -175.13 dollars; in logs $\\hat\\beta_{black} =$ -0.207, which with the approximation $100\\cdot\\hat\\beta$ gives about **-20.7%**.\n\nThe coefficient *measures* a conditional association, not a causal effect.\n:::\n\n\n::: {.callout-tip title=\"Question 4 — 95% CI (calculation)\"}\nConstruct the 95% confidence interval for the coefficient on $educ$ in **Model B**.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\nWith $\\hat\\beta_{educ} =$ 0.069 and $SE =$ 0.0067, using the approximation $\\hat\\beta \\pm 1.96 \\cdot SE$:\n\n$$CI_{95\\%} = [\\,0.0557\\ ;\\ 0.0822\\,]$$\n\nZero is not contained in the interval: the coefficient is significantly different from zero at the 5% level.\n:::\n\n\n::: {.callout-tip title=\"Question 5 — 90% CI\"}\nConstruct the 90% confidence interval for the coefficient of an increase of 20 years of $educ$ in **Model A**.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\nThe effect of +20 years of education is $20 \\cdot \\hat\\beta_{educ} =$ **1388.8 dollars**, with standard error $20 \\cdot SE =$ 135.7. At the 90% level the critical value is $1.645$:\n\n$$CI_{90\\%} = 20\\hat\\beta_{educ} \\pm 1.645 \\cdot 20\\,SE = [\\,1165.5\\ ;\\ 1612\\,]$$\n\n(Rescaling the variable by the constant 20 multiplies both the estimate and the standard error by 20, leaving the $t$ ratio unchanged.)\n:::\n\n\n::: {.callout-tip title=\"Question 6 — F test of joint significance\"}\nTest the joint null hypothesis $H_0: \\beta_{exper} = 0 \\;\\text{and}\\; \\beta_{tenure} = 0$ in **Model B**. Can we **reject/not reject** $H_0$ at the 5% level?\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlinearHypothesis(modelB, c(\"exper = 0\", \"tenure = 0\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLinear hypothesis test:\nexper = 0\ntenure = 0\n\nModel 1: restricted model\nModel 2: log(wage) ~ educ + exper + tenure + black\n\n  Res.Df Df Chisq Pr(>Chisq)    \n1    932                        \n2    930  2 60.01  9.308e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n\nWe **reject** $H_0$ at the 5% level. $exper$ and $tenure$ are jointly significant. 60.01 > 6 (the critical value at the 5% level with two restrictions).\n:::\n\n\n## Exercise 2\n\nWe use the `wage1` dataset (Wooldridge), a sample of US workers from the 1976 CPS survey. Warning: in this section **experience is measured in decades** (`exper_dec = exper / 10`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"wage1\", package = \"wooldridge\")\n\nwage1 <- wage1 |>\n  mutate(exper_dec  = exper / 10,   # experience in decades\n         exper_dec2 = exper_dec^2)  # experience (in decades) squared\n```\n:::\n\n\n| variable    | description |\n|-------------|-------------|\n| `wage`      | hourly wage in dollars |\n| `educ`      | years of education completed |\n| `exper_dec` | decades of work experience |\n| `tenure`    | years with the current employer |\n| `female`    | =1 if woman, =0 if man |\n| `married`   | =1 if married, =0 otherwise |\n| `nonwhite`  | =1 if nonwhite, =0 otherwise |\n\nThe researchers estimate six specifications:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmA <- feols(wage      ~ educ + exper_dec + tenure + female,\n            data = wage1, vcov = \"hetero\")                                   # A: linear\n\nmB <- feols(log(wage) ~ educ + exper_dec + tenure + female,\n            data = wage1, vcov = \"hetero\")                                   # B: log-linear\n\nmC <- feols(log(wage) ~ log(educ) + exper_dec + tenure + female,\n            data = wage1, vcov = \"hetero\")                                   # C: log-log\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNOTE: 2 observations removed because of infinite values (RHS: 2).\n```\n\n\n:::\n\n```{.r .cell-code}\nmD <- feols(log(wage) ~ educ + exper_dec + female:exper_dec + tenure + female,\n            data = wage1, vcov = \"hetero\")                                   # D: interaction\n\nmE <- feols(log(wage) ~ educ + exper_dec + exper_dec2 + tenure + female,\n            data = wage1, vcov = \"hetero\")                                   # E: polynomial\n\nmF <- feols(log(wage) ~ educ + educ:female + exper_dec + exper_dec2 + tenure + female,\n            data = wage1, vcov = \"hetero\")                                   # F: interaction + polynomial\n\nmodelsummary(list(\"(A)\" = mA, \"(B)\" = mB, \"(C)\" = mC,\n                  \"(D)\" = mD, \"(E)\" = mE, \"(F)\" = mF),\n             gof_omit = \"AIC|BIC|RMSE|R2 Adj.\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_7ccy9ylvpit8ybl2o9mp = TinyTable.createTableFunctions(\"tinytable_7ccy9ylvpit8ybl2o9mp\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '20', j: 2 }, { i: '20', j: 3 }, { i: '20', j: 4 }, { i: '20', j: 5 }, { i: '20', j: 6 }, { i: '20', j: 7 } ], css_id: 'tinytable_css_v2x6wwu1s267n393lq8t',}, \n          { positions: [ { i: '18', j: 2 }, { i: '18', j: 3 }, { i: '18', j: 4 }, { i: '18', j: 5 }, { i: '18', j: 6 }, { i: '18', j: 7 } ], css_id: 'tinytable_css_d8tkdq5ecwybr4pdifm5',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '14', j: 2 }, { i: '15', j: 2 }, { i: '16', j: 2 }, { i: '17', j: 2 }, { i: '19', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 }, { i: '13', j: 3 }, { i: '14', j: 3 }, { i: '15', j: 3 }, { i: '16', j: 3 }, { i: '17', j: 3 }, { i: '19', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '3', j: 4 }, { i: '4', j: 4 }, { i: '5', j: 4 }, { i: '6', j: 4 }, { i: '7', j: 4 }, { i: '8', j: 4 }, { i: '9', j: 4 }, { i: '10', j: 4 }, { i: '11', j: 4 }, { i: '12', j: 4 }, { i: '13', j: 4 }, { i: '14', j: 4 }, { i: '15', j: 4 }, { i: '16', j: 4 }, { i: '17', j: 4 }, { i: '19', j: 4 }, { i: '1', j: 5 }, { i: '2', j: 5 }, { i: '3', j: 5 }, { i: '4', j: 5 }, { i: '5', j: 5 }, { i: '6', j: 5 }, { i: '7', j: 5 }, { i: '8', j: 5 }, { i: '9', j: 5 }, { i: '10', j: 5 }, { i: '11', j: 5 }, { i: '12', j: 5 }, { i: '13', j: 5 }, { i: '14', j: 5 }, { i: '15', j: 5 }, { i: '16', j: 5 }, { i: '17', j: 5 }, { i: '19', j: 5 }, { i: '1', j: 6 }, { i: '2', j: 6 }, { i: '3', j: 6 }, { i: '4', j: 6 }, { i: '5', j: 6 }, { i: '6', j: 6 }, { i: '7', j: 6 }, { i: '8', j: 6 }, { i: '9', j: 6 }, { i: '10', j: 6 }, { i: '11', j: 6 }, { i: '12', j: 6 }, { i: '13', j: 6 }, { i: '14', j: 6 }, { i: '15', j: 6 }, { i: '16', j: 6 }, { i: '17', j: 6 }, { i: '19', j: 6 }, { i: '1', j: 7 }, { i: '2', j: 7 }, { i: '3', j: 7 }, { i: '4', j: 7 }, { i: '5', j: 7 }, { i: '6', j: 7 }, { i: '7', j: 7 }, { i: '8', j: 7 }, { i: '9', j: 7 }, { i: '10', j: 7 }, { i: '11', j: 7 }, { i: '12', j: 7 }, { i: '13', j: 7 }, { i: '14', j: 7 }, { i: '15', j: 7 }, { i: '16', j: 7 }, { i: '17', j: 7 }, { i: '19', j: 7 } ], css_id: 'tinytable_css_ij03xipc5urc5s7kohe8',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 }, { i: '0', j: 7 } ], css_id: 'tinytable_css_f13swpv96ghnu8wodfsa',}, \n          { positions: [ { i: '20', j: 1 } ], css_id: 'tinytable_css_dfowl9qi0z2ogn5snjg1',}, \n          { positions: [ { i: '18', j: 1 } ], css_id: 'tinytable_css_l7s0r3c3kcgxzpo892kk',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 }, { i: '14', j: 1 }, { i: '15', j: 1 }, { i: '16', j: 1 }, { i: '17', j: 1 }, { i: '19', j: 1 } ], css_id: 'tinytable_css_e9660gs7zsu9jp9lqkdd',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_0zwtcjtquptaq1kneq0r',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_7ccy9ylvpit8ybl2o9mp.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_7ccy9ylvpit8ybl2o9mp td.tinytable_css_v2x6wwu1s267n393lq8t, #tinytable_7ccy9ylvpit8ybl2o9mp th.tinytable_css_v2x6wwu1s267n393lq8t {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_7ccy9ylvpit8ybl2o9mp td.tinytable_css_d8tkdq5ecwybr4pdifm5, #tinytable_7ccy9ylvpit8ybl2o9mp th.tinytable_css_d8tkdq5ecwybr4pdifm5 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_7ccy9ylvpit8ybl2o9mp td.tinytable_css_ij03xipc5urc5s7kohe8, #tinytable_7ccy9ylvpit8ybl2o9mp th.tinytable_css_ij03xipc5urc5s7kohe8 { text-align: center }\n    #tinytable_7ccy9ylvpit8ybl2o9mp td.tinytable_css_f13swpv96ghnu8wodfsa, #tinytable_7ccy9ylvpit8ybl2o9mp th.tinytable_css_f13swpv96ghnu8wodfsa {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_7ccy9ylvpit8ybl2o9mp td.tinytable_css_dfowl9qi0z2ogn5snjg1, #tinytable_7ccy9ylvpit8ybl2o9mp th.tinytable_css_dfowl9qi0z2ogn5snjg1 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_7ccy9ylvpit8ybl2o9mp td.tinytable_css_l7s0r3c3kcgxzpo892kk, #tinytable_7ccy9ylvpit8ybl2o9mp th.tinytable_css_l7s0r3c3kcgxzpo892kk {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_7ccy9ylvpit8ybl2o9mp td.tinytable_css_e9660gs7zsu9jp9lqkdd, #tinytable_7ccy9ylvpit8ybl2o9mp th.tinytable_css_e9660gs7zsu9jp9lqkdd { text-align: left }\n    #tinytable_7ccy9ylvpit8ybl2o9mp td.tinytable_css_0zwtcjtquptaq1kneq0r, #tinytable_7ccy9ylvpit8ybl2o9mp th.tinytable_css_0zwtcjtquptaq1kneq0r {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_7ccy9ylvpit8ybl2o9mp\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">(A)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">(B)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">(C)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">(D)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">(E)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"7\">(F)</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">-1.568</td>\n                  <td data-row=\"1\" data-col=\"3\">0.501</td>\n                  <td data-row=\"1\" data-col=\"4\">-0.726</td>\n                  <td data-row=\"1\" data-col=\"5\">0.417</td>\n                  <td data-row=\"1\" data-col=\"6\">0.415</td>\n                  <td data-row=\"1\" data-col=\"7\">0.395</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.826)</td>\n                  <td data-row=\"2\" data-col=\"3\">(0.115)</td>\n                  <td data-row=\"2\" data-col=\"4\">(0.258)</td>\n                  <td data-row=\"2\" data-col=\"5\">(0.128)</td>\n                  <td data-row=\"2\" data-col=\"6\">(0.107)</td>\n                  <td data-row=\"2\" data-col=\"7\">(0.121)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">educ</td>\n                  <td data-row=\"3\" data-col=\"2\">0.572</td>\n                  <td data-row=\"3\" data-col=\"3\">0.087</td>\n                  <td data-row=\"3\" data-col=\"4\"></td>\n                  <td data-row=\"3\" data-col=\"5\">0.090</td>\n                  <td data-row=\"3\" data-col=\"6\">0.081</td>\n                  <td data-row=\"3\" data-col=\"7\">0.083</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.061)</td>\n                  <td data-row=\"4\" data-col=\"3\">(0.008)</td>\n                  <td data-row=\"4\" data-col=\"4\"></td>\n                  <td data-row=\"4\" data-col=\"5\">(0.008)</td>\n                  <td data-row=\"4\" data-col=\"6\">(0.008)</td>\n                  <td data-row=\"4\" data-col=\"7\">(0.009)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">exper_dec</td>\n                  <td data-row=\"5\" data-col=\"2\">0.254</td>\n                  <td data-row=\"5\" data-col=\"3\">0.046</td>\n                  <td data-row=\"5\" data-col=\"4\">0.046</td>\n                  <td data-row=\"5\" data-col=\"5\">0.084</td>\n                  <td data-row=\"5\" data-col=\"6\">0.328</td>\n                  <td data-row=\"5\" data-col=\"7\">0.328</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.098)</td>\n                  <td data-row=\"6\" data-col=\"3\">(0.016)</td>\n                  <td data-row=\"6\" data-col=\"4\">(0.017)</td>\n                  <td data-row=\"6\" data-col=\"5\">(0.024)</td>\n                  <td data-row=\"6\" data-col=\"6\">(0.046)</td>\n                  <td data-row=\"6\" data-col=\"7\">(0.046)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">tenure</td>\n                  <td data-row=\"7\" data-col=\"2\">0.141</td>\n                  <td data-row=\"7\" data-col=\"3\">0.017</td>\n                  <td data-row=\"7\" data-col=\"4\">0.018</td>\n                  <td data-row=\"7\" data-col=\"5\">0.016</td>\n                  <td data-row=\"7\" data-col=\"6\">0.016</td>\n                  <td data-row=\"7\" data-col=\"7\">0.016</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\">(0.028)</td>\n                  <td data-row=\"8\" data-col=\"3\">(0.004)</td>\n                  <td data-row=\"8\" data-col=\"4\">(0.004)</td>\n                  <td data-row=\"8\" data-col=\"5\">(0.004)</td>\n                  <td data-row=\"8\" data-col=\"6\">(0.003)</td>\n                  <td data-row=\"8\" data-col=\"7\">(0.003)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">female</td>\n                  <td data-row=\"9\" data-col=\"2\">-1.811</td>\n                  <td data-row=\"9\" data-col=\"3\">-0.301</td>\n                  <td data-row=\"9\" data-col=\"4\">-0.328</td>\n                  <td data-row=\"9\" data-col=\"5\">-0.190</td>\n                  <td data-row=\"9\" data-col=\"6\">-0.298</td>\n                  <td data-row=\"9\" data-col=\"7\">-0.248</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\">(0.254)</td>\n                  <td data-row=\"10\" data-col=\"3\">(0.038)</td>\n                  <td data-row=\"10\" data-col=\"4\">(0.038)</td>\n                  <td data-row=\"10\" data-col=\"5\">(0.057)</td>\n                  <td data-row=\"10\" data-col=\"6\">(0.037)</td>\n                  <td data-row=\"10\" data-col=\"7\">(0.185)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">log(educ)</td>\n                  <td data-row=\"11\" data-col=\"2\"></td>\n                  <td data-row=\"11\" data-col=\"3\"></td>\n                  <td data-row=\"11\" data-col=\"4\">0.933</td>\n                  <td data-row=\"11\" data-col=\"5\"></td>\n                  <td data-row=\"11\" data-col=\"6\"></td>\n                  <td data-row=\"11\" data-col=\"7\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\"></td>\n                  <td data-row=\"12\" data-col=\"2\"></td>\n                  <td data-row=\"12\" data-col=\"3\"></td>\n                  <td data-row=\"12\" data-col=\"4\">(0.098)</td>\n                  <td data-row=\"12\" data-col=\"5\"></td>\n                  <td data-row=\"12\" data-col=\"6\"></td>\n                  <td data-row=\"12\" data-col=\"7\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">exper_dec × female</td>\n                  <td data-row=\"13\" data-col=\"2\"></td>\n                  <td data-row=\"13\" data-col=\"3\"></td>\n                  <td data-row=\"13\" data-col=\"4\"></td>\n                  <td data-row=\"13\" data-col=\"5\">-0.067</td>\n                  <td data-row=\"13\" data-col=\"6\"></td>\n                  <td data-row=\"13\" data-col=\"7\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"14\" data-col=\"1\"></td>\n                  <td data-row=\"14\" data-col=\"2\"></td>\n                  <td data-row=\"14\" data-col=\"3\"></td>\n                  <td data-row=\"14\" data-col=\"4\"></td>\n                  <td data-row=\"14\" data-col=\"5\">(0.027)</td>\n                  <td data-row=\"14\" data-col=\"6\"></td>\n                  <td data-row=\"14\" data-col=\"7\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"15\" data-col=\"1\">exper_dec2</td>\n                  <td data-row=\"15\" data-col=\"2\"></td>\n                  <td data-row=\"15\" data-col=\"3\"></td>\n                  <td data-row=\"15\" data-col=\"4\"></td>\n                  <td data-row=\"15\" data-col=\"5\"></td>\n                  <td data-row=\"15\" data-col=\"6\">-0.065</td>\n                  <td data-row=\"15\" data-col=\"7\">-0.065</td>\n                </tr>\n                <tr>\n                  <td data-row=\"16\" data-col=\"1\"></td>\n                  <td data-row=\"16\" data-col=\"2\"></td>\n                  <td data-row=\"16\" data-col=\"3\"></td>\n                  <td data-row=\"16\" data-col=\"4\"></td>\n                  <td data-row=\"16\" data-col=\"5\"></td>\n                  <td data-row=\"16\" data-col=\"6\">(0.010)</td>\n                  <td data-row=\"16\" data-col=\"7\">(0.010)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"17\" data-col=\"1\">educ × female</td>\n                  <td data-row=\"17\" data-col=\"2\"></td>\n                  <td data-row=\"17\" data-col=\"3\"></td>\n                  <td data-row=\"17\" data-col=\"4\"></td>\n                  <td data-row=\"17\" data-col=\"5\"></td>\n                  <td data-row=\"17\" data-col=\"6\"></td>\n                  <td data-row=\"17\" data-col=\"7\">-0.004</td>\n                </tr>\n                <tr>\n                  <td data-row=\"18\" data-col=\"1\"></td>\n                  <td data-row=\"18\" data-col=\"2\"></td>\n                  <td data-row=\"18\" data-col=\"3\"></td>\n                  <td data-row=\"18\" data-col=\"4\"></td>\n                  <td data-row=\"18\" data-col=\"5\"></td>\n                  <td data-row=\"18\" data-col=\"6\"></td>\n                  <td data-row=\"18\" data-col=\"7\">(0.015)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"19\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"19\" data-col=\"2\">526</td>\n                  <td data-row=\"19\" data-col=\"3\">526</td>\n                  <td data-row=\"19\" data-col=\"4\">524</td>\n                  <td data-row=\"19\" data-col=\"5\">526</td>\n                  <td data-row=\"19\" data-col=\"6\">526</td>\n                  <td data-row=\"19\" data-col=\"7\">526</td>\n                </tr>\n                <tr>\n                  <td data-row=\"20\" data-col=\"1\">R2</td>\n                  <td data-row=\"20\" data-col=\"2\">0.364</td>\n                  <td data-row=\"20\" data-col=\"3\">0.392</td>\n                  <td data-row=\"20\" data-col=\"4\">0.375</td>\n                  <td data-row=\"20\" data-col=\"5\">0.399</td>\n                  <td data-row=\"20\" data-col=\"6\">0.434</td>\n                  <td data-row=\"20\" data-col=\"7\">0.434</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nAll models report heteroskedasticity-robust standard errors.\n\n### Questions\n\n::: {.callout-tip title=\"Question 1 — Models A and B\"}\nIn **Model A**, an additional year of education is associated with an increase in the hourly wage of about **__________** *(dollars / %)*.\n\nIn **Model B**, an additional year of education is associated with an increase in the hourly wage of about **__________** *(dollars / %)*.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n- **Model A** (level): about **0.572 dollars**. The dependent variable is in levels, so the coefficient is a change in **dollars**.\n- **Model B** (log-linear): about **8.7%**. The dependent variable is in logs: the coefficient is a **semi-elasticity** ($100 \\cdot \\hat\\beta$ in **%**).\n:::\n\n::: {.callout-tip title=\"Question 2 — Change of units of measurement\"}\nIf we re-estimated the models expressing the wage in **tens of dollars** (`wage/10`) instead of dollars, indicate **all** the correct statements:\n\n1. The $R^2$ values would be different.\n2. In Model A the standard errors would be multiplied by 10.\n3. Statistical inference (the significance of the coefficients) would remain unchanged.\n4. In the log-linear model the intercept would change, but not the coefficients of the explanatory variables.\n5. Rescaling the dependent variable by a positive constant does not change the coefficients of the explanatory variables in the log-linear model.\n6. The coefficients would all be multiplied by 10.\n\nMoreover, in **Model A** the coefficient on education would be multiplied by **__________**.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\nCorrect: **3, 4, 5**. Rescaling the dependent variable by a positive constant ($wage^{new} = wage/10$) does **not** change the $R^2$ (statement 1 is false) or the inference (the $t$ ratios stay the same). In Model A, which is in levels, all the coefficients and standard errors are **divided** by 10 (not multiplied: statements 2 and 6 are false), so the $t$ ratios are unchanged. In the log models the rescaling only shifts the intercept by $\\log(1/10)$, leaving the coefficients of the explanatory variables unchanged.\n\nIn **Model A** the coefficient on education would be multiplied by **0.1** (that is, divided by 10): from 0.572 to 0.0572 tens of dollars per year.\n:::\n\n::: {.callout-tip title=\"Question 3 — Model D (interaction)\"}\nIn **Model D**, the effect of an additional decade of experience (`exper_dec`) for a **woman** is an increase of about **__________** %.\n\nIndicate **all** the correct statements about the interaction `female:exper_dec` ($female \\times exper\\_dec$):\n\n1. The return to experience on the wage differs between men and women.\n2. The coefficient on `female:exper_dec` indicates how much the return to experience for women differs from that for men.\n3. The logarithmic transformation captures any nonlinearity anyway, so the interaction is superfluous.\n4. For a man (`female = 0`), an additional decade of experience is associated with a change equal to the coefficient on `exper_dec`.\n5. The return to experience is identical for men and women.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\nThe return to experience is $\\hat\\beta_{exper\\_dec}$ for men and $\\hat\\beta_{exper\\_dec} + \\hat\\beta_{female:exper\\_dec}$ for women:\n\n- **men** (`female = 0`): about 8.4% per decade;\n- **women** (`female = 1`): about **1.7%** per decade.\n\nThe difference is $100 \\cdot \\hat\\beta_{female:exper\\_dec} =$ -6.7 percentage points (the interaction term is significant, $p \\approx$ 0.014).\n\nCorrect: **1, 2, 4**. The interaction lets the return to experience depend on gender (1, 2); for men it coincides with $\\hat\\beta_{exper\\_dec}$ (4). Statement 3 is false (the log does not capture *every kind of* nonlinearity) and statement 5 contradicts the presence of the interaction.\n:::\n\n::: {.callout-tip title=\"Question 4 — Model E (polynomial)\"}\nIn **Model E**, the marginal effect of experience on the (log) wage for a worker with **10 years of experience** (`exper_dec = 1`) is about **__________** /%.\n\nThe number of years of experience at which the marginal effect is zero is **__________** years.\n\nBased on the $t$ test on the coefficient of `exper_dec²`, at the 10% level (**we reject / we do not reject**) **__________** the null hypothesis that the relationship between the wage and experience, holding other conditions constant, is linear.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\nThe marginal effect is $\\hat\\beta_{exper\\_dec} + 2\\,\\hat\\beta_{exper\\_dec2}\\cdot exper\\_dec$. At `exper_dec = 1` it is about **0.198** (that is, $\\approx$ 19.8%).\n\nThe marginal effect is zero at $exper\\_dec^* = -\\hat\\beta_{exper\\_dec}/(2\\,\\hat\\beta_{exper\\_dec2})$, that is, at about **25.3 years** of experience.\n\nThe $t$ ratio on the quadratic term is $|t| =$ 6.69. Since the critical value at the 10% level is $\\approx 1.645$, at the 10% level **we reject** the null hypothesis of linearity.\n:::\n\n::: {.callout-tip title=\"Question 5 — Comparing the R² values\"}\nCompare the $R^2$ of Model A with that of Model B. A student concludes that Model B fits the data better because it has a higher $R^2$. Which statement is correct?\n\na) The comparison is not valid because the two models have different dependent variables (`wage` vs `log(wage)`): the $R^2$ values measure shares of variance of different quantities.\nb) The comparison is not valid because Model B has more regressors.\nc) The comparison is valid only if the coefficients are statistically significant.\nd) The comparison is valid: a higher $R^2$ always indicates a better fit.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n**Correct answer: a)**. Model A has $R^2 \\approx$ 0.364 and Model B has $R^2 \\approx$ 0.392, but the dependent variables are different (`wage` vs `log(wage)`): the two $R^2$ values measure shares of variance of different quantities and are **not comparable**. b) is irrelevant (they have the same regressors); c) and d) are incorrect statements about the meaning of the $R^2$.\n:::\n\n::: {.callout-tip title=\"Question 6 — Model F (interaction + polynomial)\"}\nIn **Model F**, the percentage return to an additional year of education for **men** is about **__________** %, while for **women** it is about **__________** %.\n\nThe difference in absolute value between the two returns is about **__________** percentage points.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\nIn Model F the return to education is $\\hat\\beta_{educ}$ for men and $\\hat\\beta_{educ} + \\hat\\beta_{educ:female}$ for women:\n\n- **men**: about **8.3%**;\n- **women**: about **7.9%**;\n- **difference** (in absolute value): about **0.4 percentage points** ($= 100\\cdot|\\hat\\beta_{educ:female}|$).\n\n:::\n\n\n## Exercise 3\n\nConsider the `hprice1` data (88 houses, Wooldridge), which contain information on house prices and their characteristics.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"hprice1\", package = \"wooldridge\")\n```\n:::\n\n\n- $price$: house price in thousands of dollars\n- $sqrft$: size in square feet\n- $lotsize$: lot size (square feet)\n- $bdrms$: number of bedrooms\n- $colonial$: dummy = 1 if the house is colonial style\n\nWe estimate two models, one **lin-lin** and one **log-log**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_lin <- feols(price ~ sqrft + lotsize + bdrms + colonial,\n                     data = hprice1, vcov = \"hetero\")\n\nmodel_log <- feols(log(price) ~ log(sqrft) + log(lotsize) + bdrms + colonial,\n                     data = hprice1, vcov = \"hetero\")\n\nmodelsummary(list(\"Model A\" = model_lin, \"Model B\" = model_log),\n             gof_omit = \"AIC|BIC|RMSE|R2 Adj.\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_eq29p7imuyrvu4x6kadl = TinyTable.createTableFunctions(\"tinytable_eq29p7imuyrvu4x6kadl\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '16', j: 2 }, { i: '16', j: 3 } ], css_id: 'tinytable_css_w8c94tz2appa5l1c05l8',}, \n          { positions: [ { i: '14', j: 2 }, { i: '14', j: 3 } ], css_id: 'tinytable_css_x7rm4wf143i6ajqszvyi',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '15', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 }, { i: '13', j: 3 }, { i: '15', j: 3 } ], css_id: 'tinytable_css_mslphf87zndf8szs7wme',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_yc2la9plzq9wb17y0xxa',}, \n          { positions: [ { i: '16', j: 1 } ], css_id: 'tinytable_css_j581qvi3y99tubgxnyj1',}, \n          { positions: [ { i: '14', j: 1 } ], css_id: 'tinytable_css_tdl863j6gwvhjdnn6kar',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 }, { i: '15', j: 1 } ], css_id: 'tinytable_css_tqcvpoz58pg05txn8krh',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_2ex1i4k34qg5aqsu6k28',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_eq29p7imuyrvu4x6kadl.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_eq29p7imuyrvu4x6kadl td.tinytable_css_w8c94tz2appa5l1c05l8, #tinytable_eq29p7imuyrvu4x6kadl th.tinytable_css_w8c94tz2appa5l1c05l8 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_eq29p7imuyrvu4x6kadl td.tinytable_css_x7rm4wf143i6ajqszvyi, #tinytable_eq29p7imuyrvu4x6kadl th.tinytable_css_x7rm4wf143i6ajqszvyi {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_eq29p7imuyrvu4x6kadl td.tinytable_css_mslphf87zndf8szs7wme, #tinytable_eq29p7imuyrvu4x6kadl th.tinytable_css_mslphf87zndf8szs7wme { text-align: center }\n    #tinytable_eq29p7imuyrvu4x6kadl td.tinytable_css_yc2la9plzq9wb17y0xxa, #tinytable_eq29p7imuyrvu4x6kadl th.tinytable_css_yc2la9plzq9wb17y0xxa {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_eq29p7imuyrvu4x6kadl td.tinytable_css_j581qvi3y99tubgxnyj1, #tinytable_eq29p7imuyrvu4x6kadl th.tinytable_css_j581qvi3y99tubgxnyj1 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_eq29p7imuyrvu4x6kadl td.tinytable_css_tdl863j6gwvhjdnn6kar, #tinytable_eq29p7imuyrvu4x6kadl th.tinytable_css_tdl863j6gwvhjdnn6kar {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_eq29p7imuyrvu4x6kadl td.tinytable_css_tqcvpoz58pg05txn8krh, #tinytable_eq29p7imuyrvu4x6kadl th.tinytable_css_tqcvpoz58pg05txn8krh { text-align: left }\n    #tinytable_eq29p7imuyrvu4x6kadl td.tinytable_css_2ex1i4k34qg5aqsu6k28, #tinytable_eq29p7imuyrvu4x6kadl th.tinytable_css_2ex1i4k34qg5aqsu6k28 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_eq29p7imuyrvu4x6kadl\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Model A</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Model B</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">-24.127</td>\n                  <td data-row=\"1\" data-col=\"3\">-1.350</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(37.778)</td>\n                  <td data-row=\"2\" data-col=\"3\">(0.812)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">sqrft</td>\n                  <td data-row=\"3\" data-col=\"2\">0.124</td>\n                  <td data-row=\"3\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.018)</td>\n                  <td data-row=\"4\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">lotsize</td>\n                  <td data-row=\"5\" data-col=\"2\">0.002</td>\n                  <td data-row=\"5\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.001)</td>\n                  <td data-row=\"6\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">bdrms</td>\n                  <td data-row=\"7\" data-col=\"2\">11.004</td>\n                  <td data-row=\"7\" data-col=\"3\">0.027</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\">(9.259)</td>\n                  <td data-row=\"8\" data-col=\"3\">(0.033)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">colonial</td>\n                  <td data-row=\"9\" data-col=\"2\">13.716</td>\n                  <td data-row=\"9\" data-col=\"3\">0.054</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\">(16.430)</td>\n                  <td data-row=\"10\" data-col=\"3\">(0.049)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">log(sqrft)</td>\n                  <td data-row=\"11\" data-col=\"2\"></td>\n                  <td data-row=\"11\" data-col=\"3\">0.707</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\"></td>\n                  <td data-row=\"12\" data-col=\"2\"></td>\n                  <td data-row=\"12\" data-col=\"3\">(0.109)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">log(lotsize)</td>\n                  <td data-row=\"13\" data-col=\"2\"></td>\n                  <td data-row=\"13\" data-col=\"3\">0.168</td>\n                </tr>\n                <tr>\n                  <td data-row=\"14\" data-col=\"1\"></td>\n                  <td data-row=\"14\" data-col=\"2\"></td>\n                  <td data-row=\"14\" data-col=\"3\">(0.044)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"15\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"15\" data-col=\"2\">88</td>\n                  <td data-row=\"15\" data-col=\"3\">88</td>\n                </tr>\n                <tr>\n                  <td data-row=\"16\" data-col=\"1\">R2</td>\n                  <td data-row=\"16\" data-col=\"2\">0.676</td>\n                  <td data-row=\"16\" data-col=\"3\">0.649</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n### Questions\n\n::: {.callout-tip title=\"Question 1 — Elasticity\"}\nInterpret the coefficient on $\\log(sqrft)$ in the log-log model. Why is it called an **elasticity**?\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n$\\hat\\beta_{\\log(sqrft)} =$ 0.707. A 1% increase in size is **associated** on average with an increase of about **0.71% in the price**, holding $\\log(lotsize)$, $bdrms$, and $colonial$ constant.\n\nIt is an **elasticity** because it expresses a percentage change in $price$ for a percentage change in $sqrft$: $\\hat\\beta_1 \\approx \\dfrac{\\Delta price / price}{\\Delta sqrft / sqrft}$.\n:::\n\n\n::: {.callout-tip title=\"Question 2 — Coefficient on `bdrms` (multiple choice)\"}\nIn the log-log model, the coefficient on $bdrms$ ($\\hat\\beta = 0.027$) is interpreted as:\n\na) The elasticity of $price$ with respect to $bdrms$.\nb) The percentage change in $price$ for one additional bedroom (semi-elasticity).\nc) The change in $price$, in dollars, for one additional bedroom.\nd) The change in $price$, in thousands of dollars, for one additional bedroom.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n**Correct answer: b)**.\n\nSince $price$ is in logs and $bdrms$ in levels, the model is **log-lin in** $bdrms$: one additional bedroom is **associated** on average with a price change of about $100 \\cdot 0.027 = 2.7\\%$, holding the other variables constant.\n\nThe elasticity (answer a) would have required $\\log(bdrms)$ among the regressors. Answers c) and d) forget that the dependent variable is $\\log(price)$, not $price$.\n:::\n\n\n::: {.callout-tip title=\"Question 3 — Coefficient on `colonial`\"}\nInterpret the coefficient on $colonial$ in the **log-log** model. Approximately how large is the percentage price difference between colonial and non-colonial houses? In the **lin-lin** model, instead, how large is the difference and in what unit of measurement?\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n- **Log-log model**: $\\hat\\beta_{colonial} =$ 0.054. Holding size, lot, and bedrooms constant, a colonial-style house has a price that is on average about $100 \\cdot$ 0.054 $=$ **5.4%** higher (more precisely, $100\\cdot(e^{\\hat\\beta}-1) \\approx$ 5.5%).\n- **Lin-lin model**: $\\hat\\beta_{colonial} =$ 13.72. The dependent variable is $price$ in **thousands of dollars**: a colonial house costs on average about **13.7 thousand dollars** (that is, about 13,716 dollars) more.\n\n**Warning**: in both models the coefficient is not significant at the 5% level, so we cannot rule out that the difference is zero in the population.\n:::\n\n\n::: {.callout-tip title=\"Question 4 — Change of units of measurement (T/F)\"}\nIf we changed the unit of measurement of $price$ from thousands of dollars ($\\$1000$) to dollars ($\\$1$), the coefficient on $\\log(sqrft)$ would remain unchanged. True or false?\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n**True**. The transformation $price^{\\text{new}} = 1000 \\cdot price$ implies $\\log(price^{\\text{new}}) = \\log(1000) + \\log(price)$: only the **intercept** changes (by $\\log(1000) \\approx 6.91$), while the coefficient on $\\log(sqrft)$ — an elasticity — is **invariant to changes of scale** of both the dependent variable and the regressor.\n\nMore generally: in log-log and log-lin models, the coefficients of the regressors are invariant to changes of units (only the intercept changes).\n:::\n\n\n## Exercise 4\n\nConsider the `mlb1` data (353 Major League Baseball players, Wooldridge), which contain data on salaries and career statistics.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"mlb1\", package = \"wooldridge\")\n```\n:::\n\n\n- $salary$: annual salary in dollars\n- $years$: years in MLB\n- $bavg$: batting average (hits per 1000 at bats)\n- $hrunsyr$: home runs per year\n- $rbisyr$: runs batted in (RBI) per year\n\nWe estimate a model with $years$ in **quadratic** form:\n\n$$\\log(salary) = \\beta_0 + \\beta_1 \\, years + \\beta_2 \\, years^2 + \\beta_3 \\, bavg + \\beta_4 \\, hrunsyr + u$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_quad <- feols(log(salary) ~ years + I(years^2) + bavg + hrunsyr,\n                      data = mlb1, vcov = \"hetero\")\n\nmodelsummary(list(\"Model with years²\" = model_quad),\n             gof_omit = \"AIC|BIC|RMSE|R2 Adj.\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_ifmz6ltjbltnj28w4fgz = TinyTable.createTableFunctions(\"tinytable_ifmz6ltjbltnj28w4fgz\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '12', j: 2 } ], css_id: 'tinytable_css_p5vuyhoyf9tdnu8yfii1',}, \n          { positions: [ { i: '10', j: 2 } ], css_id: 'tinytable_css_t77hm260506fytwo9gxn',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '11', j: 2 } ], css_id: 'tinytable_css_yuc68v7iv1lu1kxpkrgd',}, \n          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_yddg7j4py25e5aavovaa',}, \n          { positions: [ { i: '12', j: 1 } ], css_id: 'tinytable_css_3uzo22vaclgub956vr1g',}, \n          { positions: [ { i: '10', j: 1 } ], css_id: 'tinytable_css_os6ihben66r2tbrrroci',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '11', j: 1 } ], css_id: 'tinytable_css_x9pncyinzu9z6l49o2k3',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_paa71z4matz4i5t2rexh',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_ifmz6ltjbltnj28w4fgz.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_ifmz6ltjbltnj28w4fgz td.tinytable_css_p5vuyhoyf9tdnu8yfii1, #tinytable_ifmz6ltjbltnj28w4fgz th.tinytable_css_p5vuyhoyf9tdnu8yfii1 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_ifmz6ltjbltnj28w4fgz td.tinytable_css_t77hm260506fytwo9gxn, #tinytable_ifmz6ltjbltnj28w4fgz th.tinytable_css_t77hm260506fytwo9gxn {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_ifmz6ltjbltnj28w4fgz td.tinytable_css_yuc68v7iv1lu1kxpkrgd, #tinytable_ifmz6ltjbltnj28w4fgz th.tinytable_css_yuc68v7iv1lu1kxpkrgd { text-align: center }\n    #tinytable_ifmz6ltjbltnj28w4fgz td.tinytable_css_yddg7j4py25e5aavovaa, #tinytable_ifmz6ltjbltnj28w4fgz th.tinytable_css_yddg7j4py25e5aavovaa {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_ifmz6ltjbltnj28w4fgz td.tinytable_css_3uzo22vaclgub956vr1g, #tinytable_ifmz6ltjbltnj28w4fgz th.tinytable_css_3uzo22vaclgub956vr1g {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_ifmz6ltjbltnj28w4fgz td.tinytable_css_os6ihben66r2tbrrroci, #tinytable_ifmz6ltjbltnj28w4fgz th.tinytable_css_os6ihben66r2tbrrroci {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_ifmz6ltjbltnj28w4fgz td.tinytable_css_x9pncyinzu9z6l49o2k3, #tinytable_ifmz6ltjbltnj28w4fgz th.tinytable_css_x9pncyinzu9z6l49o2k3 { text-align: left }\n    #tinytable_ifmz6ltjbltnj28w4fgz td.tinytable_css_paa71z4matz4i5t2rexh, #tinytable_ifmz6ltjbltnj28w4fgz th.tinytable_css_paa71z4matz4i5t2rexh {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_ifmz6ltjbltnj28w4fgz\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Model with years²</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">10.209</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.438)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">years</td>\n                  <td data-row=\"3\" data-col=\"2\">0.443</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.040)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">I(I(years^2))</td>\n                  <td data-row=\"5\" data-col=\"2\">-0.020</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.003)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">bavg</td>\n                  <td data-row=\"7\" data-col=\"2\">0.004</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\">(0.002)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">hrunsyr</td>\n                  <td data-row=\"9\" data-col=\"2\">0.068</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\">(0.006)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"11\" data-col=\"2\">353</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\">R2</td>\n                  <td data-row=\"12\" data-col=\"2\">0.628</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n### Questions\n\n::: {.callout-tip title=\"Question 1 — Why `years²`?\"}\nWhy did we add $years^2$ to the regressors? What does the **sign** of $\\hat\\beta_2$ (positive or negative) measure?\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\nThe effect of career years on salary is not necessarily linear: in the first years the salary grows rapidly, then it tends to level off or decline toward the end of the career. The $years^2$ term allows the model to capture this **curvature**.\n\nThe sign of $\\hat\\beta_2$ indicates the concavity:\n\n- $\\hat\\beta_2 < 0$ → **concave** (a parabola with a maximum)\n- $\\hat\\beta_2 > 0$ → **convex** (a parabola with a minimum)\n\nIn our case $\\hat\\beta_2 =$ -0.0202 $< 0$: the relationship is **concave**, with a maximum at a certain number of years.\n:::\n\n\n::: {.callout-tip title=\"Question 2 — Marginal effect (calculation)\"}\nCompute the marginal effect of $years$ for a player with 5 years of career and for a player with 15 years of career.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\nThe marginal effect is $\\dfrac{\\partial \\log(salary)}{\\partial years} = \\hat\\beta_1 + 2\\,\\hat\\beta_2 \\cdot years$, with $\\hat\\beta_1 =$ 0.443 and $\\hat\\beta_2 =$ -0.0202.\n\n- At $years = 5$: 0.242 → an additional year is associated with about **24.2%** more salary.\n- At $years = 15$: -0.162 → an additional year is associated with about **-16.2%** more salary.\n\nThe marginal effect **decreases** with $years$ and changes sign: typical of a concave function with an interior maximum (around 11 years).\n:::\n\n\n::: {.callout-tip title=\"Question 3 — If we omit `years²` (multiple choice)\"}\nIf we instead estimated the model **without** $years^2$, the coefficient $\\hat\\beta_1$ on $years$ would represent:\n\na) The correct marginal effect (equal to that of the quadratic model).\nb) A linear approximation of a relationship that is actually nonlinear; the sign could be misleading depending on the distribution of $years$.\nc) Always zero by construction.\nd) The semi-elasticity at $years = 0$.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n**Correct answer: b)**.\n\nOmitting $years^2$, $\\hat\\beta_1$ estimates the **best linear approximation** (in the OLS sense) of the true relationship: a single number that summarizes the whole curve on average. If most players have $years$ close to the maximum, the \"average\" marginal effect can turn out to be small or even change sign relative to the full model.\n\nAnswer a) is wrong because the true effect **depends on** $years$; it is not constant.\n:::\n\n\n::: {.callout-tip title=\"Question 4 — Coefficient on `bavg`\"}\nA batting average $bavg$ higher by 10 points is associated with how many percentage points more salary, holding $years$ and $hrunsyr$ constant?\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\nThe model is log-lin in $bavg$. $\\hat\\beta_{bavg} =$ 0.00427. For 10 additional points:\n\n$$\\%\\Delta salary \\approx 100 \\cdot 0.00427 \\cdot 10 = \\mathbf{4.27\\%}$$\n:::\n\n\n## Exercise 5\n\nWe stay with the `mlb1` data, now interested in a possible **interaction** between $years$ and the dummy $nl$ (= 1 if the player plays in the National League, = 0 if in the American League):\n\n$$\\log(salary) = \\beta_0 + \\beta_1 \\, years + \\beta_2 \\, nl + \\beta_3 \\, (years \\cdot nl) + \\beta_4 \\, hrunsyr + u$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_int <- feols(log(salary) ~ years + nl + years:nl + hrunsyr,\n                     data = mlb1, vcov = \"hetero\")\n\nmodelsummary(list(\"Model with interaction\" = model_int),\n             gof_omit = \"AIC|BIC|RMSE|R2 Adj.\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_q8gkqxn1rlvoh7rwil50 = TinyTable.createTableFunctions(\"tinytable_q8gkqxn1rlvoh7rwil50\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '12', j: 2 } ], css_id: 'tinytable_css_aivafok9i982iqutg5nn',}, \n          { positions: [ { i: '10', j: 2 } ], css_id: 'tinytable_css_equuegiwq1pdqv0s9kwk',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '11', j: 2 } ], css_id: 'tinytable_css_01lx1iiglm1e8qhe52f6',}, \n          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_x2ohy8f5os8814vzp1ad',}, \n          { positions: [ { i: '12', j: 1 } ], css_id: 'tinytable_css_cg1syw7nitkwvnht9mb6',}, \n          { positions: [ { i: '10', j: 1 } ], css_id: 'tinytable_css_o1yr5iz12lbv9ps8kmvo',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '11', j: 1 } ], css_id: 'tinytable_css_z6xchjffcjajjicfedao',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_j4h0cmvof9lbyw8xmdwr',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_q8gkqxn1rlvoh7rwil50.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_q8gkqxn1rlvoh7rwil50 td.tinytable_css_aivafok9i982iqutg5nn, #tinytable_q8gkqxn1rlvoh7rwil50 th.tinytable_css_aivafok9i982iqutg5nn {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_q8gkqxn1rlvoh7rwil50 td.tinytable_css_equuegiwq1pdqv0s9kwk, #tinytable_q8gkqxn1rlvoh7rwil50 th.tinytable_css_equuegiwq1pdqv0s9kwk {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_q8gkqxn1rlvoh7rwil50 td.tinytable_css_01lx1iiglm1e8qhe52f6, #tinytable_q8gkqxn1rlvoh7rwil50 th.tinytable_css_01lx1iiglm1e8qhe52f6 { text-align: center }\n    #tinytable_q8gkqxn1rlvoh7rwil50 td.tinytable_css_x2ohy8f5os8814vzp1ad, #tinytable_q8gkqxn1rlvoh7rwil50 th.tinytable_css_x2ohy8f5os8814vzp1ad {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_q8gkqxn1rlvoh7rwil50 td.tinytable_css_cg1syw7nitkwvnht9mb6, #tinytable_q8gkqxn1rlvoh7rwil50 th.tinytable_css_cg1syw7nitkwvnht9mb6 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_q8gkqxn1rlvoh7rwil50 td.tinytable_css_o1yr5iz12lbv9ps8kmvo, #tinytable_q8gkqxn1rlvoh7rwil50 th.tinytable_css_o1yr5iz12lbv9ps8kmvo {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_q8gkqxn1rlvoh7rwil50 td.tinytable_css_z6xchjffcjajjicfedao, #tinytable_q8gkqxn1rlvoh7rwil50 th.tinytable_css_z6xchjffcjajjicfedao { text-align: left }\n    #tinytable_q8gkqxn1rlvoh7rwil50 td.tinytable_css_j4h0cmvof9lbyw8xmdwr, #tinytable_q8gkqxn1rlvoh7rwil50 th.tinytable_css_j4h0cmvof9lbyw8xmdwr {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_q8gkqxn1rlvoh7rwil50\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Model with interaction</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">12.196</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.111)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">years</td>\n                  <td data-row=\"3\" data-col=\"2\">0.115</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.016)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">nl</td>\n                  <td data-row=\"5\" data-col=\"2\">-0.127</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.191)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">hrunsyr</td>\n                  <td data-row=\"7\" data-col=\"2\">0.076</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\">(0.007)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">years × nl</td>\n                  <td data-row=\"9\" data-col=\"2\">0.031</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\">(0.032)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"11\" data-col=\"2\">353</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\">R2</td>\n                  <td data-row=\"12\" data-col=\"2\">0.504</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n### Questions\n\n::: {.callout-tip title=\"Question 1 — Interpretation of $\\\\hat\\\\beta_2$ and $\\\\hat\\\\beta_3$\"}\nHow do we interpret the coefficient on $nl$ ($\\hat\\beta_2$) and the coefficient on the interaction $years \\times nl$ ($\\hat\\beta_3$)?\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n- $\\hat\\beta_2 =$ -0.127 (coefficient on $nl$): the difference in $\\log(salary)$ between NL and AL **evaluated at** $years = 0$ (start of the career), holding $hrunsyr$ constant. This interpretation is not very useful because few players have 0 years of career (see Question 4 on centering).\n\n- $\\hat\\beta_3 =$ 0.031 (interaction): the **difference in the annual return** to experience between NL and AL. If $\\hat\\beta_3 \\neq 0$, the return to experience is **not the same** in the two leagues: in the NL it is $\\hat\\beta_1 + \\hat\\beta_3$, in the AL it is $\\hat\\beta_1$.\n:::\n\n\n::: {.callout-tip title=\"Question 2 — Marginal effect of `years` by league (calculation)\"}\nWhat is the marginal effect of $years$ for players in the **AL** ($nl = 0$) and in the **NL** ($nl = 1$)? What are their numerical values?\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n$$\\frac{\\partial \\log(salary)}{\\partial years} = \\hat\\beta_1 + \\hat\\beta_3 \\cdot nl$$\n\n- **AL** ($nl = 0$): $\\hat\\beta_1 =$ **0.115** → an additional year is associated with about $+11.5\\%$ more salary.\n- **NL** ($nl = 1$): $\\hat\\beta_1 + \\hat\\beta_3 =$ **0.146** → about $+14.6\\%$.\n\nThe apparent difference is about 3.1 percentage points per year in favor of the NL.\n:::\n\n\n::: {.callout-tip title=\"Question 3 — Significance of the interaction (multiple choice)\"}\nIs the interaction coefficient statistically significant at the 5% level? What can we conclude?\n\na) The return to experience is zero.\nb) The return to experience does **not** differ significantly between AL and NL.\nc) The variable $nl$ has no effect on salary.\nd) The model is misspecified.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n**Correct answer: b)**.\n\nThe interaction $years:nl$ has $|t| \\approx 0.96$, so it is **not significant at the 5% level**. We cannot reject the null hypothesis that the interaction coefficient is equal to zero.\n\n- a) is wrong: $\\hat\\beta_1$ is highly significant; experience pays.\n- c) confuses the interaction with the main effect of $nl$.\n- d) there is no evidence of misspecification from this single statistic.\n:::\n\n\n::: {.callout-tip title=\"Question 4 — Centering `years`\"}\nWe center $years$ at the **sample mean** ($\\overline{years} \\approx 6.33$) and re-estimate the model. How does the interpretation of the coefficient on $nl$ change?\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmlb1 <- mlb1 |>\n  mutate(years_c = years - mean(years))\n\nmodel_int_c <- feols(log(salary) ~ years_c + nl + years_c:nl + hrunsyr,\n                       data = mlb1, vcov = \"hetero\")\n\nmodelsummary(list(\"Original\" = model_int, \"Centered on years\" = model_int_c),\n             gof_omit = \"AIC|BIC|RMSE|R2 Adj.\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_30wb54ow0e7cn45e11ym = TinyTable.createTableFunctions(\"tinytable_30wb54ow0e7cn45e11ym\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '16', j: 2 }, { i: '16', j: 3 } ], css_id: 'tinytable_css_p1i89if89o5y9mvv5lva',}, \n          { positions: [ { i: '14', j: 2 }, { i: '14', j: 3 } ], css_id: 'tinytable_css_pti4o6s3pyh9jet9svs4',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '15', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 }, { i: '13', j: 3 }, { i: '15', j: 3 } ], css_id: 'tinytable_css_iupxo0792cwuju6sat8o',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_v64j0s9zu6ajlyi4hgmt',}, \n          { positions: [ { i: '16', j: 1 } ], css_id: 'tinytable_css_djoyq96bu641en3ii4yj',}, \n          { positions: [ { i: '14', j: 1 } ], css_id: 'tinytable_css_c47tfe3j3mqc49sfdqa8',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 }, { i: '15', j: 1 } ], css_id: 'tinytable_css_v8deawgc6lpgxfwgni7k',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_l912ixsc9x7qqn0j5g36',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_30wb54ow0e7cn45e11ym.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_30wb54ow0e7cn45e11ym td.tinytable_css_p1i89if89o5y9mvv5lva, #tinytable_30wb54ow0e7cn45e11ym th.tinytable_css_p1i89if89o5y9mvv5lva {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_30wb54ow0e7cn45e11ym td.tinytable_css_pti4o6s3pyh9jet9svs4, #tinytable_30wb54ow0e7cn45e11ym th.tinytable_css_pti4o6s3pyh9jet9svs4 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_30wb54ow0e7cn45e11ym td.tinytable_css_iupxo0792cwuju6sat8o, #tinytable_30wb54ow0e7cn45e11ym th.tinytable_css_iupxo0792cwuju6sat8o { text-align: center }\n    #tinytable_30wb54ow0e7cn45e11ym td.tinytable_css_v64j0s9zu6ajlyi4hgmt, #tinytable_30wb54ow0e7cn45e11ym th.tinytable_css_v64j0s9zu6ajlyi4hgmt {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_30wb54ow0e7cn45e11ym td.tinytable_css_djoyq96bu641en3ii4yj, #tinytable_30wb54ow0e7cn45e11ym th.tinytable_css_djoyq96bu641en3ii4yj {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_30wb54ow0e7cn45e11ym td.tinytable_css_c47tfe3j3mqc49sfdqa8, #tinytable_30wb54ow0e7cn45e11ym th.tinytable_css_c47tfe3j3mqc49sfdqa8 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_30wb54ow0e7cn45e11ym td.tinytable_css_v8deawgc6lpgxfwgni7k, #tinytable_30wb54ow0e7cn45e11ym th.tinytable_css_v8deawgc6lpgxfwgni7k { text-align: left }\n    #tinytable_30wb54ow0e7cn45e11ym td.tinytable_css_l912ixsc9x7qqn0j5g36, #tinytable_30wb54ow0e7cn45e11ym th.tinytable_css_l912ixsc9x7qqn0j5g36 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_30wb54ow0e7cn45e11ym\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Original</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Centered on years</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">12.196</td>\n                  <td data-row=\"1\" data-col=\"3\">12.923</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.111)</td>\n                  <td data-row=\"2\" data-col=\"3\">(0.079)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">years</td>\n                  <td data-row=\"3\" data-col=\"2\">0.115</td>\n                  <td data-row=\"3\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.016)</td>\n                  <td data-row=\"4\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">nl</td>\n                  <td data-row=\"5\" data-col=\"2\">-0.127</td>\n                  <td data-row=\"5\" data-col=\"3\">0.068</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.191)</td>\n                  <td data-row=\"6\" data-col=\"3\">(0.094)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">hrunsyr</td>\n                  <td data-row=\"7\" data-col=\"2\">0.076</td>\n                  <td data-row=\"7\" data-col=\"3\">0.076</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\">(0.007)</td>\n                  <td data-row=\"8\" data-col=\"3\">(0.007)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">years × nl</td>\n                  <td data-row=\"9\" data-col=\"2\">0.031</td>\n                  <td data-row=\"9\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\">(0.032)</td>\n                  <td data-row=\"10\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">years_c</td>\n                  <td data-row=\"11\" data-col=\"2\"></td>\n                  <td data-row=\"11\" data-col=\"3\">0.115</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\"></td>\n                  <td data-row=\"12\" data-col=\"2\"></td>\n                  <td data-row=\"12\" data-col=\"3\">(0.016)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">years_c × nl</td>\n                  <td data-row=\"13\" data-col=\"2\"></td>\n                  <td data-row=\"13\" data-col=\"3\">0.031</td>\n                </tr>\n                <tr>\n                  <td data-row=\"14\" data-col=\"1\"></td>\n                  <td data-row=\"14\" data-col=\"2\"></td>\n                  <td data-row=\"14\" data-col=\"3\">(0.032)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"15\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"15\" data-col=\"2\">353</td>\n                  <td data-row=\"15\" data-col=\"3\">353</td>\n                </tr>\n                <tr>\n                  <td data-row=\"16\" data-col=\"1\">R2</td>\n                  <td data-row=\"16\" data-col=\"2\">0.504</td>\n                  <td data-row=\"16\" data-col=\"3\">0.504</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\nIn the **centered** model, $\\hat\\beta_{nl} =$ 0.068 represents the difference between NL and AL **for a player with career years equal to the sample mean** ($\\approx$ 6.33 years), no longer at $years = 0$. This is a much more informative value, because it is evaluated at a point of the distribution where there are many observations.\n\nNote that $\\hat\\beta_1$ (the effect of $years$ in the AL), $\\hat\\beta_3$ (the interaction), and $\\hat\\beta_4$ (the effect of $hrunsyr$) **do not change**: centering only redefines the intercept and the coefficient on $nl$.\n:::\n\n\n## Exercise 6 — Binary Dependent Variable (LPM vs Logit)\n\nThe labor force participation of married women is a classic topic in labor economics. When the dependent variable is binary (the woman is in the labor force: yes/no), we must choose among different econometric models.\n\nWe use the `mroz` dataset (Mroz, 1987), which contains information on 753 married women. We analyze the factors associated with the probability of participating in the labor market.\n\n| variable | description |\n|-----------|-------------|\n| `inlf`     | =1 if the woman is in the labor force, =0 otherwise |\n| `nwifeinc` | family income not earned by the woman (in thousands of \\$) |\n| `educ`     | years of education |\n| `exper`    | years of work experience |\n| `expersq`  | experience squared (`exper^2`) |\n| `age`      | age in years |\n| `kidslt6`  | number of children under 6 years old |\n| `kidsge6`  | number of children between 6 and 18 years old |\n\nWe estimate two models:\n\n- **Model A** — Linear Probability Model (LPM)\n- **Model B** — Logit model\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"mroz\", package = \"wooldridge\")\n\nmA_lpm <- feols(inlf ~ nwifeinc + educ + exper + expersq + age + kidslt6 + kidsge6,\n                vcov = \"hetero\", data = mroz)\n\nmB_logit <- feglm(inlf ~ nwifeinc + educ + exper + expersq + age + kidslt6 + kidsge6,\n                  family = binomial(link = \"logit\"), data = mroz)\n\nmodelsummary(list(\"LPM\" = mA_lpm, \"Logit\" = mB_logit), gof_omit = \"AIC|BIC|RMSE|R2 Adj.\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_474pyg6i6wes7kzrv8pz = TinyTable.createTableFunctions(\"tinytable_474pyg6i6wes7kzrv8pz\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '18', j: 2 }, { i: '18', j: 3 } ], css_id: 'tinytable_css_zxf7phkbz0bqo9w48vch',}, \n          { positions: [ { i: '16', j: 2 }, { i: '16', j: 3 } ], css_id: 'tinytable_css_471t4cbli91e06j6vm1s',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '14', j: 2 }, { i: '15', j: 2 }, { i: '17', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 }, { i: '13', j: 3 }, { i: '14', j: 3 }, { i: '15', j: 3 }, { i: '17', j: 3 } ], css_id: 'tinytable_css_8bxyxno2dqun01sfdsui',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_djg4np88odnwfze224w6',}, \n          { positions: [ { i: '18', j: 1 } ], css_id: 'tinytable_css_pk5d5t7881ode7oz0ja5',}, \n          { positions: [ { i: '16', j: 1 } ], css_id: 'tinytable_css_d29tok9g0543w0rko5wv',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 }, { i: '14', j: 1 }, { i: '15', j: 1 }, { i: '17', j: 1 } ], css_id: 'tinytable_css_qbabsdxtjutzr2fk4byy',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_dtg9yvn4pzsn0xy6qppq',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_474pyg6i6wes7kzrv8pz.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_474pyg6i6wes7kzrv8pz td.tinytable_css_zxf7phkbz0bqo9w48vch, #tinytable_474pyg6i6wes7kzrv8pz th.tinytable_css_zxf7phkbz0bqo9w48vch {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_474pyg6i6wes7kzrv8pz td.tinytable_css_471t4cbli91e06j6vm1s, #tinytable_474pyg6i6wes7kzrv8pz th.tinytable_css_471t4cbli91e06j6vm1s {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_474pyg6i6wes7kzrv8pz td.tinytable_css_8bxyxno2dqun01sfdsui, #tinytable_474pyg6i6wes7kzrv8pz th.tinytable_css_8bxyxno2dqun01sfdsui { text-align: center }\n    #tinytable_474pyg6i6wes7kzrv8pz td.tinytable_css_djg4np88odnwfze224w6, #tinytable_474pyg6i6wes7kzrv8pz th.tinytable_css_djg4np88odnwfze224w6 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_474pyg6i6wes7kzrv8pz td.tinytable_css_pk5d5t7881ode7oz0ja5, #tinytable_474pyg6i6wes7kzrv8pz th.tinytable_css_pk5d5t7881ode7oz0ja5 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_474pyg6i6wes7kzrv8pz td.tinytable_css_d29tok9g0543w0rko5wv, #tinytable_474pyg6i6wes7kzrv8pz th.tinytable_css_d29tok9g0543w0rko5wv {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_474pyg6i6wes7kzrv8pz td.tinytable_css_qbabsdxtjutzr2fk4byy, #tinytable_474pyg6i6wes7kzrv8pz th.tinytable_css_qbabsdxtjutzr2fk4byy { text-align: left }\n    #tinytable_474pyg6i6wes7kzrv8pz td.tinytable_css_dtg9yvn4pzsn0xy6qppq, #tinytable_474pyg6i6wes7kzrv8pz th.tinytable_css_dtg9yvn4pzsn0xy6qppq {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_474pyg6i6wes7kzrv8pz\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">LPM</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Logit</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">0.586</td>\n                  <td data-row=\"1\" data-col=\"3\">0.425</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.152)</td>\n                  <td data-row=\"2\" data-col=\"3\">(0.864)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">nwifeinc</td>\n                  <td data-row=\"3\" data-col=\"2\">-0.003</td>\n                  <td data-row=\"3\" data-col=\"3\">-0.021</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.002)</td>\n                  <td data-row=\"4\" data-col=\"3\">(0.008)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">educ</td>\n                  <td data-row=\"5\" data-col=\"2\">0.038</td>\n                  <td data-row=\"5\" data-col=\"3\">0.221</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.007)</td>\n                  <td data-row=\"6\" data-col=\"3\">(0.044)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">exper</td>\n                  <td data-row=\"7\" data-col=\"2\">0.039</td>\n                  <td data-row=\"7\" data-col=\"3\">0.206</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\">(0.006)</td>\n                  <td data-row=\"8\" data-col=\"3\">(0.032)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">expersq</td>\n                  <td data-row=\"9\" data-col=\"2\">-0.001</td>\n                  <td data-row=\"9\" data-col=\"3\">-0.003</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\">(0.000)</td>\n                  <td data-row=\"10\" data-col=\"3\">(0.001)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">age</td>\n                  <td data-row=\"11\" data-col=\"2\">-0.016</td>\n                  <td data-row=\"11\" data-col=\"3\">-0.088</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\"></td>\n                  <td data-row=\"12\" data-col=\"2\">(0.002)</td>\n                  <td data-row=\"12\" data-col=\"3\">(0.015)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">kidslt6</td>\n                  <td data-row=\"13\" data-col=\"2\">-0.262</td>\n                  <td data-row=\"13\" data-col=\"3\">-1.443</td>\n                </tr>\n                <tr>\n                  <td data-row=\"14\" data-col=\"1\"></td>\n                  <td data-row=\"14\" data-col=\"2\">(0.032)</td>\n                  <td data-row=\"14\" data-col=\"3\">(0.205)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"15\" data-col=\"1\">kidsge6</td>\n                  <td data-row=\"15\" data-col=\"2\">0.013</td>\n                  <td data-row=\"15\" data-col=\"3\">0.060</td>\n                </tr>\n                <tr>\n                  <td data-row=\"16\" data-col=\"1\"></td>\n                  <td data-row=\"16\" data-col=\"2\">(0.014)</td>\n                  <td data-row=\"16\" data-col=\"3\">(0.075)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"17\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"17\" data-col=\"2\">753</td>\n                  <td data-row=\"17\" data-col=\"3\">753</td>\n                </tr>\n                <tr>\n                  <td data-row=\"18\" data-col=\"1\">R2</td>\n                  <td data-row=\"18\" data-col=\"2\">0.264</td>\n                  <td data-row=\"18\" data-col=\"3\">0.220</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\nThe **average marginal effects** (AME) of the Logit model are:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmarginaleffects::avg_slopes(mB_logit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Term  Estimate Std. Error      z Pr(>|z|)    S     2.5 %    97.5 %\n age      -0.015719   0.002392 -6.572  < 0.001 34.2 -0.020407 -0.011031\n educ      0.039497   0.007329  5.389  < 0.001 23.8  0.025133  0.053860\n exper     0.036764   0.005174  7.105  < 0.001 39.6  0.026623  0.046905\n expersq  -0.000563   0.000178 -3.161  0.00157  9.3 -0.000912 -0.000214\n kidsge6   0.010735   0.013395  0.801  0.42290  1.2 -0.015519  0.036989\n kidslt6  -0.257754   0.032092 -8.032  < 0.001 49.9 -0.320652 -0.194855\n nwifeinc -0.003812   0.001489 -2.559  0.01049  6.6 -0.006731 -0.000893\n\nType: response\nComparison: dY/dX\n```\n\n\n:::\n:::\n\n\n\n::: {.callout-tip title=\"Question 1 — Interpreting the LPM\"}\nAccording to the LPM (Model A), having **one additional child under 6 years old** (`kidslt6`) is associated with a (**decrease** / **increase**) of ______ percentage points in the probability of participating in the labor market, holding the other variables constant.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\nA **decrease** of about **26.18 percentage points**.\n\nThe coefficient on `kidslt6` in the LPM is -0.2618. In the LPM the coefficient is directly the change in the probability ($\\times 100$ to read it in percentage points): having one additional young child is **associated with** a markedly lower probability of participation.\n:::\n\n\n::: {.callout-tip title=\"Question 2 — Logit coefficients (T/F)\"}\nSelect **all** the correct statements:\n\n1. Logit coefficients represent the effect on the *log(odds)*, not on the probability.\n2. In the logit, the marginal effect of a variable on the probability depends on the level of **all** the explanatory variables.\n3. One way to interpret them in terms of probability is to compute the average marginal effects (AME).\n4. Logit coefficients directly represent the change in the probability.\n5. Logit coefficients are always larger (in absolute value) than those of the LPM.\n6. In both models the marginal effect is constant for all individuals.\n7. Logit coefficients become probabilities if multiplied by 100.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\nCorrect: **1, 2, 3**.\n\nIn the logit, $P(y=1\\mid x) = \\Lambda(x'\\beta)$ is nonlinear: the coefficient enters inside the logistic function, so it measures the effect on the *log(odds)* (1), and the effect on the probability changes depending on the point at which it is evaluated (2). To bring it back to the probability scale we compute the marginal effects (3). Statements 4 and 7 are false (they would hold for the LPM, not for the logit); statement 5 confuses the scale of the coefficients with that of the effects; statement 6 is false for the logit (it is true only for the LPM).\n:::\n\n\n::: {.callout-tip title=\"Question 3 — Marginal effect in the logit\"}\nAccording to Model B (Logit), **4 additional years of education** (`educ`) are associated with a (**decrease** / **increase**) of ______ percentage points in the probability of participating.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\nAn **increase** of about **15.80 percentage points**.\n\nThe AME of `educ` is $0.0395$ per year. For 4 years: $4 \\times 0.0395 = 0.158$, that is, $\\approx 15.80$ percentage points. (The AME is an average: for an individual woman the effect depends on her characteristics.)\n:::\n\n\n::: {.callout-tip title=\"Question 4 — Confidence interval\"}\nStill for the effect of **4 additional years of education** in the logit, the 95% confidence interval (in percentage points) is approximately ( ______ , ______ ).\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\nApproximately **(10.05, 21.54)** percentage points.\n\nThe AME of `educ` has interval $[0.0251;\\ 0.0539]$. Multiplying by 4 years and by 100: $[\\,4 \\times 2.51\\ ;\\ 4 \\times 5.39\\,] \\approx [10.05;\\ 21.54]$. The interval does not contain zero: the effect is significant at the 5% level.\n:::\n\n\n::: {.callout-tip title=\"Question 5 — LPM vs Logit comparison\"}\nIndicate **all** the correct statements:\n\n1. In the LPM, **2 additional children** under age 6 are associated with a reduction in the probability of about 52.36 percentage points.\n2. In the logit (AME), **one additional child** under age 6 is associated with a reduction of about 25.78 percentage points.\n3. In the LPM, an additional year of education is associated with an increase of about 3.80 percentage points.\n4. The estimated effects on the probability are identical in the two models.\n5. The logit always predicts larger effects than the LPM.\n6. Education does not have a statistically significant effect in either model.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\nCorrect: **1, 2, 3**.\n\n1. LPM `kidslt6` $= -0.2618$; for 2 children: $2 \\times 26.18 = 52.36$ pp. ✔\n2. Logit AME `kidslt6` $= -0.2578 \\to 25.78$ pp. ✔\n3. LPM `educ` $= 0.0380 \\to 3.80$ pp. ✔\n4. False: the LPM and the logit give similar but not identical effects. 5. False: there is no general rule. 6. False: `educ` is significant in both.\n:::\n\n\n::: {.callout-tip title=\"Question 6 — Difference in predicted probability (LPM)\"}\nUsing the LPM (Model A), compare two women identical in `nwifeinc` (=20), `exper` (=10), `age` (=40), and `kidsge6` (=1), but different as follows:\n\n- **Woman A**: `educ` = 16, `kidslt6` = 0\n- **Woman B**: `educ` = 12, `kidslt6` = 2\n\nThe difference in the predicted probability of participation (A − B) is about ______ percentage points.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\nAbout **67.56 percentage points**.\n\nThe difference depends only on the variables that change:\n\n- education: $(16-12) \\times$ 0.038 $=$ 0.152\n- young children: $(0-2) \\times$ -0.2618 $=$ 0.5236\n\nTotal: 0.6756 → 67.56 percentage points. Woman A has a much higher predicted probability than woman B.\n:::\n\n\n## Exercise 7 — Regression with Panel Data\n\nDo firms that receive **job training grants** really improve their productivity? We measure productivity with the *scrap rate* (`scrap`: defective items per 100 produced); we use its logarithm `lscrap`.\n\nThe problem is the **endogeneity** of `grant`: grants are not randomly assigned, and firms with more quality problems may be more likely to apply for them (or to obtain them).\n\n\nWe use the panel dataset `jtrain`, which follows a sample of Michigan manufacturing firms for 3 years (1987–1989).\n\n| variable | description |\n|-----------|-------------|\n| `fcode`    | firm identification code |\n| `year`     | year of the observation |\n| `lscrap`   | logarithm of the scrap rate (inverse proxy for productivity) |\n| `grant`    | =1 if the firm received the training grant in that year (time-varying) |\n| `lsales`   | log of sales |\n| `lemploy`  | log of the number of employees |\n| `union`    | =1 if the firm has a unionized workforce (time-invariant) |\n\n- **Model A (Pooled OLS)**: ignores the panel structure\n- **Model B (firm FE)**: firm fixed effects\n- **Model C (firm + year FE)**: firm and year fixed effects\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"jtrain\", package = \"wooldridge\")\n\nm_ols <- feols(lscrap ~ grant + lsales + lemploy + union,\n               vcov = \"hetero\", data = jtrain)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNOTE: 323 observations removed because of NA values (LHS: 309, RHS: 112).\n```\n\n\n:::\n\n```{.r .cell-code}\nm_fe  <- feols(lscrap ~ grant + lsales + lemploy + union | fcode,\n               vcov = \"cluster\", data = jtrain)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNOTES: 323 observations removed because of NA values (LHS: 309, RHS: 112).\n       1 fixed-effect singleton was removed (1 observation).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe variable 'union' has been removed because of collinearity (see $collin.var).\n```\n\n\n:::\n\n```{.r .cell-code}\nm_fet <- feols(lscrap ~ grant + lsales + lemploy + union | fcode + year,\n               vcov = \"cluster\", data = jtrain)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNOTES: 323 observations removed because of NA values (LHS: 309, RHS: 112).\n       1/0 fixed-effect singleton was removed (1 observation).\nThe variable 'union' has been removed because of collinearity (see $collin.var).\n```\n\n\n:::\n\n```{.r .cell-code}\nmodelsummary(list(\"Pooled OLS (A)\" = m_ols, \"Firm FE (B)\" = m_fe, \"Firm+Year FE (C)\" = m_fet), gof_omit = \"AIC|BIC|RMSE|R2 Adj.\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_nkldc60l6clva4r2vyxu = TinyTable.createTableFunctions(\"tinytable_nkldc60l6clva4r2vyxu\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '16', j: 2 }, { i: '16', j: 3 }, { i: '16', j: 4 } ], css_id: 'tinytable_css_yal1cp73zkwlk7ib91dx',}, \n          { positions: [ { i: '10', j: 2 }, { i: '10', j: 3 }, { i: '10', j: 4 } ], css_id: 'tinytable_css_8sdkirikl1p63tqbelmn',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '14', j: 2 }, { i: '15', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 }, { i: '13', j: 3 }, { i: '14', j: 3 }, { i: '15', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '3', j: 4 }, { i: '4', j: 4 }, { i: '5', j: 4 }, { i: '6', j: 4 }, { i: '7', j: 4 }, { i: '8', j: 4 }, { i: '9', j: 4 }, { i: '11', j: 4 }, { i: '12', j: 4 }, { i: '13', j: 4 }, { i: '14', j: 4 }, { i: '15', j: 4 } ], css_id: 'tinytable_css_hnx18z5pvirzsdf9lijv',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 } ], css_id: 'tinytable_css_kb1rt4ox26q1rwtyvlzn',}, \n          { positions: [ { i: '16', j: 1 } ], css_id: 'tinytable_css_n90255w8xp0yr05lxm2e',}, \n          { positions: [ { i: '10', j: 1 } ], css_id: 'tinytable_css_9grflwvhk1qqi6bky941',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 }, { i: '14', j: 1 }, { i: '15', j: 1 } ], css_id: 'tinytable_css_kqpmy7bvpg11xmiowrg4',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_asr1zxlcb48lpqe172el',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_nkldc60l6clva4r2vyxu.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_nkldc60l6clva4r2vyxu td.tinytable_css_yal1cp73zkwlk7ib91dx, #tinytable_nkldc60l6clva4r2vyxu th.tinytable_css_yal1cp73zkwlk7ib91dx {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_nkldc60l6clva4r2vyxu td.tinytable_css_8sdkirikl1p63tqbelmn, #tinytable_nkldc60l6clva4r2vyxu th.tinytable_css_8sdkirikl1p63tqbelmn {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_nkldc60l6clva4r2vyxu td.tinytable_css_hnx18z5pvirzsdf9lijv, #tinytable_nkldc60l6clva4r2vyxu th.tinytable_css_hnx18z5pvirzsdf9lijv { text-align: center }\n    #tinytable_nkldc60l6clva4r2vyxu td.tinytable_css_kb1rt4ox26q1rwtyvlzn, #tinytable_nkldc60l6clva4r2vyxu th.tinytable_css_kb1rt4ox26q1rwtyvlzn {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_nkldc60l6clva4r2vyxu td.tinytable_css_n90255w8xp0yr05lxm2e, #tinytable_nkldc60l6clva4r2vyxu th.tinytable_css_n90255w8xp0yr05lxm2e {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_nkldc60l6clva4r2vyxu td.tinytable_css_9grflwvhk1qqi6bky941, #tinytable_nkldc60l6clva4r2vyxu th.tinytable_css_9grflwvhk1qqi6bky941 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_nkldc60l6clva4r2vyxu td.tinytable_css_kqpmy7bvpg11xmiowrg4, #tinytable_nkldc60l6clva4r2vyxu th.tinytable_css_kqpmy7bvpg11xmiowrg4 { text-align: left }\n    #tinytable_nkldc60l6clva4r2vyxu td.tinytable_css_asr1zxlcb48lpqe172el, #tinytable_nkldc60l6clva4r2vyxu th.tinytable_css_asr1zxlcb48lpqe172el {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_nkldc60l6clva4r2vyxu\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Pooled OLS (A)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Firm FE (B)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Firm+Year FE (C)</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">9.896</td>\n                  <td data-row=\"1\" data-col=\"3\"></td>\n                  <td data-row=\"1\" data-col=\"4\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(2.629)</td>\n                  <td data-row=\"2\" data-col=\"3\"></td>\n                  <td data-row=\"2\" data-col=\"4\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">grant</td>\n                  <td data-row=\"3\" data-col=\"2\">0.116</td>\n                  <td data-row=\"3\" data-col=\"3\">-0.110</td>\n                  <td data-row=\"3\" data-col=\"4\">-0.089</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.244)</td>\n                  <td data-row=\"4\" data-col=\"3\">(0.077)</td>\n                  <td data-row=\"4\" data-col=\"4\">(0.076)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">lsales</td>\n                  <td data-row=\"5\" data-col=\"2\">-0.828</td>\n                  <td data-row=\"5\" data-col=\"3\">-0.368</td>\n                  <td data-row=\"5\" data-col=\"4\">-0.065</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.213)</td>\n                  <td data-row=\"6\" data-col=\"3\">(0.248)</td>\n                  <td data-row=\"6\" data-col=\"4\">(0.194)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">lemploy</td>\n                  <td data-row=\"7\" data-col=\"2\">0.765</td>\n                  <td data-row=\"7\" data-col=\"3\">0.135</td>\n                  <td data-row=\"7\" data-col=\"4\">-0.015</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\">(0.195)</td>\n                  <td data-row=\"8\" data-col=\"3\">(0.385)</td>\n                  <td data-row=\"8\" data-col=\"4\">(0.286)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">union</td>\n                  <td data-row=\"9\" data-col=\"2\">0.863</td>\n                  <td data-row=\"9\" data-col=\"3\"></td>\n                  <td data-row=\"9\" data-col=\"4\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\">(0.251)</td>\n                  <td data-row=\"10\" data-col=\"3\"></td>\n                  <td data-row=\"10\" data-col=\"4\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"11\" data-col=\"2\">148</td>\n                  <td data-row=\"11\" data-col=\"3\">147</td>\n                  <td data-row=\"11\" data-col=\"4\">147</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\">R2</td>\n                  <td data-row=\"12\" data-col=\"2\">0.154</td>\n                  <td data-row=\"12\" data-col=\"3\">0.913</td>\n                  <td data-row=\"12\" data-col=\"4\">0.923</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">R2 Within</td>\n                  <td data-row=\"13\" data-col=\"2\"></td>\n                  <td data-row=\"13\" data-col=\"3\">0.050</td>\n                  <td data-row=\"13\" data-col=\"4\">0.008</td>\n                </tr>\n                <tr>\n                  <td data-row=\"14\" data-col=\"1\">R2 Within Adj.</td>\n                  <td data-row=\"14\" data-col=\"2\"></td>\n                  <td data-row=\"14\" data-col=\"3\">0.019</td>\n                  <td data-row=\"14\" data-col=\"4\">-0.024</td>\n                </tr>\n                <tr>\n                  <td data-row=\"15\" data-col=\"1\">FE: fcode</td>\n                  <td data-row=\"15\" data-col=\"2\"></td>\n                  <td data-row=\"15\" data-col=\"3\">X</td>\n                  <td data-row=\"15\" data-col=\"4\">X</td>\n                </tr>\n                <tr>\n                  <td data-row=\"16\" data-col=\"1\">FE: year</td>\n                  <td data-row=\"16\" data-col=\"2\"></td>\n                  <td data-row=\"16\" data-col=\"3\"></td>\n                  <td data-row=\"16\" data-col=\"4\">X</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n::: {.callout-tip title=\"Question 1 — Interpreting the Pooled OLS\"}\nAccording to Model A (Pooled OLS), receiving the grant in the current year (`grant`) is associated with a scrap rate higher by about ______ (**percentage points** / **dollars** / **%**).\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\nAbout **11.6 %** (units: **%**, because the dependent variable is in logarithms).\n\nThe coefficient on `grant` in OLS is 0.116. The sign is **positive** (and implausible): it is a symptom of selection bias — firms with more scrap tend to receive the grant. OLS confounds the effect of the grant with the characteristics of the firms that obtain it.\n:::\n\n\n::: {.callout-tip title=\"Question 2 — Interpreting the fixed effects\"}\nAccording to Model B (firm FE), which controls for all fixed characteristics of the firm, receiving the grant in the current year is associated with a scrap rate (**lower** / **higher**) by about ______ (**percentage points** / **dollars** / **%**).\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n**Lower** by about **11 %** (units: **%**).\n\nThe coefficient on `grant` in the firm FE model is -0.1102. Once fixed differences across firms are eliminated, the sign flips: the grant is now **associated with** a reduction in the scrap rate. This is the classic effect of correcting for time-invariant omitted variables.\n:::\n\n\n::: {.callout-tip title=\"Question 3 — Bias and omitted variables\"}\nWhich statements about the bias in the estimate of the grant effect are correct? (multiple selection)\n\n1. The difference between the OLS coefficient and the FE coefficients is too small to be relevant.\n2. Firm fixed effects (B and C) correct the bias from any unobserved omitted variable that is constant over time for each firm.\n3. Introducing time and firm fixed effects corrects **every** type of endogeneity, including reverse causality and measurement error.\n4. Time fixed effects (C) capture shocks common to all firms in a given year (e.g., a recession).\n5. Fixed effects cannot do anything about omitted variables that vary over time within a single firm.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\nCorrect: **2, 4, 5**.\n\nStatement 1 is false: the coefficient goes from about $+0.12$ to $-0.11$, a substantial change (even the sign changes). Statement 3 is false: fixed effects eliminate only unobserved heterogeneity that is **constant over time**, not reverse causality or measurement error. Statements 2, 4, and 5 correctly describe what fixed effects do (and do not do).\n:::\n\n\n::: {.callout-tip title=\"Question 4 — Which coefficients can be estimated?\"}\nIn Models B and C the coefficient on `union` does not appear. Which statements are correct? (multiple selection)\n\n1. In Models B and C, `union` cannot be estimated because it is **constant over time** for each firm: its variability is entirely absorbed by the firm fixed effects.\n2. `grant` can be estimated in the FE models because it varies over time within the same firm.\n3. `union` could be estimated in Model C if it were statistically significant.\n4. The impossibility of estimating `union` is due to a software error.\n5. With firm fixed effects, a time-invariant regressor is perfectly collinear with the fixed effects.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\nCorrect: **1, 2, 5**.\n\n`union` is constant within each firm over the 3 years: after the *within* transformation (deviations from the firm mean) it becomes identically zero, so it is collinear with the fixed effects and is dropped (1, 5). `grant`, on the other hand, changes over time within the same firm and remains estimable (2). Statements 3 and 4 are false: it is not a matter of significance, nor a software bug.\n:::\n\n\n::: {.callout-tip title=\"Question 5 — Clustered standard errors\"}\nIn Models B and C the standard errors are *clustered* by firm (`fcode`). Which statements are correct? (multiple selection)\n\n1. Clustering is needed because observations from the same firm in different years are not independent (serial correlation in the errors).\n2. Using standard errors that are too small increases the probability of wrongly rejecting $H_0$ (Type I error).\n3. Omitting clustering, in the presence of serial correlation, tends to produce underestimated standard errors.\n4. Clustering corrects the bias in the coefficients due to omitted variables.\n5. If a coefficient is not significant, clustering can make it significant.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\nCorrect: **1, 2, 3**.\n\nClustering concerns the **standard errors** (the inference), not the coefficients: this is why statement 4 is false. Statement 5 is false: clustering generally **widens** the standard errors, making significance harder (not easier) to achieve. Statements 1, 2, and 3 correctly explain why clustering is needed and what happens if it is omitted.\n:::\n",
    "supporting": [
      "problem_set_01_solutions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}